### ISSUE TITLE
Missing definition for logs config will cause crash if traces config refers to it

### ISSUE THREAD

**Issue by hedss** [grafana/agent#1056]
In latest Docker image of Grafana Agent (035789abfc69) or v0.20.0 and v0.19.0, if you have a configuration file that does not define a logs section, but that attempts to reference a logs section in the tracing config, a crash will occur.

Config:
```
server: 
  log_level: debug

traces:
  configs:
  - name: tempo
    receivers:
      jaeger:
        protocols:
          grpc:
          thrift_binary:
          thrift_compact:
          thrift_http:
    service_graphs:
      enabled: false
    remote_write:
      - endpoint: tempo:55680
        insecure: true
    tail_sampling:
      policies:
        - latency:
            threshold_ms: 60
    automatic_logging:
        backend: logs_instance
        logs_instance_name: loki
        roots: true
        span_attributes:
          - "service.name"
          - "http.target"
          - "otel.status_code"
        labels:
          - "job=agent"
        overrides:
          trace_id_key: "traceId"
```
Results in:
```
grafana_demo-agent-1  | panic: runtime error: invalid memory address or nil pointer dereference
grafana_demo-agent-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x29fea8a]
grafana_demo-agent-1  | 
grafana_demo-agent-1  | goroutine 1 [running]:
grafana_demo-agent-1  | github.com/grafana/agent/pkg/traces/automaticloggingprocessor.(*AutomaticLoggingConfig).Validate(0xc000882800, 0x0, 0xc00021df48, 0x5)
grafana_demo-agent-1  |         /src/agent/pkg/traces/automaticloggingprocessor/factory.go:69 +0x16a
grafana_demo-agent-1  | github.com/grafana/agent/pkg/traces.(*Config).Validate(0xc00086c910, 0x0, 0x0, 0x0)
grafana_demo-agent-1  |         /src/agent/pkg/traces/config.go:87 +0x168
grafana_demo-agent-1  | github.com/grafana/agent/pkg/config.(*Config).ApplyDefaults(0xc00086c000, 0xc00004e1f0, 0x2)
grafana_demo-agent-1  |         /src/agent/pkg/config/config.go:136 +0x185
grafana_demo-agent-1  | github.com/grafana/agent/pkg/config.load(0xc00012ce40, 0xc00004e1f0, 0x2, 0x2, 0x41d90a8, 0x0, 0xc0007dde98, 0x411918)
grafana_demo-agent-1  |         /src/agent/pkg/config/config.go:243 +0x51b
grafana_demo-agent-1  | github.com/grafana/agent/pkg/config.Load(...)
grafana_demo-agent-1  |         /src/agent/pkg/config/config.go:202
grafana_demo-agent-1  | main.main.func1(0x391bdc0, 0xc00072ebf0, 0xf548227c8846)
grafana_demo-agent-1  |         /src/agent/cmd/agent/main.go:46 +0x130
grafana_demo-agent-1  | main.main()
grafana_demo-agent-1  |         /src/agent/cmd/agent/main.go:52 +0x91
```

There should be verification of the config before attempting to use the section that doesn't exist (the reference to `loki` that is not defined).
