### ISSUE TITLE
Extend Agent to send recording rules to Cortex ruler API

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#111]
The process of migrating from a Prometheus/OpenMetrics system that supports recording rules to the Agent is made more difficult by the total lack of knowledge about recording rules from within the Agent. While there are currently no plans to support recording rules within the Agent, the Agent could act as a client to the Cortex rules API. This lets users use the Agent with a more complete Prometheus-like config and not have to install yet another tool for their migration (i.e., like the very useful [cortextool](https://github.com/grafana/cortex-tools#cortextool)).

For example, we could add `rule_files` to the instance config:

```yaml
server:
  log_level: info
  http_listen_port: 12345

prometheus:
  global:
    scrape_interval: 5s
  configs:
    - name: test
      host_filter: false
      ###################
      ### THIS IS NEW ### 
      ###################
      rule_files: 
         - recording-rules.yml 
      scrape_configs:
        - job_name: local_scrape
          static_configs:
            - targets: ['127.0.0.1:12345']
              labels:
                cluster: 'localhost'
      remote_write:
        - url: http://localhost:9009/api/prom/push
```

/cc @gotjosh
