### ISSUE TITLE
Grafana Cloud Linux integration not displaying data

### ISSUE THREAD

**Issue by loganmc10** [grafana/agent#1125]
I have the Grafana Agent running on some Linux VMs (Ubuntu 20.04) in Azure. They were recently updated from kernel 5.8 to 5.11 (there might have been some other updates in there as well).

Now it appears like CPU stats are only collected about every 5 minutes, and there are no stats for Disk IO or network:

![image](https://user-images.githubusercontent.com/848146/142918738-fcda8881-1e8b-4f69-a5b4-8082fab21b01.png)

I confirmed that the configuration file hasn't changed. The VMs are all running v0.21.1

**Comment by mattdurham** [comment]
What is your minimum step on the CPU Usage chart? If you explore can you see the  node_cpu_seconds_total flowing normally?

**Comment by loganmc10** [comment]
We are Grafana Cloud customers, so this dashboard is from the Linux Integration (not editable), but this is what the Explore interface looks like:

![image](https://user-images.githubusercontent.com/848146/142940912-1534df6d-0feb-430a-9bf8-34127f73e770.png)

This is the grafana-agent.yaml
```
integrations:
  node_exporter:
    enabled: true
  postgres_exporter:
    data_source_names:
    - postgresql://root@localhost:5432
    enabled: false
  prometheus_remote_write:
  - basic_auth:
      password: ****
      username: ****
    url: https://prometheus-us-central2.grafana.net/api/prom/push
  redis_exporter:
    enabled: false
    redis_addr: localhost:6379
loki:
  configs:
  - clients:
    - basic_auth:
        password: ****
        username: ****
      url: https://logs-prod-us-central2.grafana.net/api/prom/push
    name: integrations
    positions:
      filename: /tmp/positions.yaml
    target_config:
      sync_period: 10s
prometheus:
  configs:
  - name: integrations
    remote_write:
    - basic_auth:
        password: ****
        username: ****
      url: https://prometheus-us-central2.grafana.net/api/prom/push
    scrape_configs:
    - job_name: integrations/rabbitmq
      static_configs:
      - targets:
        - rabbitmq:15692
  global:
    scrape_interval: 60s
  wal_directory: /tmp/grafana-agent-wal
server:
  http_listen_port: 12345
```
