### ISSUE TITLE
A reboot is needed to make a change of hostname effective.

### ISSUE THREAD

**Issue by jackliusr** [grafana/agent#1131]
I changed hostnames, stopped the grafana-agent service, delete the wal folder and restarted the grafana-agent service.  grafana-agent still use the old hostnames and doesn't pick up the change of hostnames.  

https://github.com/grafana/agent/blob/414f92c3929d391dcdc2a0b7932b424aed655ef3/pkg/metrics/instance/instance.go#L747

**Comment by rlankfo** [comment]
@jackliusr every process has it's own copy of the environment. Can you confirm if the `HOSTNAME` env var value (in the shell you launched the agent from) changed to the updated hostname value?

**Comment by jackliusr** [comment]
I used ubuntu 20.04. and run grafana-agent as systemd service. I changed the hostname via ansible hostname module with systemd .   I think systemd init will keep using the original HOSTNAME  and pass it to grafana-agent systemd service unit.

```yaml
- name: Set a hostname specifying strategy
  ansible.builtin.hostname:
    name: web01
    use: systemd
```
