### ISSUE TITLE
Job label of the "up" metric

### ISSUE THREAD

**Issue by TGuimbert** [grafana/agent#1149]
Hi, I'm trying to setup the new Kubernetes integration on Grafana Cloud with the Grafana Agent Operator. The `cluster` variable of the main dashboards use the query `label_values(up{job="integrations/kubernetes/kubelet"}, cluster)`. So in order to have the dashboard working, I need to have an `up` metric with the `integrations/kubernetes/kubelet` value on the `job` label. 

I have an`up` metric with the `job` label value `kubelet` coming from the Kubelet service monitor (I'm guessing the job label is coming from the service name). I have a `metricRelabelings` rule in the service monitor to replace the `job` metric value with `integrations/kubernetes/kubelet` and I see some metrics having this label but not the `up` one. I also tried to add the `jobLabel` field to the service monitor but it didn't seem to change anything.

<details><summary>Kubelet Service Monitor</summary>

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    instance: primary
  name: kubelet-monitor
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 60s
    metricRelabelings:
    - action: keep
      regex: kubelet_cgroup_manager_duration_seconds_count|go_goroutines|kubelet_pod_start_duration_seconds_count|kubelet_runtime_operations_total|kubelet_pleg_relist_duration_seconds_bucket|volume_manager_total_volumes|kubelet_volume_stats_capacity_bytes|container_cpu_usage_seconds_total|container_network_transmit_bytes_total|kubelet_runtime_operations_errors_total|container_network_receive_bytes_total|container_memory_swap|container_network_receive_packets_total|container_cpu_cfs_periods_total|container_cpu_cfs_throttled_periods_total|kubelet_running_pod_count|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate|container_memory_working_set_bytes|storage_operation_errors_total|kubelet_pleg_relist_duration_seconds_count|kubelet_running_pods|rest_client_request_duration_seconds_bucket|process_resident_memory_bytes|storage_operation_duration_seconds_count|kubelet_running_containers|kubelet_runtime_operations_duration_seconds_bucket|kubelet_node_config_error|kubelet_cgroup_manager_duration_seconds_bucket|kubelet_running_container_count|kubelet_volume_stats_available_bytes|kubelet_volume_stats_inodes|container_memory_rss|kubelet_pod_worker_duration_seconds_count|kubelet_node_name|kubelet_pleg_relist_interval_seconds_bucket|container_network_receive_packets_dropped_total|kubelet_pod_worker_duration_seconds_bucket|container_start_time_seconds|container_network_transmit_packets_dropped_total|process_cpu_seconds_total|storage_operation_duration_seconds_bucket|container_memory_cache|container_network_transmit_packets_total|kubelet_volume_stats_inodes_used|up|rest_client_requests_total
      sourceLabels:
      - __name__
    - action: replace
      targetLabel: job
      replacement: integrations/kubernetes/kubelet
    port: https-metrics
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: integrations/kubernetes/kubelet
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
```

</details>

Am I doing something wrong or is this some kind of bug ?

Thanks for your help.

**Comment by pvlltvk** [comment]
Having the same issue. I used this doc - https://grafana.com/docs/agent/latest/operator/custom-resource-quickstart/

**Comment by pvlltvk** [comment]
Yeah, I can confirm that adding `relabeling` in addition to `metricRelabeling` fix this issue:
```
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    - action: replace
      targetLabel: job
      replacement: integrations/kubernetes/kubelet
```
