### ISSUE TITLE
Metrics targets set by file_sd_configs config does not work

### ISSUE THREAD

**Issue by JuraSebastian** [grafana/agent#1157]
`file_sd_configs` seems to have no effect. Grafana-agent starting, config gets loaded fine but no requests are made to my servers.
Using grafana agent in version: 0.21.1
Following config not working:

```yml
metrics:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 5s
    remote_write:
      - url: ${Url}/api/prom/push
        basic_auth:
          username: ${Username}
          password: ${ApiKey}
  configs:
    - name: metrics
      scrape_configs:
      - job_name: backend
#        static_configs:
#          - targets: ['123.123.123.123:1234']
        file_sd_configs:
          - files:
            - 'targets.yml'
```
```
targets.yml:
- targets:
  - 123.123.123.123:1234
```
endpoint `/agent/api/v1/targets` returns: `{"status":"success","data":[]}`

`static_configs` as in example above, when uncommented working fine and endpoint returns information of that target.
