### ISSUE TITLE
filesystem collector not running on MacOS

### ISSUE THREAD

**Issue by bboles** [grafana/agent#1226]
Looks like the filesystem collector is not being called for some reason:
```
ts=2022-01-04T19:11:12.03698Z caller=node.go:85 level=info agent=prometheus component=cluster msg="applying config"
ts=2022-01-04T19:11:12.037782Z caller=remote.go:180 level=info agent=prometheus component=cluster msg="not watching the KV, none set"
ts=2022-01-04T19:11:12Z level=info caller=traces/traces.go:123 msg="Traces Logger Initialized" component=traces
ts=2022-01-04T19:11:12.041211Z caller=node_exporter.go:49 level=info integration=node_exporter msg="Enabled node_exporter collectors"
ts=2022-01-04T19:11:12.041222Z caller=node_exporter.go:56 level=info integration=node_exporter collector=boottime
ts=2022-01-04T19:11:12.041226Z caller=node_exporter.go:56 level=info integration=node_exporter collector=cpu
ts=2022-01-04T19:11:12.041229Z caller=node_exporter.go:56 level=info integration=node_exporter collector=diskstats
ts=2022-01-04T19:11:12.041233Z caller=node_exporter.go:56 level=info integration=node_exporter collector=loadavg
ts=2022-01-04T19:11:12.041236Z caller=node_exporter.go:56 level=info integration=node_exporter collector=meminfo
ts=2022-01-04T19:11:12.041239Z caller=node_exporter.go:56 level=info integration=node_exporter collector=netdev
ts=2022-01-04T19:11:12.041242Z caller=node_exporter.go:56 level=info integration=node_exporter collector=textfile
ts=2022-01-04T19:11:12.041245Z caller=node_exporter.go:56 level=info integration=node_exporter collector=time
ts=2022-01-04T19:11:12.041249Z caller=node_exporter.go:56 level=info integration=node_exporter collector=uname
ts=2022-01-04T19:11:12.043039Z caller=wal.go:182 level=info agent=prometheus instance=022496568e9dee553555fef4d8abdbef msg="replaying WAL, this may take a while" dir=/tmp/grafana-agent-wal/022496568e9dee553555fef4d8abdbef/wal
```
This results in no filesystem metrics being exported.  No errors generated by the agent.

My config:
```
integrations:
  node_exporter:
    enabled: true
  prometheus_remote_write:
    - basic_auth:
        password: <redacted>
        username: <redacted>
      url: https://<redacted>.grafana.net/api/prom/push
loki:
  configs:
    - clients:
        - basic_auth:
            password: <redacted>
            username: <redacted>
          url: https://<redacted>.grafana.net/api/prom/push
      name: integrations
      positions:
        filename: /tmp/positions.yaml
      target_config:
        sync_period: 10s
prometheus:
  configs:
    - name: integrations
      remote_write:
        - basic_auth:
            password: <redacted>
            username: <redacted>
          url: https://<redacted>.grafana.net/api/prom/push
  global:
    scrape_interval: 60s
  wal_directory: /tmp/grafana-agent-wal
server:
  http_listen_port: 12345
```
This is on a Mac Mini M1 (5th generation) running the latest MacOS 11:
```
ProductName:    macOS
ProductVersion: 11.6.2
BuildVersion:   20G314
```
Agent info (installed from Homebrew Core):
```
$ grafana-agent --version
agent, version v0.21.2 (branch: HEAD, revision: )
  build user:       Homebrew
  build date:       2021-12-08T13:05:08Z
  go version:       go1.17.5
  platform:         darwin/arm64
```
