### ISSUE TITLE
prom_sd_pod_association panic on nil pointer dereference

### ISSUE THREAD

**Issue by james-callahan** [grafana/agent#1277]
traceback:
```
2022-01-17 00:09:06.010998 I | http: panic serving 10.24.141.26:59784: runtime error: invalid memory address or nil pointer dereference
goroutine 65083 [running]:
net/http.(*conn).serve.func1(0xc00622b360)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x3bc4e80, 0x688fc90)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/grafana/agent/pkg/traces/promsdprocessor.getConnectionIP(0x4c57170, 0xc004550780, 0x43436af, 0x9)
	/src/agent/pkg/traces/promsdprocessor/prom_sd_processor.go:122 +0x6c
github.com/grafana/agent/pkg/traces/promsdprocessor.(*promServiceDiscoProcessor).getPodIP(0xc000122b80, 0x4c57170, 0xc004550780, 0xc004039a40, 0xc0040984f8, 0x0)
	/src/agent/pkg/traces/promsdprocessor/prom_sd_processor.go:139 +0x205
github.com/grafana/agent/pkg/traces/promsdprocessor.(*promServiceDiscoProcessor).processAttributes(0xc000122b80, 0x4c57170, 0xc004550780, 0xc004039a40)
	/src/agent/pkg/traces/promsdprocessor/prom_sd_processor.go:149 +0x7a
github.com/grafana/agent/pkg/traces/promsdprocessor.(*promServiceDiscoProcessor).ConsumeTraces(0xc000122b80, 0x4c57170, 0xc004550780, 0xc00301d800, 0xc004039a40, 0xc004039a90)
	/src/agent/pkg/traces/promsdprocessor/prom_sd_processor.go:106 +0x5f
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver.consumeTraces(0x4c57170, 0xc004550780, 0xc004550810, 0x4c17710, 0xc000804ca8, 0x4c57170, 0xc004550780, 0x0)
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver@v0.40.0/trace_receiver.go:232 +0x74
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver.(*jReceiver).HandleThriftHTTPBatch(0xc0001a8780, 0x4c47990, 0xc0042aa960, 0xc002c49f00)
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver@v0.40.0/trace_receiver.go:431 +0xfa
net/http.HandlerFunc.ServeHTTP(0xc0007af440, 0x4c47990, 0xc0042aa960, 0xc002c49f00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00089f080, 0x4c47990, 0xc0042aa960, 0xc002c49700)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
go.opentelemetry.io/collector/external/middleware.(*decompressor).wrap.func1(0x4c47990, 0xc0042aa960, 0xc002c49700)
	/go/pkg/mod/github.com/grafana/opentelemetry-collector@v0.4.1-0.20211201123047-86905635e8f8/external/middleware/compression.go:127 +0xcf
net/http.HandlerFunc.ServeHTTP(0xc000119ee0, 0x4c47990, 0xc0042aa960, 0xc002c49700)
	/usr/local/go/src/net/http/server.go:2069 +0x44
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP(0xc00025b5e0, 0x4c46040, 0xc0042aa960, 0xc002c49200)
	/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.27.0/handler.go:189 +0x977
net/http.serverHandler.ServeHTTP(0xc000a162a0, 0x4c46040, 0xc003f4cfc0, 0xc002c49200)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc00622b360, 0x4c57170, 0xc005d55c00)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

<details><summary>Config file:</summary>

```yaml
server:
  http_listen_port: 8080
  log_level: info
traces:
  configs:
    - batch:
        send_batch_size: 1000
        timeout: 5s
      name: default
      receivers:
        jaeger:
          protocols:
            grpc: null
            thrift_binary: null
            thrift_compact: null
            thrift_http: null
          remote_sampling:
            strategy_file: /etc/agent/strategies.json
            tls:
              insecure: true
        otlp:
          protocols:
            grpc: null
            http: null
        zipkin:
          endpoint: 0.0.0.0:9411
      remote_write:
        - endpoint: tempo-distributor:4317
          insecure: true
          retry_on_failure:
            enabled: false
      # We don't trust pod process tags: only trust source IP
      prom_sd_pod_association:
        - connection
      scrape_configs:
        # Pods with a label 'app.kubernetes.io/name'
        - job_name: kubernetes-pods-app-kubernetes-io-name
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
              target_label: app
            - action: drop
              regex: ''
              source_labels:
                - app

            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_component
              target_label: component
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_node_name
              target_label: nodename
            - action: replace
              replacement: $1
              separator: /
              source_labels:
                - namespace
                - app
              target_label: job

        # Pods with a label 'app'
        - job_name: kubernetes-pods-app
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            # Drop pods with label 'app.kubernetes.io/name'. They are already considered above
            - action: drop
              regex: .+
              source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_label_app
              target_label: app
            - action: drop
              regex: ''
              source_labels:
                - app

            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_component
              target_label: component
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_node_name
              target_label: nodename
            - action: replace
              replacement: $1
              separator: /
              source_labels:
                - namespace
                - app
              target_label: job

        # Pods with direct controllers, such as StatefulSet
        - job_name: kubernetes-pods-direct-controllers
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            # Drop pods with label 'app.kubernetes.io/name' or 'app'. They are already considered above
            - action: drop
              regex: .+
              separator: ''
              source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
                - __meta_kubernetes_pod_label_app
            # Drop pods that have no controller
            - action: drop
              regex: ''
              source_labels:
                - __meta_kubernetes_pod_controller_name
            # Drop pods that have an indirect controller
            - action: drop
              regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
              source_labels:
                - __meta_kubernetes_pod_controller_name
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_controller_name
              target_label: app

            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_component
              target_label: component
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_node_name
              target_label: nodename
            - action: replace
              replacement: $1
              separator: /
              source_labels:
                - namespace
                - app
              target_label: job

        # Pods with indirect controllers, such as Deployment
        - job_name: kubernetes-pods-indirect-controller
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            # Drop pods with label 'app.kubernetes.io/name' or 'app'. They are already considered above
            - action: drop
              regex: .+
              separator: ''
              source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
                - __meta_kubernetes_pod_label_app
            - action: keep
              regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
              source_labels:
                - __meta_kubernetes_pod_controller_name
            - action: replace
              regex: '([0-9a-z-.]+)-[0-9a-f]{8,10}'
              source_labels:
                - __meta_kubernetes_pod_controller_name
              target_label: app

            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_component
              target_label: component
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_node_name
              target_label: nodename
            - action: replace
              replacement: $1
              separator: /
              source_labels:
                - namespace
                - app
              target_label: job

        # All remaining pods not yet covered
        - job_name: kubernetes-other
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            # Drop what has already been covered
            - action: drop
              regex: .+
              separator: ''
              source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
                - __meta_kubernetes_pod_label_app
                - __meta_kubernetes_pod_controller_name
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: app

            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_component
              target_label: component
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_node_name
              target_label: nodename
            - action: replace
              replacement: $1
              separator: /
              source_labels:
                - namespace
                - app
              target_label: job
```

</details>
