### ISSUE TITLE
Allow specifying the name of a job in a {Service,…}Monitor

### ISSUE THREAD

**Issue by flokli** [grafana/agent#1280]
I'm using grafana-agent-operator, and have it manage the `default/kubelet` service.

I created a `ServiceMonitor` to scrape metrics from there:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kubelet
  name: kubelet
  namespace: default
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    port: https-metrics
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    path: /metrics/cadvisor
    port: https-metrics
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    path: /metrics/probes
    port: https-metrics
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    path: /metrics/resource
    port: https-metrics
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
      k8s-app: kubelet
```

This runs a in a k3s cluster, which (also) exposes `kube-scheduler` and `apiserver` metrics on the `/metrics` `https-metrics` endpoint.

Many prometheus dashboards and PrometheusRules rely on the `job=kube-scheduler`/`job=apiserver` fields (and the separate `up` metric).

That's why I created two additional `ServiceMonitor` resources to collect these other metrics in additional jobs (only keeping the ones starting with `scheduler_` or `apiserver_`). In the case of `kube-scheduler`, it looks like this:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kubelet
  name: kube-scheduler
  namespace: default
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    port: https-metrics
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    - action: keep
      regex: scheduler_.+
      sourceLabels:
      - __name__
    - replacement: kube-scheduler
      targetLabel: job
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
      k8s-app: kubelet
```

However, it seems it's not possible to influence the name of the job, even with the above relabelConfig - ~in my case, it still picks "kubelet".~

**Comment by flokli** [comment]
I checked the generated `/var/lib/grafana-agent/config.agent.yaml` in the pod. While it lists the config:

```yaml
#[…]
            - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              honor_labels: true
              job_name: serviceMonitor/default/kube-scheduler/0
              kubernetes_sd_configs:
                - namespaces:
                    names:
                        - default
                  role: endpoints
              relabel_configs:
                - source_labels:
                    - job
                  target_label: __tmp_prometheus_job_name
                - action: keep
                  regex: kubelet
                  source_labels:
                    - __meta_kubernetes_service_label_app_kubernetes_io_name
                - action: keep
                  regex: kubelet
                  source_labels:
                    - __meta_kubernetes_service_label_k8s_app
                - action: keep
                  regex: https-metrics
                  source_labels:
                    - __meta_kubernetes_endpoint_port_name
                - regex: Node;(.*)
                  replacement: $1
                  separator: ;
                  source_labels:
                    - __meta_kubernetes_endpoint_address_target_kind
                    - __meta_kubernetes_endpoint_address_target_name
                  target_label: node
                - regex: Pod;(.*)
                  replacement: $1
                  separator: ;
                  source_labels:
                    - __meta_kubernetes_endpoint_address_target_kind
                    - __meta_kubernetes_endpoint_address_target_name
                  target_label: pod
                - source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - source_labels:
                    - __meta_kubernetes_service_name
                  target_label: service
                - source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                - source_labels:
                    - __meta_kubernetes_pod_container_name
                  target_label: container
                - replacement: $1
                  source_labels:
                    - __meta_kubernetes_service_name
                  target_label: job
                - replacement: https-metrics
                  target_label: endpoint
                - source_labels:
                    - __metrics_path__
                  target_label: metrics_path
                - action: keep
                  regex: scheduler_.+
                - replacement: kube-scheduler
                  source_labels:
                    - __meta_kubernetes_service_name
                  target_label: job
                - action: hashmod
                  modulus: 1
                  source_labels:
                    - __address__
                  target_label: __tmp_hash
                - action: keep
                  regex: 0
                  source_labels:
                    - __tmp_hash
              scheme: https
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true
#[…]
```

This doesn't show up in the targets that grafana-agent then knows about: 

```
❯ curl http://localhost:8080/agent/api/v1/targets | jq | grep serviceMonitor/default/kube-scheduler/0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  136k    0  136k    0     0   215k      0 --:--:-- --:--:-- --:--:--  215k
```

**Comment by rfratto** [comment]
🤔 Hmm, it's weird that it's not showing up in the targets list. The scrape configs seem the same. Is the other service monitor showing up? i.e., `serviceMonitor/default/kubelet/X`? 

Silly question: how long did you wait after making the latest change? I've found that the config reloader we use can take a minute or two for changes to the generated config to propagate.

**Comment by flokli** [comment]
Nope, I also kicked the grafana-agent pod - no luck.

The other service monitors are showing up:

```
❯ curl http://localhost:8080/agent/api/v1/targets | jq ".data[].target_group"  | grep serviceMonitor
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  136k    0  136k    0     0   199k      0 --:--:-- --:--:-- --:--:--  199k
"serviceMonitor/cert-manager/cert-manager/0"
"serviceMonitor/default/kubelet/0"
"serviceMonitor/default/kubelet/0"
"serviceMonitor/default/kubelet/0"
"serviceMonitor/default/kubelet/0"
"serviceMonitor/default/kubelet/0"
"serviceMonitor/default/kubelet/0"
"serviceMonitor/default/kubelet/1"
"serviceMonitor/default/kubelet/1"
"serviceMonitor/default/kubelet/1"
"serviceMonitor/default/kubelet/1"
"serviceMonitor/default/kubelet/1"
"serviceMonitor/default/kubelet/1"
"serviceMonitor/default/kubelet/2"
"serviceMonitor/default/kubelet/2"
"serviceMonitor/default/kubelet/2"
"serviceMonitor/default/kubelet/2"
"serviceMonitor/default/kubelet/2"
"serviceMonitor/default/kubelet/2"
"serviceMonitor/default/kubelet/3"
"serviceMonitor/default/kubelet/3"
"serviceMonitor/default/kubelet/3"
"serviceMonitor/default/kubelet/3"
"serviceMonitor/default/kubelet/3"
"serviceMonitor/default/kubelet/3"
"serviceMonitor/ingress-nginx/ingress-nginx-controller/0"
"serviceMonitor/ingress-nginx/ingress-nginx-controller/0"
"serviceMonitor/ingress-nginx/ingress-nginx-controller/0"
"serviceMonitor/ingress-nginx/ingress-nginx-controller/0"
"serviceMonitor/ingress-nginx/ingress-nginx-controller/0"
"serviceMonitor/kube-system/coredns/0"
"serviceMonitor/kube-system/kube-state-metrics/0"
"serviceMonitor/node-exporter/node-exporter/0"
"serviceMonitor/node-exporter/node-exporter/0"
"serviceMonitor/node-exporter/node-exporter/0"
"serviceMonitor/node-exporter/node-exporter/0"
"serviceMonitor/node-exporter/node-exporter/0"
"serviceMonitor/node-exporter/node-exporter/0"
```

**Comment by rfratto** [comment]
Hmm, that's odd. Can you upload the entire generated config?

**Comment by flokli** [comment]
Please find the generated config here: [agent.yaml.gz](https://github.com/grafana/agent/files/7889713/agent.yaml.gz)

In `scrape_configs`, I removed some lines (and censored some URLs/usernames), but it should contain the kube-scheduler/apiserver scrape configs, as well as the kubelet config:

**Comment by rfratto** [comment]
I think I found the problem: 

```yaml
action: keep
regex: scheduler_.+
```

Did you mean for this to be `metricRelabelings`? Unless there's a label called `scheduler_*` it will drop the target.

```yaml
metricRelabelings:
- source_labels: [__name__] 
  regex: scheduler_.+ 
  action: keep
```
