### ISSUE TITLE
[dev.frontend-receiver] add sourcemap support

### ISSUE THREAD

**Issue by domasx2** [grafana/agent#1295]
Add opt-in sourcemap support where receiver is able to use sourcemaps to transform exception stacktrace frames from compiled locations to original source locations. 

Several modes should be supported to retrieve sourcemaps:
1. Download compiled source, read source map url comment, download source map, cache 
2. Download compiled source, read inline sourcemap, cache
3. Configure sourcemap folder location on file system. Per http origin + release

For example:

```yaml
sourcemaps:
  download: false # if true and sourcemap not found on fs, attempt to download
  filesystem:
     - origins: "https://fooapp.1.cdn.com,https://fooap.2.cdn.com" # or just "*" for any origin
       folder: "/etc/fooapp/${release}/"
```

Then if location is  "https://fooapp.1.cdn.com/public/js/main.js" and `app.release` provided in payload is `abcd`, will attempt to find sourcemap at `/etc/fooapp/abcd/public/js/main.js.map`
