### ISSUE TITLE
Proposal: HTTP Service Discovery Aggregator

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1320]
## Background

RFC #1224, which proposes adding [integrations into the operator][], mentions the need to aggregate over multiple HTTP SD API endpoints:

> The operator's existing HTTP server will be extended with a new endpoint which aggregates the integrations targets for all managed integrations pods. This endpoint will be available at /operator/api/v1/metrics/integrations/sd. For this endpoint to work, the Operator will create a new controller that watches for changes to Endpoints related to the integrations-specific Services created by the operator. The list of relevant pod IPs will then be maintained internally.

After some thought, it's clear that this problem isn't specific to the operator, and the need for an aggregator will continually come up when integrations are being collected centrally. For example, if a user was deploying Grafana Agents with integrations on VMs, they would need to take one of three approaches:

* Use a static set of targets and update it when the environment changes 
* Write a custom API to aggregate targets, like the initial proposal for the operator 
* Integrate with another SD mechanism like Consul to expose the flattened list of targets  

All of these paths require extra effort from the user that arguably shouldn't be necessary: one of the main goals of Grafana Agent is that you don't need to deploy extra infrastructure to collect telemetry. 

The concept of a discovered Prometheus target exposing multiple other targets is newly identified, and it's likely to need a few iteration cycles while we experiment with what's possible. This proposal suggests one such first step: use Prometheus SD to discover and aggregate over multiple http_sd endpoints across a dynamic environment. 

## Goals 

* Allow retrieving a combined set of targets across a dynamic set of http_sd endpoints. 
* Minimize the blast radius by adding this functionality into a cordoned off section of the codebase while we iterate, learn, and improve. 

## Proposal 

A new `http-sd` command will be added to `agentctl`. This will launch an HTTP server with an [http_sd][]-compatible API at `/targets`. `/targets`  is generated from an aggregate of multiple other http_sd-compatible APIs. 

The `http-sd` command is configured with a YAML file with the following schema:

```yaml
# HTTP resource path on which to fetch http_sd targets. 
[ api_path: <path> | default = /targets ] 

# Refresh interval to re-query individual endpoints.
[ refresh_interval: <duration> | default = 60s ] 

# How long before a refresh times out. 
[ refresh_timeout: <duration> | default = 10s ] 

# Configures the protocol scheme to use for requests. 
[ scheme: <scheme> | default = http ]

# Omitted for brevity: 
# 
# HTTP configuration:
#     scheme, params, basic_auth, authorization, oauth2, 
#     follow_redirects, proxy_url 
#
# Prometheus SD:
#     kubernetes_sd_configs, static_configs, 
#     consul_sd_configs, et al.

# Control how conflicts are handled between labels present from 
# the http_sd target and the targets it exposes. If true, 
# the labels from the aggregator are ignored in favor of the 
# labels from http_sd endpoint. If false, conflicting labels from 
# the http_sd endpoint will be prefixed with "exported_". 
[ honor_labels: <boolean> | default = false ]   

# Relabel discovered http_sd endpoints 
relabel_configs:
[ - <relabel_configs> ... ] 

# Relabel individual targets from http_sd endpoints 
target_relabel_configs:
[ - <relabel_configs> ... ] 
```

http_sd endpoints will be discovered from the set of configured SD mechanisms. These endpoints can use the following meta labels to influence the behavior of the aggregator: 

* `__address__` to specify what `<host>:<port>` to make the http_sd request against.
* `__api_path__` to override the API path to use for retrieving http_sd targets.
* `__scheme__` to override the scheme to use for retrieving http_sd targets. 

Labels that do not start with `__` will be appended to the targets discovered from the individual endpoints. Conflicting labels between the endpoint and discovered targets will be resolved based on the value of `honor_labels`. 

Discovered endpoints will be polled every `refresh_interval` seconds. The `/targets` endpoint of the aggregator will return the current targets from across all the discovered endpoints from the most recent refresh of each.

### Multiple Jobs 

This proposal omits an equivalent of having multiple configs in the style of the `scrape_configs` array. It's not immediately clear whether one might need more than one config for a tool like this. 

### Long Polling 

Today, `http_sd` polls for updates every 30 seconds by default. This can be increased or decreased as needed to change the resolution of changes. However, it may be worth exploring adding a [Consul-inspired long polling][long-polling] to http_sd, where `X-Prometheus-HTTP-SD-Index`  may optionally be returned by http_sd APIs and used for blocking calls which return either after the timeout or whenever a new target set is generated.   

### Graduating out of agentctl

This proposal suggests limiting the scope as much as possible by adding this new functionality specifically to agentctl. In the future, we may wish to do one or more of the following:

* Turn the http_sd aggregator into an integration 
* Turn the http_sd aggregator into its own "real" SD mechanism (to be used in scrape_configs).  

## Alternatives Considered 

#1308 is part of an effort to explore dynamic configuration. With #1308, one could use templates based on an environment that generates a list of `http_sd_configs` from an environment, very similarly to this solution. There are a few small differences:

1. Dynamic configuration would have a harder time being able to benefit from any kind of long polling
2. Dynamic configuration would also have a harder time attaching extra metadata in the same way that `relabel_configs` can. 
 
I believe we should explore both of these solutions in parallel, and it's possible that both may be useful in their own way. 

[integrations into the operator]: https://github.com/grafana/agent/pull/1224
[http_sd]: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#http_sd_config
[long-polling]: https://www.consul.io/api/features/blocking
