### ISSUE TITLE
Grafana Agent Binary - Configuration question

### ISSUE THREAD

**Issue by darkwizard242** [grafana/agent#133]
Hi,

So I have a general question since I have not played around with Grafana Cloud before and was attempting to hook up an agent binary along to my Grafana Cloud Instance (free version). The [blog](https://grafana.com/blog/2020/07/02/getting-started-with-the-grafana-cloud-agent-a-remote_write-focused-prometheus-agent/) here does state for when we are not using a Grafana Cloud instance, but what parameters are required if you want to use have the metrics be pushed to Grafana Cloud... For instance my configuration was the following:

```yaml
server:
  log_level: info
  http_listen_port: 12345
prometheus:
  wal_directory: /tmp/wal
  global:
    scrape_interval: 15s
integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true

  prometheus_remote_write:
   - url: https://<grafana-cloud-instance-name>.grafana.net/api/prom/push
     basic_auth:
       username: <grafana-cloud-user-here>
       password: <password-here>
```

and the error I got was:

```shell
ts=2020-07-10T00:30:55.332480205Z caller=dedupe.go:112 agent=prometheus instance=integration/node_exporter component=remote level=error remote_name=integration/node_exporter-243165 url=https://<grafana-cloud-instance-name>.grafana.net/api/prom/push msg="non-recoverable error while sending metadata" count=248 err="server returned HTTP status 401 Unauthorized: {\"message\":\"Invalid username or password\"}"
```

While I do see the cause is user and password, but just want to make sure what the correct method to pass them was.
