### ISSUE TITLE
grafana-agent-operator segfaults on missing secret key

### ISSUE THREAD

**Issue by thmzlt** [grafana/agent#1448]
(Installed grafana-agent-operator using the Helm chart at version 0.1.5)

The grafana-agent-operator pod segfaults when adding a `MetricInstance` or `LogsInstance` that points to a secret key for basicAuth username/password that doesn't exist.

Example:

```yaml
apiVersion: monitoring.grafana.com/v1alpha1
kind: LogsInstance
metadata:
  name: grafana-agent
  namespace: grafana-agent
  labels:
    agent: grafana-agent-logs
spec:
  clients:
    - url: https://my-loki-instance
      basicAuth:
        username:
          name: basic-auth-secret
          key: THIS_KEY_DOESNT_EXIST
        password:
          name: basic-auth-secret
          key: THIS_KEY_DOESNT_EXIST
  podLogsNamespaceSelector: {}
  podLogsSelector:
    matchLabels: {}
```
