### ISSUE TITLE
integrations-next: integrations stop working after /-/reload

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1455]
integrations-next integrations will stop working if the /-/reload endpoint is invoked after changing an integration's config. 

To reproduce: 

1. Run the Agent with `-enable-features=integrations-next` and the following agent configuration:

```yaml
server:
  http_listen_port: 12345

integrations:
  metrics:
    autoscrape:
      enable: false 

  agent: 
    extra_labels: 
      foo: bar
```

2. Change `foo: bar` to `foo: example`

3. Run `curl localhost:12345/-/reload` 

4. Run `curl localhost:12345/integrations/agent/metrics` 

Expected behavior: metrics for the agent should be returned
 
Actual behavior: An 503 Service Unavailable error is returned
