### ISSUE TITLE
Version upgrade via Helm does not work, due to changing labels in Deployment's selector

### ISSUE THREAD

**Issue by alex-berger** [grafana/agent#1462]
Upgrading a grafana-agent-operator Helm release, does not work as the Deployment's label selector (`spec.selector.matchLabels`) contains labels whose values change with each release. As [clearly documented](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#label-selector-updates) the label selector of a Deployment is immutable and thus must not contain any version information.

> In API version apps/v1, a Deployment's label selector is immutable after it gets created.

# Observed 

Currently the Deployment generated by the HelmChart looks like the one below. Note the `app.kubernetes.io/version` and ` helm.sh/chart` labels used in `spec.selector.matchLabels`, which both contain values that might change with each release.

```yaml
apiVersion: apps/v1
kind: Deployment
...
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: grafana-agent-system-grafana-agent-operator
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana-agent-operator
      app.kubernetes.io/version: 0.22.0
      helm.sh/chart: grafana-agent-operator-0.1.5
```

# Expected

The Deployment's `spec.selector.matchLabels` should be carefully redesigned to only contain a minimal set of labels, which all do not change between releases. For example something like this should work:

```yaml
apiVersion: apps/v1
kind: Deployment
...
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: grafana-agent-system-grafana-agent-operator
      app.kubernetes.io/name: grafana-agent-operator
```

# Workaround

With the above `spec.selector.matchLabels` we first have to manually delete the Deployment before we can apply a Helm upgrade. This is annoying as it makes fully automated GitOps (e.g. using FluxCD) impossible.
