### ISSUE TITLE
grafana-agent-operator secrets issue with logs daemonset

### ISSUE THREAD

**Issue by jimgus** [grafana/agent#1523]
Grafana Agent Operator deployed with Helm 0.1.6

My intention is to set up Grafana Agent for logging. When adding a secret to the Grafana Agent resource, the logs DS is not created and I can see the following in the operator log:

```
level=error ts=2022-03-22T09:38:18.325686665Z component=controller.grafanaagent name=grafana-agent-platform namespace=grafana-agent msg="error during reconciling" err="failed to reconcile statefulset governing service: failed to create daemonset: DaemonSet.apps \"grafana-agent-platform-logs\" is invalid: [spec.template.spec.containers[0].volumeMounts[6].mountPath: Invalid value: \"/var/lib/grafana-agent/secrets\": must be unique, spec.template.spec.containers[1].volumeMounts[6].mountPath: Invalid value: \"/var/lib/grafana-agent/secrets\": must be unique]"
```
The agent config looks like this (I have LogsInstance configured as well):
```
apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: grafana-agent-platform
  namespace: grafana-agent
  labels:
    app: grafana-agent-platform
spec:
  image: grafana/agent:v0.21.2
  logLevel: info
  serviceAccountName: grafana-agent
  priorityClassName: platform-medium
  logs:
    instanceSelector:
      matchLabels:
        agent: grafana-agent-platform-logs
  tolerations:
    - operator: "Exists"
  secrets:
    - xenit-proxy-certificate
```
When removing the `secrets`part, the DS is up and running.

When checking the code I can see that  the above mount path (`/var/lib/grafana-agent/secrets`) is used twice:
https://github.com/grafana/agent/blob/9f811f20a7366641c2cf86cd379cdd36924672c0/pkg/operator/resources_logs.go#L173
https://github.com/grafana/agent/blob/9f811f20a7366641c2cf86cd379cdd36924672c0/pkg/operator/resources_logs.go#L198

I'm wondering if this can be a problem?
