### ISSUE TITLE
eventhandler: Add extra identifying labels into integration config

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1549]
By default, the eventhandler integration doesn't generate any labels outside of `namespace`. While the documentation recommends settings `external_labels`, this only works if nothing else is sending logs to that Loki instance. 

The following labels should be added by default to align with labels added by other integrations:

* `job=integrations/eventhandler`
* `instance=<result of eventhandler.Config.Identifier()>` 
* `agent_hostname=<agent identifier from globals>` 

Additionally, there should be an `extra_labels` field to add additional labels on top of these, matching the behavior of metrics-based v2 integrations:

```
integrations:
  eventhandler:
    extra_labels: 
      foo: bar     # adds a foo="bar" label
```

cc @hjet
