### ISSUE TITLE
Logs timezone stage doesn't work well on Windows

### ISSUE THREAD

**Issue by splitt3r** [grafana/agent#1571]
The problem described in https://github.com/grafana/loki/issues/1361 seems to still exist in the Grafana Agent. I'm using the following configuration to gather logs from a Windows server. It works in a pure promtail installation but does not with the Grafana Agent.

```
...
logs:
  positions_directory: C:\ProgramData\grafana-agent-positions
  configs:
    - name: default
      clients:
        - url: http://...:3100/loki/api/v1/push
      scrape_configs:
        - job_name: application-logs
          pipeline_stages:
            # Configure multi line entries like exceptions. Everything that does not start with a date is appended to the previous line.
            - multiline:
                firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}\ '
            # Regular expression to parse a general log line
            - regex:
                expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) \[(?P<thread>\S+)\] (?P<level>\S+)(\s+)(?P<logger>\S+) - (?s)(?P<message>.*)$'
            # Go only knows the time format with a . instead of a ,
            - template:
                source: timestamp
                template: '{{ Replace .Value "," "." 1 }}'
            # Parse the timestamp
            - timestamp:
                source: timestamp
                # Read more about the date example here: https://programming.guide/go/format-parse-string-time-date-example.html
                format: 2006-01-02 15:04:05.000
                # location: Europe/Berlin
          static_configs:
            - targets:
              - localhost
              labels:
                job: application
                __path__: C:\logs\*.log
...
```

The `location: Europe/Berlin` leads to the error given in the linked issue.
