### ISSUE TITLE
kubernetes_sd_configs.selectors.label doesn't work

### ISSUE THREAD

**Issue by renannprado** [grafana/agent#1573]
We would like to prevent that our metrics coming from [cloudwatch exporter](https://github.com/nerdswords/yet-another-cloudwatch-exporter) get labels like `pod`, `node`, etc.

To do that, we thought of using the selector in the `kubernetes_sd_configs` so that it doesn't scrape metrics coming from this specific application, and then we would have another `job` that does it.

However we're failing to ensure that `kubernetes_sd_configs` won't scrape that specific application.

We tried the configuration below, but doesn't seem to change anything.

We're using the agent in the latest version `v0.23.0`.

```yaml
scrape_configs:
  - job_name: kubernetes-pod-metrics
    # Only filter for the Pods in the host
    kubernetes_sd_configs:
      - role: pod
        selectors:
          - role: pod
            label: application notin (cloudwatch-exporter)
```
