### ISSUE TITLE
GitHub integration doesn't list all releases

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1588]
To reproduce, run the Agent with at least the command line arguments `-enable-features=integrations-next -config.expand-env -config.enable-read-api` and this config:

```yaml
metrics:
  configs:
  - name: default

integrations:
  metrics:
    autoscrape:
      enable: true
      metrics_instance: default
  github_configs:
  - repositories:
    - grafana/agent
```

curl `http://localhost:12345/integrations/github/metrics`

Scan the list of `release` labels for the `github_repo_release_downloads` metric, and observe that only a small number of releases are listed.
