### ISSUE TITLE
Grafana agent can't recognize the blackbox configuration

### ISSUE THREAD

**Issue by SiminMu** [grafana/agent#1593]
Hi,

I am using the latest version of Grafana agent to scrape the metrics of blackbox exporter, here is the configuration file I am using:
```
server:
  grpc_listen_address: 127.0.0.1
  grpc_listen_port: 0 # the agent will automatically select an unused port
  http_listen_address: 127.0.0.1
  http_listen_port: 10005
  http_server_idle_timeout: 30s
  http_server_read_timeout: 5s
  log_level: debug

metrics:
  global:
    scrape_interval: 15s
    scrape_timeout: 10s
    external_labels:
      datacenter: ss
      env: ddev
      hostalias: 11111
      service: cosoo
    remote_write:
      - url: "https://collector-cortex/api/prom/push"
        bearer_token_file: "/tmp/agent/metrics-write.key"
        queue_config:
          capacity: 2500
          max_shards: 100
          min_shards: 1
          max_samples_per_send: 500
          batch_send_deadline: 5s
          min_backoff: 1s
          max_backoff: 1m
  wal_directory: "/tmp/agent/wal"
  wal_cleanup_age: 12h
  wal_cleanup_period: 30m

  # If an instance crashes abnormally, how long should we wait before trying
  # to restart it. 0s disables the backoff period and restarts the agent
  # immediately.
  instance_restart_backoff: 5s

  configs:
    - name: default
      host_filter: true
      wal_truncate_frequency: 30m
      min_wal_time: 5m
      max_wal_time: 2h

      scrape_configs:
        - job_name: 'blackbox'
          metrics_path: /probe
          params:
            module: [http_2xx]  # Look for a HTTP 200 response.
          static_configs:
            - targets:
              - "http://prometheus.io"
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: 127.0.0.1:10003  # The blackbox exporter's real hostname:port.
```

Then I run Grafana agent only with the config file:
```
agent -config.file=config.yaml
```

Normally I should be able to see some logs like the bellow, but this time I don't see this kind of logs(I also check the remote storage but no metric appeared there). So I think that maybe grafana agent can't recognize the blackbox job and just ignore it?
```
GET /metrics (200) 5.451935ms
```
