### ISSUE TITLE
Memory usage for the grafana-agent log shipper

### ISSUE THREAD

**Issue by kovaxur** [grafana/agent#1602]
Hi,
I'm currently using the grafana-agent operator on Kubernetes with Loki as backend. The grafana-agent's log collector is running as a daemonset on every node and collecting logs from the pods.

I had to set up a memory limit, as the log collector seems to eat all the memory on the Kubernetes nodes and I would like to figure out what could be the possible problem, but I haven't seen any similar issue so far. Please help what direction should I go.

Currently set memory limit: 512MB, the container is killed when it reaches it, CPU utilization seems to be fine:
![image](https://user-images.githubusercontent.com/9846259/163118396-f073f244-2b14-431f-a974-bedef1d381f4.png)

Number of entries sent at that time, I don't think that it would be too much:
![image](https://user-images.githubusercontent.com/9846259/163118908-fdbf340e-2593-494f-86ec-71ea672c6af8.png)

Thanks

**Comment by rfratto** [comment]
Hi! Would you be able to collect a memory profile from /debug/pprof/heap and upload it for us to investigate?

**Comment by kovaxur** [comment]
[grafana-agent-logs-logs-mrtw8.zip](https://github.com/grafana/agent/files/8487615/grafana-agent-logs-logs-mrtw8.zip)

Hi,
Added one from an instance which is having around 350MB memory usage.

Thanks

**Comment by kovaxur** [comment]
I'm not sure, if we are not misusing some features, the scenario for us is the following:

- we use the grafana-agent operator to look for PodLogs CRD objects
- or each service we generate a PodLogs object, each contains something similar like:

Pipeline stages:
```
              pipeline_stages:
                - docker: {}
                - json:
                    expressions:
                        level: level
                - labels:
                    level: level
                - labeldrop:
                    - filename
                    - cluster
                    - job
```
Relabel configs:

```
                - source_labels:
                    - job
                  target_label: __tmp_prometheus_job_name
                - action: keep
                  regex: XXXX
                  source_labels:
                    - __meta_kubernetes_pod_label_app_kubernetes_io_name
                - source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - source_labels:
                    - __meta_kubernetes_service_name
                  target_label: service
                - source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                - source_labels:
                    - __meta_kubernetes_pod_container_name
                  target_label: container
                - regex: (.+)
                  replacement: $1
                  source_labels:
                    - __meta_kubernetes_pod_label_app_kubernetes_io_name
                  target_label: app_kubernetes_io_name
                - regex: (.+)
                  replacement: $1
                  source_labels:
                    - __meta_kubernetes_pod_label_app_kubernetes_io_instance
                  target_label: app_kubernetes_io_instance
                - regex: (.+)
                  replacement: $1
                  source_labels:
                    - __meta_kubernetes_pod_label_app_kubernetes_io_component
                  target_label: app_kubernetes_io_component
                - regex: (.+)
                  replacement: $1
                  source_labels:
                    - __meta_kubernetes_pod_label_app_kubernetes_io_part_of
                  target_label: app_kubernetes_io_part_of
                - replacement: XXX/XXXX
                  target_label: job
                - replacement: /var/log/pods/*$1/*.log
                  separator: /
                  source_labels:
                    - __meta_kubernetes_pod_uid
                    - __meta_kubernetes_pod_container_name
                  target_label: __path__
```

I couldn't find best-practices for this, so maybe it would be better to define the pipelines and relabel_configs per namespace and not per services? The per-service gives us better configurability though.

Thanks
