### ISSUE TITLE
Grafana Agent v0.24.0 doesn't work with old configuration

### ISSUE THREAD

**Issue by hungran** [grafana/agent#1607]
I've used the configuration for getting log Windows system as below with `v.023.0` and it was running as expected
```yaml
server:
  http_listen_port: 12345
metrics:
  wal_directory: C:\ProgramData\grafana-agent-wal
  global:
    scrape_interval: 1m
  configs:
    - name: integrations
integrations:
  windows_exporter:
    enabled: true

logs:
  # Choose a directory to save the last read position of log files at.
  # This directory will be created if it doesn't already exist.
  positions_directory: C:\grafana-agent
  configs:
    - name: windows
      # Loki endpoint to push logs to
      clients:
        - url: https://loki.....
      scrape_configs:
        - job_name: windowslogs
          static_configs:
            - targets: [localhost]
              labels:
                app: appname
                node_name: abc
                __path__: C:\Logs\**\Mobile.log
```
When upgraded to `v0.24.0` with the same as above config the Grafana Agent was not run
Error message:
![image](https://user-images.githubusercontent.com/26101787/163187222-d3df7b69-97e0-4b16-ab8d-db61f5a28550.png)
