### ISSUE TITLE
Unclear which integration config options are no longer supported in integrations-next, vs which should be moved (and where).

### ISSUE THREAD

**Issue by rgeyer** [grafana/agent#1610]
In the [integrations-next documentation](https://github.com/grafana/agent/blob/9bdcf6930843994b92e5fd5d9dfe477773bcdc18/docs/user/configuration/integrations/integrations-next/_index.md), at the end of the document there is a list of options which are no longer supported. 

It is unclear which of these options are completely deprecated and can no longer be used (enabled?) and which ones need to be defined elsewhere (relabel_configs, metric_relabel_configs).

Specifically, I was converting an existing agent config for statsd, and had some metric relabel configs, and it was unclear where to migrate them.

Before:
```
statsd_exporter:
    metric_relabel_configs:
      - source_labels: [exported_job]
        target_label: job
        replacement: 'integrations/$1'
      - source_labels: [exported_instance]
        target_label: instance
      - regex: (exported_instance|exported_job)
        action: labeldrop
```

After:
```
statsd:
    autoscrape:
      metric_relabel_configs:
        - source_labels: [exported_job]
          target_label: job
          replacement: 'integrations/$1'
        - source_labels: [exported_instance]
          target_label: instance
        - regex: (exported_instance|exported_job)
          action: labeldrop
```
