### ISSUE TITLE
Grafana agent consuming huge amount of cpu and memory 

### ISSUE THREAD

**Issue by AsishVenakataSai** [grafana/agent#1632]
grafana agent version(v0.23.0).

Currently we are using grafana agent (daemonset) to collect traces and logs.
We are observing a very huge amount of memory being used, on certain scenarios which is reaching more than 20GB.

Which is impacting on other serivce performance inside the node and also data is lost in few cases.
![Screenshot (931)](https://user-images.githubusercontent.com/84021311/164386973-ee6d0324-ed4d-48b0-8453-3c00b9666394.png)
![Screenshot (932)](https://user-images.githubusercontent.com/84021311/164386986-63a7259e-f06e-4434-989b-ff5a50a8409d.png)
![Screenshot (933)](https://user-images.githubusercontent.com/84021311/164386995-067d82df-4008-4a7d-8b96-b2cbfa31a067.png)
![Screenshot (934)](https://user-images.githubusercontent.com/84021311/164387005-01e14e6d-4122-4174-8df3-d1c18e448b48.png)

Grafana agent config
```
server:
      http_listen_port: 8080
      log_level: info
    metrics:
      global:
        scrape_interval: 15s
        external_labels:
          cluster: xxxxxxxxxx
          region: xxxxxxxxxx
      wal_directory: /tmp/grafana-agent-wal 
    logs:
      positions_directory: /tmp/loki-positions 
      configs:
        - name: agent
          clients:
            - url: xxxxxxxxx
              tenant_id: xxxxxxxxxx
              external_labels:
                cluster: xxxxxxxxxx
                region: xxxxxxxxxx
          scrape_configs:
            - job_name: kubernetes-pods-app
              kubernetes_sd_configs:
                - role: pod
              pipeline_stages:
                - docker: {}
              relabel_configs:
                - action: drop
                  source_labels:
                    - __meta_kubernetes_pod_container_name
                  regex: 'istio-proxy'
                - action: drop
                  regex: .+
                  source_labels:
                    - __meta_kubernetes_pod_label_app_kubernetes_io_name
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_label_app
                  target_label: app
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_label_component
                  target_label: component
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_node_name
                  target_label: node
                - action: drop
                  regex: ''
                  source_labels:
                    - __meta_kubernetes_pod_label_app
                - action: drop
                  regex: ''
                  source_labels:
                    - __meta_kubernetes_pod_label_app
                - action: replace
                  source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  replacement: $1
                  separator: /
                  source_labels:
                    - namespace
                    - app
                  target_label: job
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_container_name
                  target_label: container
                - action: replace
                  replacement: /var/log/pods/*$1/*.log
                  separator: /
                  source_labels:
                    - __meta_kubernetes_pod_uid
                    - __meta_kubernetes_pod_container_name
                  target_label: __path__
            - job_name: kubernetes-pods-istio-proxy
              kubernetes_sd_configs:
                  - role: pod
              pipeline_stages:
                - cri: {}
                - docker: {}
                - json:
                    expressions:
                      path: path
                      duration: duration
                      bytes_received: bytes_received
                      bytes_sent: bytes_sent
                      method: method
                      response_code: response_code
                      user_agent: user_agent
                      upstream_service_time: upstream_service_time
              relabel_configs:
                - action: keep
                  source_labels:
                    - __meta_kubernetes_pod_container_name
                  regex: 'istio-proxy'
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_label_app
                  target_label: app
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_label_component
                  target_label: component
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_node_name
                  target_label: node
                - action: replace
                  source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  replacement: $1
                  separator: /
                  source_labels:
                    - namespace
                    - app
                  target_label: job
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_container_name
                  target_label: container
                - action: replace
                  replacement: /var/log/pods/*$1/*.log
                  separator: /
                  source_labels:
                    - __meta_kubernetes_pod_uid
                    - __meta_kubernetes_pod_container_name
                  target_label: __path__           
    traces:
      configs:
        - name: default
          receivers:
            jaeger:
              protocols:
                grpc: null
                thrift_binary: null
                thrift_compact: null
                thrift_http: null
            zipkin: null
            otlp:
              protocols:
                grpc:
                http:
          attributes:
            actions:
              - action: upsert
                key: cluster
                value: xxxxxxxxxxxx
              - action: upsert
                key: region
                value: xxxxxxxxxxxx
              - action: delete
                key: thread.id
              - action: delete
                key: thread.name
          remote_write:
            - endpoint: xxxxxxxxxxx
              insecure: false
              headers:
                x-scope-orgid: xxxxxxxxxxxx
          batch:
            timeout: 5s
            send_batch_size: 1000
          scrape_configs:
            - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - action: replace
                  source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_container_name
                  target_label: container
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: false
          automatic_logging:
            roots: true
            backend: stdout
    integrations:
      agent:
        enabled: true
      node_exporter:
        enabled: true
      prometheus_remote_write:
        - url: xxxxxxxx
          headers:
            x-scope-orgid: xxxxxxx

```
