### ISSUE TITLE
Grafana agent http proxy not fully supported

### ISSUE THREAD

**Issue by martin-jaeger-maersk** [grafana/agent#1702]
Hi all,
First time contributor here.

We are in need of the grafana-agent supporting being run behind a HTTP_PROXY.
It is somewhat supported today but not fully.

I have done testing on metrics, traces and logs (with `oauth2`authentication), and here is what i found.
| Stream  | Data               | Oauth2 | Comment                                                                                                |
|---------|--------------------|--------|--------------------------------------------------------------------------------------------------------|
| logs    | :white_check_mark: | :x:    | oauth2 works with `v0.33.0` of  `prometheus/common` |
| metrics | :white_check_mark: | :x:    | oauth2 works with `v0.33.0` of  `prometheus/common` |
| traces  | :white_check_mark: | :white_check_mark: | Config file does not support `proxy_url`, but does pickup ENV `HTTP_PROXY/HTTPS_PROXY` when set                 |

Getting logs and metrics to work is _easy_, as it simply involves upgrading of a pkg.

Upgrading to `v0.33.0` of  `prometheus/common`, allows to specify `proxy_url` on `oauth2`: (both for logs and metrics)
(verified that it works)

```
metrics:
  wal_directory: /tmp/grafana-agent/wal
  global:
    scrape_interval: 15s
    remote_write:
      - url: myurl.com
        proxy_url: http://localhost:8888
        oauth2:
          client_id: ${CLIENT_ID} 
          client_secret: ${CLIENT_SECRET}
          token_url: myurl.com
          scopes: ["myscope"]
          proxy_url: http://localhost:8888  <---- 
```

Now with `traces`, i have tried specifying `proxy_url` on `remote_write` and on `remote_write/oauth2` which makes the agent blow up on startup (due to YAML parse error). Neither are supported it seems.

~I also tried specifying the `HTTP_PROXY` as mentioned in the [OTEL docs](https://opentelemetry.io/docs/collector/configuration/#proxy-support), but this doesn't work either.~

All the above brings me to my points.

1. Can anyone confirm that this is true
2. If true, i would like to contribute to grafana-agent, making HTTP_PROXY support better. How would i get started?
