### ISSUE TITLE
Operator: stuck on reconciling node

### ISSUE THREAD

**Issue by andreabrduque** [grafana/agent#1706]
Hi all, this is not necessarily an issue as Im no expert in k8s. So any help or directions would be much appreciated :)

Im deploying the Grafana Agent Operator using the helm charts (version 0.1.11).

I'm following the quickstart guide and deploying a basic hierarchy of `GrafanaAgent` + `MetricsInstance` + `LogsInstance` +  `PodLogs` to monitor an application. Everything works fine if I keep the agent in the same default node pool. 

However,  I have a second Node Pool with NVIDIA GPUs that Im unable to get logs from ( I can get the metrics fine). I can see from the operator logs, that the controller repeatedly tries to reconcile the nodes from this node pool and outputs the following message repeatedly:

```
 level=info component=controller.node namespace= msg="reconciling node"
````

My questions are:

1 - Should the grafana agent operator be able to create agents in different node pools, or I should specifically schedule them to a particular node pool? 2 -  Has there been any attempts before to monitor node pools with GPUs using the grafana agent? GPU nodes have a taint `nvidia.com/gpu: present` that Im afraid it might be preventing the grafana operator of scheduling pods into it.

**Comment by andreabrduque** [comment]
Closing this, solution was actually very simple. I only had to create a toleration when deploying my grafana agent.

**Comment by nunodsfernandes** [comment]
@andreabrduque could you kindly share how to do it?
Kind of stuck on this..

**Comment by andreabrduque** [comment]
@nunodsfernandes  If you are using GKE and you are installing the drivers as google recommends in the docs, nodes with GPUs get a label `nvidia.com/gpu`. Not sure how it is on EKS for example.

Therefore you can add a toleration to the grafana agent resource like this:

````
apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: grafana-agent
  namespace: default
  labels:
    app: grafana-agent
spec:
  image: grafana/agent:v0.24.1
  logLevel: info
  serviceAccountName: grafana-agent
  nodeSelector:
    cloud.google.com/gke-nodepool: ner-pool
  tolerations:
    - key: nvidia.com/gpu
      operator: Equal
      value: present
      effect: NoSchedule
  metrics:
    instanceSelector:
      matchLabels:
        agent: grafana-agent-metrics
    externalLabels:
      cluster: cloud
  logs:
    instanceSelector:
      matchLabels:
        agent: grafana-agent-logs

```
