### ISSUE TITLE
Second instance of integration is ignored

### ISSUE THREAD

**Issue by v-zhuravlev** [grafana/agent#1718]
Perhaps I found a bug , but not sure, maybe doing something wrong.

If I use integrations-next and try to collect data from two redis instances with config

```
metrics:
  wal_directory: /tmp/wal
  global:
    remote_write:
    - url: http://cortex.k3d.localhost:9999/api/prom/push
    - basic_auth:
        password: <password>
        username: 232426
      url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
  configs:
    - name: default
integrations:
  redis_configs:
    - instance: localhost
      redis_addr: redis://localhost:6379
    - instance: localhost1
      redis_addr: redis://localhost:6379
```

Start the agent( it is not required to startup actual redis)

**Expected:**
In Grafana->explore you should see both metrics for PromQL `redis_exporter_build_info` with instance=localhost and instance=localhost1
**Actual:**
In Grafana->explore you see only first metric for PromQL `redis_exporter_build_info` with instance=localhost

At the same time, If you swap the list and restart the agent, then you can see both metrics:

```
metrics:
  wal_directory: /tmp/wal
  global:
    remote_write:
    - url: http://cortex.k3d.localhost:9999/api/prom/push
    - basic_auth:
        password: <password>
        username: 232426
      url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
  configs:
    - name: default
integrations:
  redis_configs:
    - instance: localhost1
      redis_addr: redis://localhost:6379
    - instance: localhost
      redis_addr: redis://localhost:6379

```
