### ISSUE TITLE
wal_directory value in agent.yaml ignored

### ISSUE THREAD

**Issue by jaredmcqueen** [grafana/agent#1738]
I'm running the container `grafana/agent:lastest` in an OpenShift Kubernetes environment.  I can only write it special paths, like `/tmp`.  By default, the wal file is writing to `/etc/agent/data` which will never work.  I can't get the agent to pick up the `wal_directory` value.  

my agent.yaml:
```
1000680000@python-starter-779975797-48ktl:/etc/agent$ pwd
/etc/agent
1000680000@python-starter-779975797-48ktl:/etc/agent$ cat agent.yaml
metrics:
  global:
    scrape_interval: 1m
  wal_directory: /tmp/wal
  configs:
    - name: test
      host_filter: false
      scrape_configs:
        - job_name: local_scrape
          static_configs:
            - targets: ['127.0.0.1:12345']
              labels:
                cluster: 'localhost'
      remote_write:
        - url: http://prometheus-server:9009/api/prom/push
server:
  log_level: debug
```

error I'm seeing in my kubernetes pod logs:
```
grafana-agent ts=2022-05-25T21:32:12.193834853Z caller=instance.go:298 level=debug agent=prometheus instance=4455161823efd642e79e4c12268b50a4 msg="initializing instance" name=4455161823efd642e79e4c12268b50a4
grafana-agent ts=2022-05-25T21:32:12.193925348Z caller=instance.go:307 level=error agent=prometheus instance=4455161823efd642e79e4c12268b50a4 msg="failed to initialize instance" err="error creating WAL: create dir: mkdir /etc/agent/data: permission denied"
```

Any guidance on how to set that wal directory would be greatly appreciated, thanks!
