### ISSUE TITLE
configuration-reference.md example does not match actual implementation: flag provided but not defined: -integrations.node_exporter.rootfs-path

### ISSUE THREAD

**Issue by bkcsfi** [grafana/agent#176]
Hi,

on https://github.com/grafana/agent/blob/master/docs/configuration-reference.md

there is this example for node-exporter config under docker:

```shell
docker run \
  --net="host" \
  --pid="host" \
  --cap-add=SYS_TIME \
  -v "/:/host:ro,rslave" \
  -v /tmp/agent:/etc/agent \
  -v /path/to/config.yaml:/etc/agent-config/agent.yaml \
  grafana/agent:v0.5.0 \
  --config.file=/etc/agent-config/agent.yaml \
  --integrations.node_exporter.rootfs-path=/host
```

however the argument `--integrations.node_exporter.rootfs-path=/host` is not accepted by grafana/agent:master-9e81239

It returns this error: `flag provided but not defined: -integrations.node_exporter.rootfs-path`

there aren't any -integration options listed in the help output from the agent.

**Comment by rfratto** [comment]
Hi @bkcsfi, 

Thanks for reporting this, and I'm sorry you ran into this issue. Those docs were written before the node_exporter integration was finalized and at a point where it still included command line flags, and I forgot to update them. 

This is the docker command you should be using:

```
docker run \
  --net="host" \
  --pid="host" \
  --cap-add=SYS_TIME \
  -v "/:/host:ro,rslave" \
  -v /tmp/agent:/etc/agent \
  -v /path/to/config.yaml:/etc/agent-config/agent.yaml \
  grafana/agent:v0.5.0 \
  --config.file=/etc/agent-config/agent.yaml 
```

Note that `/path/to/config.yaml` must be replaced with a path to a `config.yaml` file on your host machine. You can use this `config.yaml` file for reference:

```yaml
server:
  log_level: info
  http_listen_port: 12345

prometheus:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 5s

integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true
    rootfs_path: /host
  prometheus_remote_write:
    - url: http://localhost:9009/api/prom/push
```

Replace the URL on the last line with the URL you want to write data to, and add a `basic_auth` section if it is needed, like so:

```yaml
# ... other settings ... 

integrations:
  # ... other settings ...
  prometheus_remote_write:
    - url: http://localhost:9009/api/prom/push
      basic_auth:
        username: admin
        password: s3cur3p455
```

I'd like to leave this issue open to track fixing the instructions; you're more than free to contribute fixes yourself if you want, otherwise I can get to it in a few days.
