### ISSUE TITLE
Node Exporter "instance: hostname" not replacing hostname with "__address__"

### ISSUE THREAD

**Issue by guillecro** [grafana/agent#1779]
I did a clean install of grafana agent in one of my servers
We've been using grafana agent but because of the new config we decided to re-do the config.

```
xxxx@yyyy:/# grafana-agent --version
agent, version v0.24.2 (branch: HEAD, revision: 1216514b)
```

The problem is that, when using the Grafana Cloud Node Exporter Dashboard, the "instance" value is "hostname", even if in the config we have the default configuration from the install that grafana cloud provides for the integration

![image](https://user-images.githubusercontent.com/8771166/172221967-40c3f14f-73f2-4aff-9690-8e0d7d16f43b.png)

Here is the configuration, its straight from the install process.

```
--- Retrieving config and placing in /etc/grafana-agent.yaml
integrations:
  node_exporter:
    enabled: true
    relabel_configs:
    - replacement: hostname
      source_labels:
      - __address__
      target_label: instance
  prometheus_remote_write:
  - basic_auth:
      password: XXXXXXXXXXXXXXXXXXXXXXXXX
      username: XXXXXXXXXXXXXXXXXXXXXXXXX
    url: XXXXXXXXXXXXXXXXXXXXXXXXX
logs:
  configs:
  - clients:
    - basic_auth:
        password: XXXXXXXXXXXXXXXXXXXXXXXXX
        username: XXXXXXXXXXXXXXXXXXXXXXXXX
      url: XXXXXXXXXXXXXXXXXXXXXXXXX
    name: integrations
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
    - job_name: integrations/node_exporter_journal_scrape
      journal:
        labels:
          instance: hostname
          job: integrations/node_exporter
        max_age: 24h
      relabel_configs:
      - source_labels:
        - __journal__systemd_unit
        target_label: unit
      - source_labels:
        - __journal__boot_id
        target_label: boot_id
      - source_labels:
        - __journal__transport
        target_label: transport
      - source_labels:
        - __journal_priority_keyword
        target_label: level
    target_config:
      sync_period: 10s
metrics:
  configs:
  - name: integrations
    remote_write:
    - basic_auth:
        password: XXXXXXXXXXXXXXXXXXXXXXXXX
        username: XXXXXXXXXXXXXXXXXXXXXXXXX
      url: XXXXXXXXXXXXXXXXXXXXXXXXX
  global:
    scrape_interval: 60s
  wal_directory: /tmp/grafana-agent-wal
server:
  http_listen_port: 12345

--- Enabling and starting grafana-agent.service
```

It was working with the previous configuration with v0.21.2 but upgrading to v0.24.2 doesnt replace the hostname label with __address__

**Comment by rfratto** [comment]
👋 

```yaml
instance: hostname
``` 

This is a literal string and won't be replaced by the hostname of the machine. You can try `${HOSTNAME}` with `-config.expand-env` passed as a command line flag to expand it as an environment variable, though.

**Comment by guillecro** [comment]
I see, it was a breaking change from https://grafana.com/docs/agent/latest/upgrade-guide/#v0210
It was a bit confusing because in the node_exporter configuration for the metrics says:
```
    - replacement: hostname
      source_labels:
      - __address__
      target_label: instance
```

`__address__`, which is `<agent machine hostname>:<agent listen port>` would be the instance label value but according to the upgrade documentation this breaking change was implemented in v0.21.0 and says _integrations that connect to an external system will now infer an appropriate value based on the config for that specific integration_. 

In the integration it says: 
> In order to see logs and metrics signals correlated on the same dashboard, you need to make sure that `job` and `instance` labels match in `node_exporter` integration config under `metrics`, and under `logs`
And I wasn't sure what was asking me to do but now after reading again the breaking change in v0.21.0 I understand now.

Thanks for clarifying it, I am now able to match the pieces.
Hope this issue helps whoever goes through this problem!
