### ISSUE TITLE
[traces] Panic in tail sampling "and" processor if no type

### ISSUE THREAD

**Issue by joe-elliott** [grafana/agent#1797]
If a tail sampling "and" processor is used but no type is specified then the agent panics. 

This config
```
    tail_sampling:
      policies:
      - and:
          and_sub_policy:
          - <correctly specified subpolicy>
          - <correctly specified sub policy>
          ...
```

Will produce this panic:

```
agent_1                     | panic: runtime error: invalid memory address or nil pointer dereference
agent_1                     | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2880ad0]
agent_1                     | 
agent_1                     | goroutine 81 [running]:
agent_1                     | github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor/internal/sampling.(*And).Evaluate(0x7?, {{{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xfb, ...}}}, ...)
agent_1                     | 	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor@v0.46.0/internal/sampling/and.go:44 +0x70
agent_1                     | github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor.(*tailSamplingSpanProcessor).makeDecision(0xc000ab0000, {{{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xfb, ...}}}, ...)
agent_1                     | 	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor@v0.46.0/processor.go:221 +0x1c4
agent_1                     | github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor.(*tailSamplingSpanProcessor).samplingPolicyOnTick(0xc000ab0000)
agent_1                     | 	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor@v0.46.0/processor.go:170 +0x825
agent_1                     | github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor.(*policyTicker).onTick(...)
agent_1                     | 	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor@v0.46.0/processor.go:473
agent_1                     | github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor.(*policyTicker).start.func1()
agent_1                     | 	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor@v0.46.0/processor.go:465 +0x32
agent_1                     | created by github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor.(*policyTicker).start
agent_1                     | 	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor@v0.46.0/processor.go:461 +0xad
```

The below corrected config works fine. (Note the addition of "type: and")
```
    tail_sampling:
      policies:
      - type: and
        and:
          and_sub_policy:
          - <correctly specified subpolicy>
          - <correctly specified sub policy>
          ...
```
