### ISSUE TITLE
cAdvisor on Docker host not reporting container metadata

### ISSUE THREAD

**Issue by hbjydev** [grafana/agent#1807]
I have Grafana Agent installed on a bare Docker host we have some apps running on, and I have this in my config:

```yml
integrations:
  # ... (node_exporter, etc.)
  cadvisor:
    enabled: true
    docker_only: true
```

But for some reason, the only container-relevant label that comes back on any of the `container_*` metrics is `id`, I don't see `name`, `image`, or any of the labels or environment variables. The [documentation](https://grafana.com/docs/agent/latest/configuration/integrations/cadvisor-config/) tells me that it should be collecting all of this already, so is there something I'm misconfiguring or have I spotted a bug?

**Comment by tpaschalis** [comment]
Hi there 👋 When `docker_only is set to true, it just propagates to cAdvisor's [DockerOnly](https://github.com/google/cadvisor/blob/24e7a9883d12f944fd4403861707f4bafcaf4f3d/container/raw/factory.go#L33) flag so there isn't much to go wrong there.

As stated in the cAdvisor [docs](https://github.com/google/cadvisor/blob/master/docs/running.md#standalone), it requires elevated privileges in order to capture all metrics; otherwise it will just degrade the set of the metrics reported instead of failing outright.

Similarly, as we're embedding the cAdvisor code, I believe that it requires you to run the Agent with superuser privileges in order to collect all metrics. To make sure that's the case, you could set the log_level to `debug` and see if there's any reported 'permission denied' errors. If that solution isn't possible in your setup, you might be able to run the cAdvisor by itself as `root` and then use the Agent to scrape its endpoint.

**Comment by hbjydev** [comment]
@tpaschalis Thanks for that! Once I get in and finish any Cloudflare-flavoured firefighting this morning I’ll try these. :)

**Comment by shizunge** [comment]
I have successfully run cadvisor via grafana-agent by mount the following volumes:

```
```

**Comment by activifinder** [comment]
@shizunge Can you share your working config for grafana agent and for the cadvisor container? I'm also struggling because container names don't get published in my metrics.

**Comment by adrenaline681** [comment]
@shizunge Can you share your working config for grafana agent and for the cadvisor container? I'm also struggling because container names don't get published in my metrics.

**Comment by shizunge** [comment]
I started it via a docker compose file:
```
version: '3.8'
services:
  grafana-agent:
    image: grafana/agent:latest
    cap_add:
      # SYS_TIME for node exporter
      - SYS_TIME
    command:
      - "-config.file=/grafana-agent.yml"
      - "-config.expand-env"
      - "-disable-support-bundle"
    networks:
      - host
    hostname: "{{.Node.Hostname}}"
    env_file:
      - ./env-global.env
    secrets:
      - source: grafana-cloud-api-token-remote-write
        target: /logs-remote-write-password
      - source: grafana-cloud-api-token-remote-write
        target: /metrics-remote-write-password
    configs:
      - source: grafana-agent-config
        target: /grafana-agent.yml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # For cadvisor, promtail also needs docker.sock
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # For loki to read docker log files.
      # - /var/lib/docker:/var/lib/docker:ro
      # node_exporter also needs to access '/', '/sys', '/proc', these could be shared with cadvisor.
      # There is no way to configure cadvisor where to read data.
      # cadvisor needs /proc to read network stats. Or cadvisor will read data from /rootfs/proc.
      # cadvisor needs /sys and /var/lib/docker for container discovery.
      - /:/rootfs:ro,rslave
      - /sys:/sys:ro,rslave
      - /var/lib/docker:/var/lib/docker:ro
      - grafana-agent-log-positions:/positions
      - grafana-agent-metrics-wal:/metrics-wal
    deploy:
      mode: global
```

**Comment by shizunge** [comment]
Agent config:
```
integrations:
  cadvisor:
    enabled: true
    instance: ${NODE_NAME:-HOST_NO_NAME}
    # Metrics for the integration will be exposed at /integrations/cadvisor/metrics
    scrape_integration: true
    scrape_interval: 15s
    scrape_timeout: 10s
    # relabel_configs:
    metric_relabel_configs:
      # Drop unused metrics with larger number of series.
      # Drop metrics for the root
      - source_labels: ['id']
        regex: '^/$'
        action: drop
      # Add PROJECT_NAME to the job name.
      - source_labels: ['job']
        target_label: 'job'
        replacement: '${PROJECT_NAME}/cadvisor'
      # Change label name container_label_com_docker_swarm_service_name -> service
      - source_labels: ['container_label_com_docker_swarm_service_name']
        target_label: 'service'
      - source_labels: ['container_label_com_docker_swarm_service_name']
        target_label: 'container_label_com_docker_swarm_service_name'
        replacement: ''
    store_container_labels: false
    allowlisted_container_labels: ['com.docker.swarm.service.name']
    # Options are accelerator,advtcp,app,cpu,cpuLoad,cpu_topology,cpuset,disk,diskIO,hugetlb,
    # memory,memory_numa,network,oom_event,percpu,perf_event,process,referenced_memory,resctrl,
    # sched,tcp,udp.
    # https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md
    enabled_metrics: ['cpu', 'diskIO', 'memory', 'network']
    docker: 'unix:///var/run/docker.sock'
    docker_only: true
    # # Also see https://github.com/google/cadvisor/issues/3037
    # disable_root_cgroup_stats: true
```
