### ISSUE TITLE
`docs/user/configuration/traces-config.md` contains wrong information about configuring `tail_sampling.policies` 

### ISSUE THREAD

**Issue by bartoszbehring-form3** [grafana/agent#1809]
Recently we wanted to configure tail sampling policies the agent. We followed [the documentation](https://grafana.com/docs/agent/latest/configuration/traces-config/) that mentions you should define them in the same way as it is in the [Open Telemetry Collector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/b2327211df976e0a57ef0425493448988772a16b/processor/tailsamplingprocessor).  For example:
``` yaml
tail_sampling:
  policies:
     [
          {
            name: test-policy-1,
            type: always_sample
          }
     ]
```

It turned out with such configuration the agent was returning [following error](https://github.com/grafana/agent/blob/d0a3f5773da5f451f130227ea6c67e9222dad939/pkg/traces/config.go#L528). After digging out in the Grafana Agent code we figured it out that, we should do it in the following way instead:
``` yaml
tail_sampling:
  policies:
    - always_sample: ""
```

I'm not sure if it's just a documentation being wrong or it is the bug in the code and the Grafana Agent would like to follow the Open Telemetry Collector scheme for this field.
