### ISSUE TITLE
pipeline support for metrics

### ISSUE THREAD

**Issue by oscni** [grafana/agent#1821]
Would be very useful with pipeline support for metrics. Specifically the tenant function.
https://grafana.com/docs/loki/latest/clients/promtail/stages/tenant/

**Comment by tpaschalis** [comment]
Hey there 👋  thanks for the suggestion! We're exploring adding a more pipeline-like functionality into the Agent, so stay tuned for more news in the future!

About the specific `tenant` functionality, we don't currently support something as fancy as Loki's solution.

What you could do (at least for now) is to use the `headers` field under remote_write, to configure an extra header along your metrics. The header value could also be more dynamic by using an env var and passing the `-config.expand-env` CLI flag.

```yaml
remote_write:
- url: <remote-url>
  headers:
    X-Scope-OrgID: "my-custom-value"
```
