### ISSUE TITLE
grafana agent fails to read generated config file

### ISSUE THREAD

**Issue by yusi1** [grafana/agent#1823]
I've followed the steps in "Hosted Prometheus metrics" on Grafana Cloud to generate a config file for the agent on Linux AMD64 but the agent fails with:
```
2022-06-23 22:11:02.266982 I | error loading config file ./agent-config.yaml: yaml: unmarshal errors:
  line 1: field global not found in type config.config
  line 4: field scrape_configs not found in type config.config
```

This is the generated config file with sensitive information redacted:
```
global:
  scrape_interval: 60s

scrape_configs:
  - job_name: node
    static_configs:
    - targets: ['localhost:9100']

remote_write:
  - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
    basic_auth:
      username: [REDACTED]
      password: [REDACTED]
```

I have no clue why it fails with these errors, if it was autogenerated, shouldn't the config file be correct?

**Comment by tpaschalis** [comment]
It's an indentation issue. The [`global` key](https://grafana.com/docs/agent/latest/configuration/metrics-config/#global_config) should be under the `metrics` block, while the rest of the config, a [`metrics_instance_config` block](https://grafana.com/docs/agent/latest/configuration/metrics-config/#metrics_instance_config) should be under an array of metrics configs.

Here's how I'd rearrange the fields so it would work.
```
metrics:
  global:
    scrape_interval: 60s
  configs:
  - name: foo
    scrape_configs:
      - job_name: node
        static_configs:
        - targets: ['localhost:9100']

    remote_write:
      - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
        basic_auth:
          username: foo
          password: bar
```


In any case, I think it might be a good opportunity to improve our onboarding process! Can you share how you ended up with this config via Grafana Cloud?
