### ISSUE TITLE
mongodb_exporter have no metrics

### ISSUE THREAD

**Issue by wkjun** [grafana/agent#1834]
docker image version: 0.25.1 

when i deploy grafana-agent in k8s. use `0.25.1` version

the main config is :

```
 integrations:
      mongodb_exporter:
        enabled: true
        mongodb_uri: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_INSTANCE}.${DB_NAMESPACE}:27017
        relabel_configs:
        - source_labels: [__address__]
          target_label: instance
          replacement: ${CLUSTER_TYPE}.${DB_INSTANCE}
        - source_labels: [__address__]
          target_label: service_name
          replacement: ${DB_INSTANCE}
        - source_labels: [__address__]
          target_label: mongodb_cluster
          replacement: ${DB_INSTANCE}_cluster
```

It just only show the `mongodb_up` gauge. 

refer the issue  `https://bytemeta.vip/repo/percona/mongodb_exporter/issues/477` the `v0.31.2` MongoDB Exporter need add a  parameter `--collect-all`,please provide like parameter to grafana-agent  in mongodb_exporter.
