### ISSUE TITLE
Incorrect flag in integrations-next autoscrape deserializes incorrect parameter without error.

### ISSUE THREAD

**Issue by rgeyer** [grafana/agent#1840]
Given the following config file, the agent will run successfully, but will not actually autoscrape the enabled node_exporter integration.

This is because the correct parameter is `enable: true`, but `enabled: true` is allowed during deserialization, effectively failing silently.

gragent-autoscrape-deser.fail.yaml
```
server:
    http_listen_address: 0.0.0.0
    http_listen_port: 8080
integrations:
    metrics:
        autoscrape:
            enable: false
    node_exporter_configs:
        - autoscrape:
            enabled: true
            metrics_instance: default
```

`docker run --rm -it -p 8080:8080 -v $(pwd):/config grafana/agent:v0.25.1 -config.file /config/gragent-autoscrape-deser-fail.yaml -enable-features integrations-next -config.enable-read-api`

In the resulting config (`curl localhost:8080/-/`), note that the node_exporter integration is set to `enable: false`.

The expected behavior is that the invalid parameter `enabled` would cause a deserialization error.
