### ISSUE TITLE
Grafana Agent Operator - Logs: Too many open files

### ISSUE THREAD

**Issue by jallaix** [grafana/agent#1844]
Not sure how to reproduce the bug.
It happened the first time I tried Grafana Agent Operator, setting a PodLogs configured to retrieve logs for all pods of all namespaces of the K8s cluster.

With PodLogs having a more reduced scope, the bug happens on 1 of my 6 clusters.

Below is the log of the *config-reloader* container of the *grafana-agent-logs* pod:
```
add config file /var/lib/grafana-agent/config-in/agent.yml to watcher: create watcher: too many open files
```

As a result the *grafana-agent* container of the *grafana-agent-logs* pod keeps crashing (CrashLoopBackOff) because of:
```
error loading config file /var/lib/grafana-agent/config/agent.yml: error reading config file open /var/lib/grafana-agent/config/agent.yml: no such file or directory
```

Below are my PodLogs:
```yaml
apiVersion: monitoring.grafana.com/v1alpha1
kind: PodLogs
metadata:
  labels:
    instance: primary
  name: system
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - kube-system
    - external-secrets
  selector:
    matchLabels: {}
---
apiVersion: monitoring.grafana.com/v1alpha1
kind: PodLogs
metadata:
  labels:
    instance: primary
  name: split
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - split
    - ingress-nginx
  selector:
    matchLabels: {}
```
