### ISSUE TITLE
Cannot unmarshal http_listen_address and http_listen_port

### ISSUE THREAD

**Issue by std66** [grafana/agent#1935]
### Issue description
I've just registered on Grafana Cloud and downloaded and installed the Grafana Agent. The stock installation works just fine, but only accessible on localhost. I want to make Grafana Agent publicly accessible by specifying **http_listen_address** and **http_listen_port** according to this page:
https://grafana.com/docs/grafana-cloud/data-configuration/agent/#agent-ip-address
so that Grafana Cloud can collect metrics from my system. Adding these two properties to the agent-config.yaml makes the Agent not able to start.

### Environment
Operating system: Windows 10 1909 Build 18363.1082
Grafana Agent version:
```
C:\Program Files\Grafana Agent>agent-windows-amd64.exe -version
agent, version v0.26.0 (branch: HEAD, revision: bb7473b8)
  build user:       root@177cd7f753cb
  build date:       2022-07-18T17:15:00Z
  go version:       go1.18
  platform:         windows/amd64
```

### Grafana Agent configuration file
```
server:
  log_level: warn
  http_listen_address: 0.0.0.0
  http_listen_port: 12345
metrics:
  wal_directory: C:\ProgramData\grafana-agent-wal
  global:
    scrape_interval: 1m
  configs:
    - name: integrations
integrations:
  windows_exporter:
    enabled: true
```

### Grafana Agent output
```
C:\Program Files\Grafana Agent>agent-windows-amd64.exe -config.file agent-config.yaml
2022-07-21 13:05:45.618456 I | error loading config file agent-config.yaml: yaml: unmarshal errors:
  line 3: field http_listen_address not found in type server.config
  line 4: field http_listen_port not found in type server.config
```

**Comment by tpaschalis** [comment]
Hey there 👋 

I suppose you're using Agent v0.26.0, right? Most of the `server` block fields fields have been [deprecated](https://grafana.com/docs/agent/v0.26/upgrade-guide/#breaking-change-deprecated-yaml-fields-in-server-block-removed) and are now configurable via command line flags.

**Comment by std66** [comment]
Thank you, I'll give it a try.

**Comment by std66** [comment]
OK, I've got it working, but there were some steps missing from my end, as it turned out.
1. I had to modify the startup command of the Grafana Agent, as you've pointed out:
```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Grafana Agent
ImagePath = "C:\Program Files\Grafana Agent\agent-windows-amd64.exe" -config.file="C:\Program Files\Grafana Agent\agent-config.yaml" -server.http.address="0.0.0.0:12345"
```
2. On grafana.com I had to obtain a hostname, a username and API key for Prometheus remote write. This can be done in the user profile settings.
3. Using the information gathered on step 2, I had to extend the agent-config.yaml file:
```
server:
  log_level: warn
metrics:
  wal_directory: C:\ProgramData\grafana-agent-wal
  global:
    scrape_interval: 1m
  configs:
    - name: integrations
integrations:
  windows_exporter:
    enabled: true
  prometheus_remote_write:
   - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
     basic_auth:
       username: <6-digit number>
       password: <API key>
```

Now I have metrics and a fancy Windows dashboard on Grafana Cloud.

Thank you for your help!
