### ISSUE TITLE
Integration yaml not strictly checking

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#1952]
Integration yaml checks the first level (that an integration is correct), but does not check the sub settings. IE
The below unmarshals but `sup` is not identified as an invalid setting
```
integrations:
  windows_exporter:
    enabled: true
    services:
      sup: "WHERE Name='Grafana Agent'"
```
The below does unmarshal and the agent fails to load
```
integrations:
  windows_exporter:
    enabled: true
    servicesbad:
      sup: "WHERE Name='Grafana Agent'"
```
