### ISSUE TITLE
Matching of sending IP address to find pod info should strip the port number first

### ISSUE THREAD

**Issue by jphx** [grafana/agent#1984]
I'm using the Grafana Agent, version 0.26.1, configured using the tk/jsonnet configuration alternative.  My configuration file includes this to enable translation of the sending IP address into pod information:

```yaml
scrape_configs:
  - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    job_name: kubernetes-pods
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: false
```

However, I see no pod information in the captured traces.  After enabling debug-level logging in the Grafana Agent, I see this error message when the trace is received:

```
ts=2022-08-03T13:07:49.133188793Z caller=prom_sd_processor.go:166 level=debug component="traces service disco" msg="unable to find matching hostLabels" ip=172.30.114.52:54443
```

I believe the Grafana Agent knows about the IP address because I see messages like this earlier in the log:
```
ts=2022-08-03T13:07:26.142710099Z caller=prom_sd_processor.go:284 level=debug component="traces service disco" msg="adding host to hostLabels" host=172.30.114.52
```

I believe the presence of the port number in the string being looked up is causing the failure to find the match.  The port number should be stripped before doing the lookup.
