### ISSUE TITLE
server.http-listen-address not works as expect

### ISSUE THREAD

**Issue by Kaminari-Y** [grafana/agent#206]
OS and agent version
```
root@ray-cookbook101:~# uname -a
Linux ray-cookbook101 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@ray-cookbook101:~#
root@ray-cookbook101:~# agent -version
agent, version v0.6.1 (branch: HEAD, revision: 18ce4f4)
  build user:       runner@fv-az184
  build date:       2020-09-11T14:22:34Z
  go version:       go1.14.4
```

agent.yaml
```
server:
  log_level: info
  http_listen_address: 100.1.1.1
  http_listen_port: 12345
prometheus:
  wal_directory: /grafana-cloud-agent-data
  global:
    scrape_interval: 30s
    scrape_timeout: 10s
integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true
```

- Case 1
If I set http_listen_address: 100.1.1.1, could access 100.1.1.1:12345 to see metrics, but couldn't push to remote storage

- Case 2
If I set http_listen_address: 127.0.0.1, could't access 100.1.1.1:12345 of course, but I can see metrics pushed to my remote storage.
