### ISSUE TITLE
Operator Compute resources for log agent and metric agent should be separated

### ISSUE THREAD

**Issue by andreivaloshyn** [grafana/agent#2081]
Now we can set up compute resources only for entire agent
```
apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: grafana-agent
  labels:
    app: grafana-agent
spec:
  image: grafana/agent
  resources:
    requests:
      cpu: {{ GRAFANA_AGENT_RESOURCE_CPU_MIN }}
      memory: {{ GRAFANA_AGENT_RESOURCE_MEMORY_MIN }}
    limits:
      cpu: {{ GRAFANA_AGENT_RESOURCE_CPU_MAX }}
      memory: {{ GRAFANA_AGENT_RESOURCE_MEMORY_MAX }}
....
```
and it will be applied for Metric StatefulSet and Log DaemonSet which sometimes can be inconvenient
