### ISSUE TITLE
Scrape Error message unclear/unprecise

### ISSUE THREAD

**Issue by eviscares** [grafana/agent#2097]
Hi,

we're having a bit of an issue debugging a scraper, due to the unclear error message that we're getting.
The error we're getting is: `"scrape_error":"server returned HTTP status 401 "`, which is not entirely helpful, especially as we have good reason to believe, that the agent can reach the metrics endpoint. One reason for that is, that it is possible to curl the metrics endpoint from the grafana_agent pod and receive all the metrics, and the other one is, that we have another scraping config that works for the endpoint.
Config that doesn't work:
```yaml 
           - job_name: "kubernetes-pods"
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                # Make Scheme configurable by setting prometheus.io/scheme
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
                  action: replace
                  target_label: __scheme__
                  regex: (.+)
                # Scrape metrics when the prometheus.io/scrape annotation has been set to true
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                  action: keep
                  regex: true
                # Allow us to overwrite the path with the content of prometheus.io/path
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                  action: replace
                  target_label: __metrics_path__
                  regex: (.+)
                  # Allow us to overwrite the default path with the content of prometheus.io/port
                - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                  action: replace
                  regex: (.+):(?:\d+);(\d+)
                  replacement: ${1}:${2}
                  target_label: __address__
                # Expose Pod labels as metric labels
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_(.+)
                # Expose Pod namespace as metric namespace label
                - source_labels: [ __meta_kubernetes_namespace ]
                  action: replace
                  target_label: namespace
                # Expose Pod name as metric name label
                - source_labels: [ __meta_kubernetes_pod_name ]
                  action: replace
                  target_label: pod
              scheme: http
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: false
                server_name: kubernetes
```

config that does work:
```yaml
           - job_name: 'spring boot scrape'
              metrics_path: '/metrics'
              scrape_interval: 5s
              static_configs:
                - targets: ['backend-svc:58180']
```
