### ISSUE TITLE
Tracing Prometheus service discovery fails silently

### ISSUE THREAD

**Issue by joe-elliott** [grafana/agent#212]
If the prometheus service disco in the tracing pipeline fails then nothing is logged and no pods are discovered.

To reproduce:
-  Deploy grafana agent with a k8s service disco such as:
```
tempo:
    scrape_configs:
      - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
        tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: false
```

- Deploy this to a cluster where the grafana agent does not have permissions to query pods.  (i.e. denied via RBAC).
- Observe that no failures are logged and no pods are discovered.
