### ISSUE TITLE
how about adding promtail server to logs

### ISSUE THREAD

**Issue by songjiayang** [grafana/agent#2143]
My application had used log push mode (push to loki server directly ) yet, when change it to agent way, I really it can compatible the `/loki/api/v1/push`,  so no need to deploy promtail separately.

**Comment by tpaschalis** [comment]
Hey there 👋  Thanks for the suggestion!

You can already do that today, as the Grafana Agent embeds Promtail for logs; just use the `loki_push_api` key under [scrape_configs](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#scrape_configs) to configure the server!

The following config will [accept](https://grafana.com/docs/loki/latest/api/#push-log-entries-to-loki) snappy-compressed POST requests on `http://localhost:3500/loki/api/v1/push` as well as newline-delimited log lines on `http://localhost:3500/promtail/api/v1/raw`. You can use this request to test it out
```
curl -v -H "Content-Type: application/json" -XPOST -s "http://localhost:3500/loki/api/v1/push" --data-raw \
  '{"streams": [{ "stream": { "foo": "bar2" }, "values": [ [ "1570818238000000000", "fizzbuzz" ] ] }]}'
```

```yaml
logs:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: my_job_name
        loki_push_api:
          server:
            http_listen_port: 3500
            grpc_listen_port: 3600
          labels:
            pushserver: push1
    clients:
      - url: https://<user>:<pass>@<url>/loki/api/v1/push
```

We can consider exposing this functionality under a different endpoint for users to send logs directly to an instance of their choosing as we currently do with metrics on `/agent/api/v1/metrics/instance/{instance}/write`, but I believe this should cover your needs!
