### ISSUE TITLE
Is that integrations not send metadata to remote?

### ISSUE THREAD

**Issue by katepangLiu** [grafana/agent#2177]

**Comment by mattdurham** [comment]
Thank you for the issue. Can you provide more detail? For example, what you are expecting to see.

**Comment by katepangLiu** [comment]
My config agent.yaml
```
metrics:
  configs:
    - name: default
      scrape_configs:
        - job_name: local_scrape
      remote_write:
        - url: http://192.168.184.128:9000/receive
          metadata:
            send: true
            send_interval: 1m

integrations:
  redis_configs:
  - redis_addr: 127.0.0.1:6379
```
As expected, redis exporter metadata and metrics should be sent to the remote `127.0.0.1:6379`, but now I can only see the metrics?
