### ISSUE TITLE
Error creating WAL: create dir: mkdir data-agent: permission denied

### ISSUE THREAD

**Issue by MinDBreaK** [grafana/agent#2217]
# What happened?
Unable to start Grafana Agent with systemd

The logs display 
```
Sep 26 09:51:49 ip-XXX-XX-X-XXX grafana-agent[10604]: ts=2022-09-26T09:51:49.706326991Z caller=instance.go:308 level=error agent=prometheus instance=613d7b8d9a2dad114c3ec0a2b3053a7e msg="failed to initialize instance" err="error creating WAL: create dir: mkdir data-agent: permission denied"
Sep 26 09:51:49 ip-XXX-XX-X-XXX grafana-agent[10604]: ts=2022-09-26T09:51:49.706375632Z caller=manager.go:268 level=error agent=prometheus msg="instance stopped abnormally, restarting after backoff period" err="failed to initialize instance: error creating WAL: create dir: mkdir data-agent: permission denied" backoff=5s instance=613d7b8d9a2dad114c3ec0a2b3053a7e
```

However, the data-agent directory is already created, with the correct permissions.

```
ls /tmp
[...]
drwxrwxr-x  3 grafana-agent grafana-agent 4096 Sep 26 09:05 data-agent/
-rw-------  1 grafana-agent grafana-agent   50 Sep 26 10:06 positions.yaml
[...]
```

# What was expected to happen?
The service start can create directories

# Steps to reproduce the problem:
1. Install the deb of the last version
2. Configure logs and metrics
3. Enable the service
4. Start the service
5. The logs displays the errors

Starting manually with the following commands works as expected (Or it does not display the message on stdout/stderr) 
```shell 
sudo -s -u grafana-agent;
grafana-agent -config.file /etc/grafana-agent
```

# Version numbers (grafana, prometheus, graphite, plugins, operating system, etc.):
## Agent 
agent, version v0.28.0-rc.0 (branch: HEAD, revision: e7c14fd4)
  build user:       root@f61f50825f1c
  build date:       2022-09-21T18:33:04Z
  go version:      go1.18.6
  platform:         linux/amd64

## Operating system
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	        22.04
Codename:	jammy

Configuration information:
EC2 instance on AWS. Private VPC.

## Agent target 
Grafana Cloud

## Configuration
```
server:
  log_level: info

metrics:
  global:
    scrape_interval: 1m
    remote_write:
      - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
        basic_auth:
          username: "redacted"
          password: "redacted"

  configs:
    - name: name
      scrape_configs:
        - job_name: 'job_name'
          metrics_path: "/metric/path"
          params:
            format: ['prometheus']
          scheme: http
          bearer_token: "redacted"
          static_configs:
            - targets: ['127.0.0.1:12345']

logs:
  configs:
    - name: default
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: log
          static_configs:
            - targets: [localhost]
              labels:
                job: log
                __path__: /var/log/file.log
      clients:
        - url: https://redacted:redacted@logs-prod-us-central1.grafana.net/loki/api/v1/push
```
## Service file
```
[Unit]
Description=Monitoring system and forwarder
Documentation=https://grafana.com/docs/agent/latest/
Wants=network-online.target
After=network-online.target

[Service]
Restart=always
User=grafana-agent
Environment=HOSTNAME=%H
EnvironmentFile=/etc/default/grafana-agent
ExecStart=/usr/bin/grafana-agent --config.file $CONFIG_FILE $CUSTOM_ARGS
# If running the Agent in scraping service mode, you will want to override this value with
# something larger to allow the Agent to gracefully leave the cluster. 4800s is recommend.
TimeoutStopSec=20s
SendSIGKILL=no

[Install]
WantedBy=multi-user.target
```
