### ISSUE TITLE
[Integrations] [apche_http] instance label is incorrect

### ISSUE THREAD

**Issue by katepangLiu** [grafana/agent#2218]
### Description
When `host` is given without port, agent should take `host` as instance label. 
For now, agent take `host:` as instance label .

### Use case

my agent.yaml
```
server:
  log_level: debug

metrics:
    configs:
        - name: default
          remote_write:
            - url: http://localhost:9090/api/v1/write


integrations:
  apache_http_configs:
    - scrape_uri: http://localhost/server-status?auto
    - scrape_uri: http://localhost:8080/server-status?auto
```

#### Expected
metrics:
```
up{agent_hostname="localhost.localdomain:12345", instance="localhost", job="integrations/apache_http"}
up{agent_hostname="localhost.localdomain:12345", instance="localhost:8080", job="integrations/apache_http"}
```

#### Currently:
metrics:
```
up{agent_hostname="localhost.localdomain:12345", instance="localhost:", job="integrations/apache_http"}
up{agent_hostname="localhost.localdomain:12345", instance="localhost:8080", job="integrations/apache_http"}
```
