### ISSUE TITLE
How to setup `heroku_drain` without `server` block

### ISSUE THREAD

**Issue by Antoine-lb** [grafana/agent#2346]
Hello 👋
In the [Grafana Agent Loki documentation](https://grafana.com/docs/agent/latest/configuration/create-config-file/#loki-configmigrating-from-promtail) it says that I have to "remove the `server` block if present", but how can `heroku_drain` work without it?

Here a sample of the working Pormtail that I'm trying to translate to Grafana Agent:
```yaml
server:
    http_listen_port: 9080
    grpc_listen_port: 0
    log_level: "info"

positions:
  filename: /tmp/positions.yaml

# This bit indicates what Loki instance to write the logs to. We’ll inject the
# details and credentials through environment variables
clients:
- url: https://${LOKI_TENANT_ID}:${LOKI_TOKEN}@${LOKI_HOST}/loki/api/v1/push

scrape_configs:
# Job name, that will be injected in each log line
- job_name: herokutestlogss

# Apply relabel to keep Heroku internal labels
  relabel_configs:
  - source_labels: ['__heroku_drain_host']
    target_label: 'host'
  - source_labels: ['__heroku_drain_app']
    target_label: 'app'
  - source_labels: ['__heroku_drain_proc']
    target_label: 'proc'

# Main heroku target configuration
  heroku_drain:
    server:
      http_listen_address: 0.0.0.0
      # $PORT is a special environment variable that Heroku fills with
      # port that’s accessible from outside the container. We indicate promtail
     # to listen for Heroku logs in it.
      http_listen_port: ${PORT}
      log_level: info
  # Tag each log entry with our job name
    labels: 
      job: herokutestlogss
```

Thanks for your time

**Comment by tpaschalis** [comment]
Hello there Antoine! 👋 

Small caveat: the heroku_drain functionality is not yet available on the Promtail version that the agent is vendoring.
On the plus side, we're already in the process of updating Loki/Promtail to a more recent version, so it _might_ be available in one of our next releases.

Now moving on to how you'd transform this to an Agent config.
Indeed, you need to remove Promtail's `server:` block and replace it with Grafana Agent's own top-level [server](https://grafana.com/docs/agent/latest/configuration/server-config/) key. The agent tries to keep all configuration fields reloadable, so the HTTP/gRPC ports are no longer specified as configuration, but via command-line flags. Finally, in order for variable substitution to work, you'd need to pass in the `-config.expand-env` flag, too.

Here's how the command would work
```
$ ./agent -config.file agent-config.yaml -config.expand-env -server.http.address 0.0.0.0:9080 -server.grpc.address 0.0.0.0:4317
```

```yaml
# agent-config.yaml
server:
    log_level: "info"

logs:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    # This bit indicates what Loki instance to write the logs to. We’ll inject the
    # details and credentials through environment variables
    clients:
    - url: https://$LOKI_TENANT_ID:$LOKI_TOKEN@$LOKI_HOST/loki/api/v1/push

    scrape_configs:
    # Job name, that will be injected in each log line
    - job_name: herokutestlogss

    # Apply relabel to keep Heroku internal labels
      relabel_configs:
      - source_labels: ['__heroku_drain_host']
        target_label: 'host'
      - source_labels: ['__heroku_drain_app']
        target_label: 'app'
      - source_labels: ['__heroku_drain_proc']
        target_label: 'proc'

    # Main heroku target configuration
      heroku_drain:
        server:
          http_listen_address: 0.0.0.0
          # $PORT is a special environment variable that Heroku fills with
          # port that’s accessible from outside the container. We indicate promtail
         # to listen for Heroku logs in it.
          http_listen_port: $PORT
          log_level: info
      # Tag each log entry with our job name
        labels: 
          job: herokutestlogss
```
