### ISSUE TITLE
Operator: ignore pods with Succeeded and Failed phase

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2370]
A recent [change][] to Prometheus Operator ignores pods with the Succeeded and Failed phase by default:

[change]: https://github.com/prometheus-operator/prometheus-operator/blob/a54a34c7a7ce31130fc9e271b410c1ebd8e9e0bf/pkg/prometheus/promcfg.go#L798-L804

We should bring in this change to the Grafana Agent Operator. This can help avoid scenarios where 
unexpected metrics appear from a non-running pod because the IP of that pod got recycled and is in use by another application.

**Comment by tillepille** [comment]
Hi @rfratto !
We run into this problem as well, especially with a fair share of cronjobs where the pods stay for a time after completion and smaller subnets, so we recycle IPs quite regularly.

For my understanding the problem also occurs independent from the operator.
Or is there already a way do handle that already in the configuration?

**Comment by rfratto** [comment]
> For my understanding the problem also occurs independent from the operator.
> Or is there already a way do handle that already in the configuration?

Right, this can happen in any scenario where kubernetes_sd_configs are used. The solution is to add relabel configs to ignore these pods. 

For non-operator configs:

```yaml 
relabel_configs:
  - source_labels: ["__meta_kubernetes_pod_phase"] 
    regex: Failed|Succeeded 
    action: drop 
```

For operator configs (such as PodMonitor):

```yaml 
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: example-podmonitor
  namespace: example
spec:
  podMetricsEndpoints:
    - relabelings:
        - action: drop
          source_labels: ['__meta_kubernetes_pod_phase']
          regex: Failed|Succeeded
      ...
  ...
```
