### ISSUE TITLE
Can't configure modules for blackbox exporter

### ISSUE THREAD

**Issue by zanderson-aim** [grafana/agent#2400]
Trying to adding a ICMP probe to the new feature, but it appears not matter how I configure it does not work. I was able to get ICMP to work if I create a module called "http_2xx" but pick type as ICMP. Not sure if I'm configuring it wrong, or if there is a bug that is hard coding all targets to use modules "http_2xx"

Here is my config
Modules:
```
modules:      
  http_2xx:
    prober: "icmp"
    timeout: 5s                 
  http_2xx_ipv4:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: "ip4"        
  icmp_ipv4:
    prober: "icmp"
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"    
```
Targets
```
    blackbox_targets:
      - name: icmp_google
        address: 8.8.8.8
        module: icmp_ipv4
      - name: icmp_cloudflare
        address: 1.1.1.1
        module: icmp_ipv4
      - name: http_google
        address: "https://www.google.com"
        module: http_2xx_ipv4
      - name: http_cloudflare
        address: "https://www.cloudflare.com"
        module: http_2xx_ipv4   
```

But when I launch the agent it only seems to want/use http_2xx. I can make ICMP work by defining the module but picking type icmp
```
ts=2022-10-20T16:31:44.8869746Z caller=handler.go:187 integration=blackbox module=http_2xx target=https://www.google.com level=debug msg="Beginning probe" probe=icmp timeout_seconds=5
ts=2022-10-20T16:31:44.8869746Z caller=handler.go:187 integration=blackbox module=http_2xx target=https://www.google.com level=debug msg="Resolving target address" target=https://www.google.com ip_protocol=ip6
ts=2022-10-20T16:31:44.889185Z caller=handler.go:187 integration=blackbox module=http_2xx target=https://www.google.com level=debug msg="Resolution with IP protocol failed" target=https://www.google.com err="lookup https://www.google.com: no such host"
```
```
ts=2022-10-20T16:31:42.4797872Z caller=handler.go:187 integration=blackbox module=http_2xx target=1.1.1.1 level=debug msg="Beginning probe" probe=icmp timeout_seconds=5
ts=2022-10-20T16:31:42.4797872Z caller=handler.go:187 integration=blackbox module=http_2xx target=1.1.1.1 level=debug msg="Resolving target address" target=1.1.1.1 ip_protocol=ip6
ts=2022-10-20T16:31:42.4820991Z caller=handler.go:187 integration=blackbox module=http_2xx target=1.1.1.1 level=debug msg="Resolved target address" target=1.1.1.1 ip=1.1.1.1
ts=2022-10-20T16:31:42.4826261Z caller=handler.go:187 integration=blackbox module=http_2xx target=1.1.1.1 level=debug msg="Creating socket"
```

Here is the config if I pull it the from the /-/config endpoint
```
  blackbox:
    enabled: true
    scrape_interval: 1m0s
    scrape_timeout: 1m0s
    config_file: C:\Program Files\Grafana Agent\blackbox_exporter_modules.yaml
    blackbox_targets:
    - name: icmp_google
      address: 8.8.8.8
      module: icmp_ipv4
    - name: icmp_cloudflare
      address: 1.1.1.1
      module: icmp_ipv4
    - name: http_google
      address: https://www.google.com
      module: http_2xx_ipv4
    - name: http_cloudflare
      address: https://www.cloudflare.com
      module: http_2xx_ipv4
    probe_timeout_offset: 0.5
```
