### ISSUE TITLE
agent gets into bad state and drops metrics

### ISSUE THREAD

**Issue by nicklan** [grafana/agent#248]
We've noticed our agents can get into a state where they start dropping a majority of the metrics they scrape. Associated logs are:

```
ts=2020-11-06T19:49:08.929711874Z caller=dedupe.go:112 agent=prometheus instance=5f32452cd0442efde5c553cc47441659 component=remote level=info remote_name=5f3245-25d49b url=http://localhost:9900/api/v1/prom/remote/write msg="Dropped sample for series that was not explicitly dropped via relabelling" ref=1423202
ts=2020-11-06T19:49:08.929752731Z caller=dedupe.go:112 agent=prometheus instance=5f32452cd0442efde5c553cc47441659 component=remote level=info remote_name=5f3245-25d49b url=http://localhost:9900/api/v1/prom/remote/write msg="Dropped sample for series that was not explicitly dropped via relabelling" ref=1423203
ts=2020-11-06T19:49:08.929791189Z caller=dedupe.go:112 agent=prometheus instance=5f32452cd0442efde5c553cc47441659 component=remote level=info remote_name=5f3245-25d49b url=http://localhost:9900/api/v1/prom/remote/write msg="Dropped sample for series that was not explicitly dropped via relabelling" ref=1423204
ts=2020-11-06T19:49:08.929834035Z caller=dedupe.go:112 agent=prometheus instance=5f32452cd0442efde5c553cc47441659 component=remote level=info remote_name=5f3245-25d49b url=http://localhost:9900/api/v1/prom/remote/write msg="Dropped sample for series that was not explicitly dropped via relabelling" ref=1423205
ts=2020-11-06T19:49:08.929871078Z caller=dedupe.go:112 agent=prometheus instance=5f32452cd0442efde5c553cc47441659 component=remote level=info remote_name=5f3245-25d49b url=http://localhost:9900/api/v1/prom/remote/write msg="Dropped sample for series that was not explicitly dropped via relabelling" ref=1423206
ts=2020-11-06T19:49:08.929920881Z caller=dedupe.go:112 agent=prometheus instance=5f32452cd0442efde5c553cc47441659 component=remote level=info remote_name=5f3245-25d49b url=http://localhost:9900/api/v1/prom/remote/write msg="Dropped sample for series that was not explicitly dropped via relabelling" ref=1423207
```

over and over and over (like 10s per second)

Restarting the agent immediately fixes the issue with no change in the targets or metrics it's scraping, so I do suspect an internal issue here.

Please let me know if there are additional details that would be helpful, thanks.

**Comment by rfratto** [comment]
Hi, sorry you're running into this; it looks like this would happen if the Agent were to incorrectly remove a series from the WAL while it still exists. 

Can you share your Agent config and the number of active series/sample throughput the Agent is seeing?

You can find the active series with `agent_wal_storage_active_series` and the sample throughput with the rate of `agent_wal_samples_appended_total`.

**Comment by nicklan** [comment]
Thanks for the reply.

agent_wal_storage_active_series is about 750k, which is pretty high i realize. agent_wal_samples_appended_total is about 25k/sec

the config is quite complex. Here's some of it, minus the actual scrape jobs:

```
prometheus:
  global:
    scrape_interval: 30s
    scrape_timeout: 20s
    external_labels:
      [snip]
  configs:
    - name: agent
      host_filter: false
      remote_write:
        - url: "http://localhost:9900/api/v1/prom/remote/write"
          remote_timeout: 30s
          queue_config:
            capacity: 10240 # default = 500
            max_shards: 200 # default = 1000
            min_shards: 10 # default = 1
            max_samples_per_send: 2000 # default = 100
            batch_send_deadline: 60s # default = 5s
            min_backoff: 100ms # default = 30ms
            max_backoff: 10s # default = 100ms
      scrape_configs:
...
```

Then we have a number of scrape configs. If there's something in particular that would be interesting there lmk.
