### ISSUE TITLE
Routing Processor

### ISSUE THREAD

**Issue by saboco** [grafana/agent#2531]
OTel Collector supports a kind of processor that helps route traces to different exporters.
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/routingprocessor

Would it be possible to add that to Grafana Agent.
The use case I imagine is routing the traces to different tenancies of tempo.

If I configure the application to have a `X-Tenant` attribute:

```csharp
 var tracerProviderBuilder = Sdk.CreateTracerProviderBuilder()
                    .SetResourceBuilder(ResourceBuilder.CreateDefault()
                        .AddService("OtelTest")
                        .AddAttributes(new []
                        {
                            new KeyValuePair<string,object>("X-Tenant", "tenant2")
                        }))
                        .AddOtlpExporter();
```

The spans will have this attribute, but as far as I know that won't be used by tempo to define the tenancy.
So we would have to configure several exporters each one with its `X-Scope-OrgID` header.

```yaml
processors:
  routing:
    from_attribute: X-Tenant
    default_exporters:
    - tempo
    table:
    - value: tenant2
      exporters: [tempo/tenant2]
exporters:
  tempo:
    endpoint: localhost:4317
    headers:
        x-scope-orgid: tenant1
  tempo/tenant2:
    endpoint: localhost:4317
    headers:
        x-scope-orgid: tenant2
```
