### ISSUE TITLE
Feature Request: Extended authentication support for proxy_write

### ISSUE THREAD

**Issue by metzgertie** [grafana/agent#2556]
This is a followup on #2051. Currently there is no simple way of doing a http-basic-auth on the proxy, which makes the whole thing hard to debug.

To simplify the proxy authentication the optional properties `username` and `password` should be added to the remote_write proxy_url feature. I created prometheus/prometheus/issues/11626 for the upstream support. I'm no fan of forking or patch maintenance, so I would like to have it in the future. If I have time I could implement it myself. 

```yaml
proxy_url: https://some-proxy.internal.net
  # optional
  username: $proxy_user
  password: $proxy_password
```

Thanks again for all your help.
