### ISSUE TITLE
Unable to enable "agent" integration in integrations-next

### ISSUE THREAD

**Issue by danmaasrbx** [grafana/agent#2618]
Hi folks - in the legacy Grafana Agent config format, we're using:

```
integrations:
  agent:
    enabled: true
```

in order to turn on the built-in agent metrics. However, with `--enable-features=integrations-next`, that syntax is now rejected with "unmarshal errors: field enabled not found in type agent.Config".

We've also tried using "enable: true" instead of "enabled: true", with same result.

Leaving the "agent:" block completely empty lets Grafana Agent start up, but then we aren't seeing the metrics we expect from that integration, so we assume it needs to be turned on somehow.

The key metric we need to collect is `net_conntrack_dialer_conn_failed_total` which alerts us when Grafana Agent is failing to scrape its other local scrape targets. This metric has been super valuable in tracking down configuration and network errors. (if this is coming from somewhere other than the "agent" integration, please let us know how to turn it on :).

**Comment by tpaschalis** [comment]
Hey there Dan! 👋 

Thanks for the report. I can reproduce the behavior and looks like you're right, an empty `agent:` block will not start the Agent integration.

For now, to work around that issue you can supply at least an empty object to the config like `agent: {}`, which will initialize everything with their default values. Doing that with a config as the following lets me access the Agent's internal metrics such as `net_conntrack_dialer_conn_failed_total`.

```
server:
  log_level: debug

metrics:
  configs:
    - name: default
      remote_write:
      - url: <url>
        basic_auth:
          username: <user>
          password: <pass>

integrations:
  agent: {}
```

The `integrations-next` flag means that the integrations will be auto-scraped and try to send data to the metrics config named `default`. If you want to override the location the data will be sent to, you can use the following snippet to do so.
```
integrations:
  metrics:
    autoscrape: 
      enable: true
      metrics_instance: <name-of-metrics-config-instance>
```
