### ISSUE TITLE
Flow: add automatically watching & reloading config file

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2691]
It's typical to deploy Grafana Agent on Kubernetes with a sidecar container to watch for changes to the config file and automatically invoke the `/-/reload` endpoint when it changes.

It'd be great to incorporate this directly into the agent, which would be useful on platforms that don't have the sidecar container (e.g., Raspberry Pi). 

I imagine auto-reloading would be enabled by default, but would support being disabled by a flag.

**Comment by sbhrule15** [comment]
Is this available for the taking? Feel free to assign me if so 😃

**Comment by rfratto** [comment]
@sbhrule15 It is! I assigned the issue to you :) Let us know if you need any help!

**Comment by sbhrule15** [comment]
@rfratto given the name of the issue, I only added this to Flow, but let me know if you meant for this to be agent wide and I'll be more than happy to add in the additional components!

**Comment by tunguyen9889** [comment]
Hi folks, is it possible to enable the auto reload for Static mode, too? I'm using the [Remote Configuration](https://grafana.com/docs/agent/latest/static/configuration/#remote-configuration-experimental) feature, it would be great if we can reload the agent whenever the remote config file changed.

**Comment by rfratto** [comment]
Removing the assignment for now since #3991 seems abandoned.

**Comment by dwalker-sabiogroup** [comment]
The content of this issue mention _reloading config file_ only.  The [run](https://grafana.com/docs/agent/latest/flow/reference/cli/run/) command also supports loading files from a directory

> If you give the PATH_NAME argument a directory path, Grafana Agent Flow will find *.river files (ignoring nested directories) and load them as a single configuration source.

Supporting automatic reloading of the agent based on the contents of a directory would enable the use of [k8s-sidecar](https://github.com/kiwigrid/k8s-sidecar) when deployed in kubernetes with the config being created from configmaps.

This would align with the grafana dashboard/datasource sidecar approach e.g.

```yaml
env:
  - name: METHOD
    value: WATCH
  - name: LABEL
    value: grafana_datasource
  - name: LABEL_VALUE
    value: "1"
  - name: FOLDER
    value: /etc/grafana/provisioning/datasources
  - name: RESOURCE
    value: both
  - name: REQ_USERNAME
    valueFrom:
      secretKeyRef:
        key: admin-user
        name: kube-prometheus-stack-grafana
  - name: REQ_PASSWORD
    valueFrom:
      secretKeyRef:
        key: admin-password
        name: kube-prometheus-stack-grafana
  - name: REQ_URL
    value: http://localhost:3000/api/admin/provisioning/datasources/reload
  - name: REQ_METHOD
    value: POST
image: quay.io/kiwigrid/k8s-sidecar:1.25.2
name: grafana-sc-datasources
volumeMounts:
  - mountPath: /etc/grafana/provisioning/datasources
    name: sc-datasources-volume
```
