### ISSUE TITLE
PodLogs: support static_labels stage

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2728]
The PodLogs CRD is missing support for Promtail's [static_labels stage](https://grafana.com/docs/loki/latest/clients/promtail/stages/static_labels/).

**Comment by tpaschalis** [comment]
IIRC for now, a workaround would be to use a [`template` stage](https://grafana.com/docs/loki/latest/clients/promtail/stages/template/) to prepopulate the keys in the shared extracted map and then use a [`labels` stage](https://grafana.com/docs/loki/latest/clients/promtail/stages/labels/) to set them on the log entry.

```
- template:
    source: myenv
    template: 'dev'
- labels:
    env: myenv
```
