### ISSUE TITLE
Adding promtail static_config section to logs config breaks sending

### ISSUE THREAD

**Issue by MaxDiOrio** [grafana/agent#2748]
My goal is to add a static label to all logs sent by the Grafana Agent using the Windows Exporter Integration.  I added a static_config section to each job, and added a labels section with my label I want added.  According to the documentation, this should work - however after restarting the grafana agent, I no longer receive logs in Loki, and there are no errors from the agent.

I dosee the following difference in the Grafana Agent log entries, which leads me to believe that it should be working.   

Config file with static_config sections:
level=info component=logs logs_config=integrations msg="no path for target" labels="{__address__=\"localhost\", environment=\"infrastructure\"}"

It would be nice if both prometheus and promtail would abide by the integrations: labels: section and add the labels to both, or have a global config value for labels that would apply to everything being sent.

```
integrations:
  labels:
    environment: infrastructure
  prometheus_remote_write:
  - url: http://mimir.domain.cloud/api/v1/push
  windows_exporter:
    enabled: true

logs:
  configs:
  - clients:
    - url: https://loki.domain.cloud/loki/api/v1/push
    name: integrations
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
    - job_name: integrations/windows-exporter-application
      static_configs:
      - labels:
          environment: infrastructure
      pipeline_stages:
      - json:
          expressions:
            source: source
      - labels:
          source: 
      relabel_configs:
      - source_labels:
        - agent_hostname
        target_label: temp_agent_hostname
      - source_labels:
        - computer
        target_label: agent_hostname
      windows_events:
        bookmark_path: C:\Users\user\AppData\Roaming\bookmark-application.xml
        eventlog_name: Application
        labels:
          job: integrations/windows_exporter
        use_incoming_timestamp: true
        xpath_query: '*'
    - job_name: integrations/windows-exporter-system
      static_configs:
      - labels:
          environment: infrastructure
      pipeline_stages:
      - json:
          expressions:
            source: source
      - labels:
          source: 
      relabel_configs:
      - source_labels:
        - computer
        target_label: agent_hostname
      windows_events:
        bookmark_path: C:\Users\user\AppData\Roaming\bookmark-system.xml
        eventlog_name: System
        labels:
          job: integrations/windows_exporter
        use_incoming_timestamp: true
        xpath_query: '*'
    target_config:
      sync_period: 10s
metrics:
  configs:
  - name: integrations
    remote_write:
    - url: http://mimir.domain.cloud/api/v1/push
  global:
    scrape_interval: 15s
  wal_directory: /tmp/grafana-agent-wal
```

**Comment by tpaschalis** [comment]
Hey there! The [static_configs](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#static_configs) key in Promtail (and the Agent by extension) is used to specify a static list of paths to get retrieve logs from by using the `__path__` and `__path_exclude__` keys. 

Given there's no path key provided, the Agent doesn't know how to use the static_configs key, so you get your "no path for target" log message.

> It would be nice if both prometheus and promtail would abide by the integrations: labels: section and add the labels to both, or have a global config value for labels that would apply to everything being sent.

If you want to add a specific set of labels to everything that goes through your logs pipeline, you could try using the `external_labels` key under your logs' client config. The metrics configuration also contains a similar key.

**Comment by MaxDiOrio** [comment]
OK so maybe I'm missing something according to the documentation and how the Grafana Cloud generates the config file and where stuff goes because external_labels crashes the client too.  Why isn't name first and clients and scrape config underneath according to the hierarchy?  

Agent Documentation:
```
logs:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: varlogs
        static_configs:
          - targets: [localhost]
            labels:
              job: varlogs
              __path__: /var/log/*log
    clients:
      - url: http://localhost:3100/loki/api/v1/push
```

Cloud Generated Config:

```
logs:
  configs:
  - clients:
    - url: https://lokiserver/loki/api/v1/push
    name: integrations
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
    - job_name: integrations/windows-exporter-application
      pipeline_stages:
      - json:
          expressions:
            source: source
      - labels:
          source: 
      relabel_configs:
      - source_labels:
        - agent_hostname
        target_label: temp_agent_hostname
      - source_labels:
        - computer
        target_label: agent_hostname
      windows_events:
        bookmark_path: C:\Users\user\AppData\Roaming\bookmark-application.xml
        eventlog_name: Application
        labels:
          job: integrations/windows_exporter
        use_incoming_timestamp: true
        xpath_query: '*'
    - job_name: integrations/windows-exporter-system
      pipeline_stages:
      - json:
          expressions:
            source: source
      - labels:
          source: 
      relabel_configs:
      - source_labels:
        - computer
        target_label: agent_hostname
      windows_events:
        bookmark_path: C:\Users\user\AppData\Roaming\bookmark-system.xml
        eventlog_name: System
        labels:
          job: integrations/windows_exporter
        use_incoming_timestamp: true
        xpath_query: '*'
    target_config:
      sync_period: 10s

```


When I add external_labels under client config as according to the documentation - it crashes the agent too:

<img width="497" alt="image" src="https://user-images.githubusercontent.com/25855524/212685264-f30e434b-70e0-4e6c-b62b-38dcca2b5577.png">
