### ISSUE TITLE
Clarify docs for explore scrape_interval

### ISSUE THREAD

**Issue by samjewell** [grafana/agent#2813]
And maybe also:

~~Rename `scrape_samples_scraped` to `scrapes`~~

---

I'm trying to follow the docs here:
https://grafana.com/docs/grafana-cloud/billing-and-usage/control-prometheus-metrics-usage/changing-scrape-interval/#grafana-agent

And see the following example query:
```sql
count_over_time(scrape_samples_scraped[1m])
```

I'm trying to understand what the query is doing

Although we aren't always very clear, and sometimes we are ambiguous, in general the DPM acronym is used to mean the following things:
- "DPM" => 
   > The number of data points per minute (DPM), also at the 95th percentile
   from [here](https://grafana.com/docs/grafana-cloud/billing-and-usage/active-series-and-dpm/#billing-calculations). ie. the total count of datapoints
- "DPM per active series"
   > Grafana Cloud Pro includes a default resolution (included DPM) of 1 DPM per active series
   From [here](https://grafana.com/docs/grafana-cloud/billing-and-usage/active-series-and-dpm/#data-points-per-minute). ie. the datapoints **per series**, averaged

The [Agent docs here](https://grafana.com/docs/grafana-cloud/billing-and-usage/control-prometheus-metrics-usage/changing-scrape-interval/#grafana-agent) are too ambiguous and unclear. Indeed they may not be talking about **either** of the above!

~~Indeed maybe even the metric name itself is wrong.~~

~~When I read a metric named as `…_samples_scraped` I expect that to count **all** the samples (ie. datapoints) scraped. But when I run the suggested query, I can see results which are integer values such as `1, 2, 3, 4, 8, 12` etc. So interpreting the results it appears that the values for this query are actually "DPM per series, average". And the underlying metric itself should be named as `…_scrapes` and not `…_samples_scraped`.~~

**Comment by rfratto** [comment]
Technically the metrics should end in `_total` since it's a counter (probably something like `scraper_scraped_samples_total`), but the metric comes from Prometheus so we don't have a lot of agency to change it. 

I'm interested in if this is something we can clarify just on the documentation side without having to rename the metric.

**Comment by samjewell** [comment]
> but the metric comes from Prometheus

If it comes from Prometheus, can it also be used by customers/people who are shipping metrics to Grafana Cloud through Prometheus instead of the Agent?
ie. would the same approach also work in this section:
https://grafana.com/docs/grafana-cloud/billing-and-usage/control-prometheus-metrics-usage/changing-scrape-interval/#prometheus

**Comment by samjewell** [comment]
Ok I've confirmed that this is present in Prometheus as well as the agent. So I plan to update this section:
https://grafana.com/docs/grafana-cloud/billing-and-usage/control-prometheus-metrics-usage/changing-scrape-interval/#prometheus
to match this section:
https://grafana.com/docs/grafana-cloud/billing-and-usage/control-prometheus-metrics-usage/changing-scrape-interval/#grafana-agent
Or rather, to just have one section.

Thanks again for your reply here @rfratto - it should make our docs far simpler, and there's a way we can make the Billing/Usage dashboard more useful too, by providing a link directly to the explore with this query populated. Cheers.

---

If anyone is interested, I confirmed it as follows:

Got this output:
<img width="1427" alt="Screenshot 2023-01-24 at 15 59 44" src="https://user-images.githubusercontent.com/2903904/214344621-1693983f-5a2a-4d1a-a7b7-43cfea2750d4.png">

When I ran three instances of Prometheus locally, the last of which with this config file:
```yaml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "this new prom"
    scrape_interval: 30s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets:
          - "localhost:9092"
  
  - job_name: "old proms"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets:
          - "localhost:9090"
          - "localhost:9091"
```
