### ISSUE TITLE
Tracing/Jaeger: No longer listening on remote sampling port 5778

### ISSUE THREAD

**Issue by simonswine** [grafana/agent#2911]
I have hit a problem with using remote sampling through Grafana Agent.

This is roughly my config (single replica stateful set of Grafana Agent):

```yaml
kind: ConfigMap
apiVersion: v1
data:
  agent.yaml: |
    server:
        log_level: debug
    traces:
        configs:
            - name: kubernetes-traces
              receivers:
                jaeger:
                    protocols:
                        grpc: null
                        thrift_binary: null
                        thrift_compact: null
                        thrift_http: null
                    remote_sampling:
                        strategy_file: /etc/agent/strategy.json
                        tls:
                            insecure: true
              remote_write:
                - endpoint: tempo.monitoring.svc.cluster.local:4317
                  insecure: true
                  retry_on_failure:
                    enabled: true
              scrape_configs:
                - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
                  job_name: kubernetes-pods
                  kubernetes_sd_configs:
                    - role: pod
                  relabel_configs:
                    - action: replace
                      source_labels:
                        - __meta_kubernetes_namespace
                      target_label: namespace
                    - action: replace
                      source_labels:
                        - __meta_kubernetes_pod_name
                      target_label: pod
                    - action: replace
                      source_labels:
                        - __meta_kubernetes_pod_container_name
                      target_label: container
                  tls_config:
                    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                    insecure_skip_verify: false
  strategy.json: '{"default_strategy":{"param":1,"type":"probabilistic"}}'
[...]
```

When using Grafana Agent v0.28.1 (or earlier), everything works as expected and the remote sampling is listening on port 5778. Once I am upgrading to anything later than v0.29.0, Grafana Agent no longer listens to port 5778.
