### ISSUE TITLE
Grafana Agent v0.31.0 failing with tail_sampling config

### ISSUE THREAD

**Issue by ErgoPr0xy** [grafana/agent#2920]
Hi, 

I am trying to set up traces again after upgrading to v0.31.0

This is what I am setting (changed for v0.24.0 following the upgrade guide), I also tried removing `- type: probabilistic` as suggested in another issue experiencing a similar problem --> https://github.com/grafana/agent/issues/1837

```
tail_sampling:
  policies:
  - type: probabilistic
    probabilistic:
      sampling_percentage: 15

```
No matter what config I use/change it to - I always get a different error. I've switched to the below for now as a workaround but it is not ideal

```
tail_sampling:
  policies:
  - type: always_sample
```

this works without issue and the agent starts fine

Even if I follow how this is configured from the upstream config I run into the same issue. 

This worked from v0.24.0 to v0.29.0 and I don't see anything related to it in the release notes or upgrade guide. 

Thanks

**Comment by rfratto** [comment]
What was the version of the agent you were using before v0.31.0? 

> I always get a different error

What is the error message you get?

**Comment by ErgoPr0xy** [comment]
> What was the version of the agent you were using before v0.31.0?
> 
> > I always get a different error
> 
> What is the error message you get?


Started on v0.22.0 --> v0.24.0 --> v0.29.0 and now on v0.31.0

Full error:
```
caller=main.go:68 level=error msg="error creating the agent server entrypoint" 
err="failed to create tracing instance example-tracing-instance: failed to create pipeline: 
failed to load otelConfig from agent traces config: malformed sampling policy"

```

**Comment by tpaschalis** [comment]
Could you please provide the full configuration that's causing the error after redacting any secrets and check for malformed indentation?

The following configuration starts the Agent fine for me with your first sampling config snippet:

```yaml
server:
  log_level: "debug"

traces:
  configs:
    - name: "my-traces-instance"
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317

      tail_sampling:
        policies:
        - type: probabilistic
          probabilistic:
            sampling_percentage: 15

      remote_write:
      - endpoint: "http://tempo/url"
        basic_auth:
          username: "user"
          password: "pass"
```
