### ISSUE TITLE
Flow proposal: `remote.kubernetes.configmap` and `remote.kubernetes.secret` 

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2976]
To support people who wish to migrate off of Grafana Agent Operator onto Flow, we can add native support for components to read values from ConfigMaps and Secrets. 

## remote.kubernetes.configmap 

`remote.kubernetes.configmap` will watch a specific ConfigMap in Kubernetes, exporting all keys within the ConfigMap:

```river 
remote.kubernetes.configmap "example" {
  namespace = "CONFIGMAP_NAMESPACE"
  name      = "CONFIGMAP_NAME"

  client {
    // Omitted: Kubernetes client settings 
  }
}
```

`remote.kubernetes.configmap` exports a value called `data` which is a map of data fields. 

For example, for the given ConfigMap:

```yaml
apiVersion: v1 
kind: ConfigMap 
metadata:
  namespace: default
  name: example-configmap
data:
  foo: bar
  hello: world
``` 

the `data` export would be an object matching:

```river 
{
  foo   = "bar",
  hello = "world",
}
```

## remote.kubernetes.secret 

`remote.kubernetes.secret` will watch a specific Secret in Kubernetes, exporting all keys within the Secret:

```river 
remote.kubernetes.secret "example" {
  namespace = "SECRET_NAMESPACE"
  name      = "SECRET_NAME"

  client {
    // Omitted: Kubernetes client settings 
  }
}
```

`remote.kubernetes.secret` exports a value called `data` which is a map of data fields. base64 values retrieved from the Kubernetes API are decoded prior to exporting. Each value in the exported `data` value is a [secret](https://grafana.com/docs/agent/latest/flow/config-language/expressions/types_and_values/#secrets).

For example, for the given Secret:

```yaml
apiVersion: v1 
kind: Secret 
metadata:
  namespace: default
  name: example-secret
data:
  foo: YmFy       # base64 encoding of "bar" 
  hello: d29ybGQ= # base64 encoding of "world"  
``` 

the `data` export would be an object matching:

```river 
{
  foo   = secret /* "bar" */,
  hello = secret /* "world" */,
}
```

The exported values in the map are [secrets](https://grafana.com/docs/agent/latest/flow/config-language/expressions/types_and_values/#secrets), allowing them to only be passed to other arguments expecting secrets, and may not be implicitly converted back to strings.
