### ISSUE TITLE
Operator: Reconciliation error when setting tlsConfig on Probe

### ISSUE THREAD

**Issue by supergillis** [grafana/agent#3002]
Grafana Operator fails to reconcile when setting `tlsConfig` on a `Probe` instance.

# Error

```
level=error ts=2023-02-15T10:29:31.887632294Z controller=grafanaagent controllerGroup=monitoring.grafana.com controllerKind=GrafanaAgent GrafanaAgent="unsupported value type" namespace=monitoring name=grafana-default-agent reconcileID=672370ea-24af-48c6-95a8-b578c98cacd4 msg="error during reconciling" err="unable to build config: RUNTIME ERROR: Field does not exist: CAFile
    component/metrics/tls_config.libsonnet:14:37-50    thunk from <thunk <unsafe> from <object <anonymous>>>
    ext/optionals.libsonnet:5:8-13    function <anonymous>
    component/metrics/tls_config.libsonnet:14:20-51    thunk <unsafe> from <object <anonymous>>
    component/metrics/tls_config.libsonnet:15:8-14    object <anonymous>
    Field \"ca_file\"    
    Field \"tls_config\"    
    Array element 20    
    Field \"scrape_configs\"    
    Array element 0    
    Field \"configs\"    
    
Field \"metrics\"    
    ext/optionals.libsonnet:40:17-50    function <anonymous>
    agent-metrics.libsonnet:(27:28)-(64:3)    thunk from <function <anonymous>>
    ext/marshal.libsonnet:3:44-50    thunk from <function <anonymous>>

    ext/marshal.libsonnet:3:18-51    function <anonymous>
    agent-metrics.libsonnet:(27:15)-(64:4)    function <anonymous>
    Top-level function call"
```

# Reproducing

Create a `Probe` instance with `tlsConfig`.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: postgres
  namespace: monitoring
spec:
  basicAuth:
    password:
      key: password
      name: postgres-probe
    username:
      key: username
      name: postgres-probe
  interval: 30s
  jobName: postgres
  metricRelabelings:
  - action: replace
    sourceLabels:
    - __address__
    targetLabel: target
  prober:
    path: /metrics
    scheme: https
    url: localhost
  targets:
    staticConfig:
      relabelingConfigs:
      - action: replace
        sourceLabels:
        - __param_target
        targetLabel: instance
      - action: replace
        sourceLabels:
        - __param_target
        targetLabel: __address__
      static:
      - db.a.timescaledb.io:9273
  tlsConfig:
    insecureSkipVerify: true
```
