### ISSUE TITLE
A question about how to integrate Grafana Agent with any external metrics storage system

### ISSUE THREAD

**Issue by amseager** [grafana/agent#3015]
This is more a question about the documentation.
I think it's not quite clear of how the metrics that have been polled by Grafana Agent are delivered to the external metrics storage (Prometheus/Grafana Mimir/Grafana Cloud Metrics). I can only see the "pushing" approach, so you can use `remote_write` in this case, and your external metrics storage should be set up as a remote-write receiver. However, I've seen a lot of articles in which this was considered a bad practice - it was advised to always use the "polling" method unless you can't poll from the metrics source (which is not relevant to Grafana Agent that has an API for this). I believe this was even mentioned in the Prometheus docs.
So, what's the right way to do this? If it depends on your preference or the Grafana Agent doesn't support some ways at all (which can be intended or not), I think it should be mentioned in the readme (in form of a comparison table of these strategies or smth like that).

**Comment by rfratto** [comment]
Hello! 

Grafana Agent does support pulling, just in the way Prometheus does: you use scrape_configs to pull metrics from targets:

```yaml
server:
  log_level: info

metrics:
  global:
    scrape_interval: 1m
  configs:
    - name: test
      host_filter: false
      scrape_configs:
        - job_name: local_scrape
          static_configs:
            - targets: ['127.0.0.1:12345']
              labels:
                cluster: 'localhost'
      remote_write:
        - url: http://localhost:9009/api/prom/push
```

remote_write forwards pulled metrics from the agent to a remote system. 

The pulling/pushing debate normally refers to how telemetry data from an application/system under observation is collected. Pulling means that an agent, collector, or a database reaches out to the application and requests telemetry data from it. Pushing means that the application pushes its telemetry data directly to an agent, collector, or database. 

remote_write sits outside of that concept; it's about delivering the pulled metrics after they've been retrieved. 

The Prometheus ecosystem is built around pull-based metrics. There's been a bit of resurgence recently in pushed-based metrics, which is being re-popularized by the OpenTelemetry project. 

Given the popularity of both OpenTelemetry and Prometheus, I don't think it's possible to say if either the pull or push method is the best practice; it depends on your environment, and which tradeoffs you're willing to make.

**Comment by amseager** [comment]
Hello @rfratto,
Very big thanks for the explanation, that's exactly what I wanted to know. 

To conclude this topic, a small question if you don't mind (I think this is the only thing which left uncovered): is it possible for the Grafana Agent to receive metrics over grpc/http that are pushed by e.g. java app with the OTLP instrumentation agent, as we can do in case of collecting traces?

```
traces:
  configs:
  - name: default
    receivers:
      otlp:
        protocols:
          grpc:
          http:
```
Looks like this is not possible to have the same block under the `metrics:` section. The example in the docs shows only how to configure it via the scraping apps by Grafana Agent itself (the "opposite" way).
