### ISSUE TITLE
`grafana-agent-logs` DaemonSet continuously recreates new pods.

### ISSUE THREAD

**Issue by clouedoc** [grafana/agent#3032]
Hi,

I've deployed a GrafanaAgent using the Grafana Agent Operator.

It creates tons of grafana-agent-logs pods as shown below:

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/13921610/220180393-92f19042-6e6f-4f50-b221-bd85aab172aa.png">

These are controlled by the `grafana-agent-logs` daemonset. In turn, this daemonset is controlled by the `grafana-agent` GrafanaAgent.

I am unsure how to troubleshoot this as pods keep getting recreated and it consumes resources on the UI side (I cannot even see the logs of the pods that are up for 1 second and die as Lens and ArgoCD become unresponsive).
## Versions

| Name | Version
| - | - |
| Grafana Agent Operator | 0.2.12 |

## Configuration 
Here is my configuration:

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-agent-operator
  namespace: argocd
spec:
  project: infra
  source:
    chart: grafana-agent-operator
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.2.12
    helm:
      releaseName: grafana-agent-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
---
apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: grafana-agent
  namespace: grafana
  labels:
    app: grafana-agent
spec:
  image: grafana/agent:v0.31.3
  logLevel: info
  serviceAccountName: grafana-agent
  metrics:
    instanceNamespaceSelector: {}
    instanceSelector:
      matchLabels:
        agent: grafana-agent-metrics
    externalLabels:
      cluster: tagnet
  logs:
    instanceNamespaceSelector: {}
    instanceSelector:
      matchLabels:
        agent: grafana-agent-logs
```
