### ISSUE TITLE
Pointless Windows Event logged every minute

### ISSUE THREAD

**Issue by bboreham** [grafana/agent#3053]
These events, saying `level=info agent=prometheus component=cluster msg="reshard timer ticked, scheduling refresh"`, are not useful:

<img width="498" alt="image" src="https://user-images.githubusercontent.com/8125524/220584987-59556014-1490-4e3c-bed2-a76af8a179ee.png">

All the more so since I don't have any remote-write configured:

```
server:
  http_listen_port: 12345
metrics:
  wal_directory: C:\ProgramData\grafana-agent-wal
  global:
    scrape_interval: 1m
  configs:
    - name: integrations
integrations:
  windows_exporter:
    enabled: true
```
