### ISSUE TITLE
cadvisor "Cannot detect current cgroup on cgroup v2"

### ISSUE THREAD

**Issue by stefanpoensgen** [grafana/agent#3108]
I'm currently testing the agent to gather all my metrics and logs. At first it looks to work but the cadvisor part is reporting "Cannot detect current cgroup on cgroup v2"
Any tipps how to solve this?

docker-compose.yml looks like
```
    agent:
        image: grafana/agent:latest
        restart: always
        volumes:
            - ./agent/config:/etc/agent-config
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/:/var/lib/docker:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/host/root:ro
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
        entrypoint:
            - /bin/agent
            - -server.http.address=0.0.0.0:12345
            - -config.file=/etc/agent-config/agent.yml
            - -metrics.wal-directory=/tmp/agent/wal
            - -config.expand-env
            - -config.enable-read-api
        devices:
            - /dev/kmsg:/dev/kmsg
        privileged: true
```

agent.yml looks like
```
integrations:
  cadvisor:
    docker_only: true
    enabled: true
    instance: localhost:9090
    relabel_configs:
      - action: replace
        replacement: integrations/docker
        target_label: job


logs:
  configs:
    - clients:
        - url: http://10.0.0.2:3100/loki/api/v1/push
      name: integrations
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - docker_sd_configs:
            - host: unix:///var/run/docker.sock
              refresh_interval: 5s
          job_name: integrations/docker
          relabel_configs:
            - action: replace
              replacement: integrations/docker
              source_labels:
                - __meta_docker_container_id
              target_label: job
            - action: replace
              replacement: localhost:9090
              source_labels:
                - __meta_docker_container_id
              target_label: instance
            - regex: /(.*)
              source_labels:
                - __meta_docker_container_name
              target_label: container
            - source_labels:
                - __meta_docker_container_log_stream
              target_label: stream
```
