### ISSUE TITLE
Flow: prometheus.exporter.unix not compatible with Grafana Cloud integration

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#3180]
Out of the box, you can't use `prometheus.exporter.unix` with the Grafana Cloud integration, because the Grafana Cloud integration expects the `job` label to be set to `integrations/node_exporter`.

Additionally, the `instance` label is different. The `instance` label used to be set to the agent's hostname and listen port, but it's been changed to the component name, which is less useful when there's a ton of running agents. 

To get it to work, I had to stick a `discovery.relabel` component in between the exporter and scraping:

```river 
prometheus.exporter.unix {
	disable_collectors = ["mdadm"]
}

// We need to change the output of prometheus.exporter.unix to be 
// compatible with the node_exporter integration:
//
// * Change the job label to integrations/node_exporter.
// * Change the instance label to be HOSTNAME:LISTEN_PORT.
discovery.relabel "node_exporter" {
	targets = prometheus.exporter.unix.targets

	rule {
		action       = "replace"
		target_label = "job"
		replacement  = "integrations/node_exporter"
	}

	rule {
		action       = "replace"
		target_label = "__hostname__"
		replacement  = "{{ ansible_facts['nodename'] }}"
	}

	rule {
		action        = "replace"
		source_labels = ["__address__"]
		target_label  = "__port__"
		regex         = ".*:(.*)"
		replacement   = "$1"
	}

	rule {
		action        = "replace"
		source_labels = ["__hostname__", "__port__"]
		separator     = ":"
		target_label  = "instance"
	}
}

prometheus.scrape "default" {
	targets    = discovery.relabel.node_exporter.output
	forward_to = [prometheus.remote_write.grafanacloud.receiver]

	scrape_interval = "60s"
}
```

Ideally the `discovery.relabel` component isn't necessary for remapping the data to what it used to be.

**Comment by marctc** [comment]
> Out of the box, you can't use `prometheus.exporter.unix` with the Grafana Cloud integration, because the Grafana Cloud integration expects the `job` label to be set to `integrations/node_exporter`.

Is changing this not an option? I'm not oposing to the changes that you mention but just wondering if it would be easier to change Grafana Cloud Integration

**Comment by rfratto** [comment]
> Instance is not super useful as it is now. Does it even make sense for exporters to set that if it is host related information?

It's only host-related information for node_exporter. Every exporter choses a different value for the instance key. For example, the mongodb_exporter integration uses [the host of the MongoDB server](https://github.com/grafana/agent/blob/ba85be1de202df9a139b9d70f63a418a2945e258/pkg/integrations/mongodb_exporter/mongodb_exporter.go#L33-L40).

**Comment by jcreixell** [comment]
@rfratto static mode does set the `<hostname>:<port>` value for the instance label by default. However, the Grafana Cloud integration actually overrides that value and provides a custom relabel rule. This is needed to ensure that the instance label matches for both metrics and logs. See this example config snippet from as shown in Grafana Cloud instructions:

```yaml
  node_exporter:
    enabled: true
    # disable unused collectors
    disable_collectors:
      - ipvs #high cardinality on kubelet
      - btrfs
      - infiniband
      - xfs
      - zfs
    # exclude dynamic interfaces
    netclass_ignored_devices: "^(veth.*|cali.*|[a-f0-9]{15})$"
    netdev_device_exclude: "^(veth.*|cali.*|[a-f0-9]{15})$"
    # disable tmpfs
    filesystem_fs_types_exclude: "^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|tmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$"
    # drop extensive scrape statistics
    metric_relabel_configs:
    - action: drop
      regex: node_scrape_collector_.+
      source_labels: [__name__]
    relabel_configs:
    - replacement: hostname
      target_label: instance
```

Given that most integrations have a similar relabel config, I would not consider the `instance` label default to be an issue. As long as modules are used to configure such integrations (which makes sense given that the bundle metrics and logs configs together), relabel rules can always be included as part of the config (as done now).

Regarding the `job` label, this is something that can be fixed internally for Grafana Cloud, so I don't see any changes needed on the agent side, WDYT?

**Comment by jcreixell** [comment]
a counter argument would be that currently we do not set any node-specific label, which means we can't differentiate between nodes, but that's not a Grafana Cloud specific issue. We may want to set the `<host>:<port>` label then to provide a good default outside Grafana Cloud. I will see how hard would it be to implement

**Comment by jcreixell** [comment]
btw I also see that some integrations in Grafana Cloud use node exporter under the hood but override the job label via relabel configs, for example, the mac integration:

```yaml
  node_exporter:
    enabled: true
    relabel_configs:
    - replacement: $(hostname)
      source_labels: [agent_hostname]
      target_label: instance
    - replacement: "integrations/macos-node"
      source_labels: [agent_hostname]
      target_label: job
```
