### ISSUE TITLE
Flow: `loki.source.journal` missing labels attribute

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#3182]
`loki.source.journal` is [missing](https://grafana.com/docs/agent/v0.32/flow/reference/components/loki.source.journal/) an attribute for `labels`, which is available on the [Promtail source](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#journal):

```yaml
journal:
  labels:
    label1: value1 
    ...
```
