### ISSUE TITLE
Docs feedback: /configuration/create-config-file.md

### ISSUE THREAD

**Issue by romangallego** [grafana/agent#3246]
It would be great to have in the documentation 
**How to add to prometheus instaces for remote_write?**
(to write in 2 destinations.)
The following config does not work.

```
    prometheus:
      wal_directory: /tmp/prometheus_wal
      global:
        remote_write:
            - url: "https://the-urlONE/api/v1/push"
            - url: "https://the-urlTWO/api/v1/push"
      configs:
        - name: default
          scrape_configs:
            - job_name: "thejob"
              honor_timestamps: true
              follow_redirects: true
              metrics_path: "/serverscraped/prometheus"
              static_configs:
                - targets: [192.168.1.5]
                  labels:
                    cluster: "thecluster
                    namespace: "k8snspace"
```

**Comment by tpaschalis** [comment]
Hey there, thanks for reaching out 👋 

The [configuration/create-config-file](https://grafana.com/docs/agent/latest/configuration/create-config-file/) page contains a template for people migrating from Prometheus config.

There, we have a `# PASTE remote_write SECTION HERE` section, where multiple remote_writes can be configured. The global remote_write serves a different purpose, to provide some defaults to all metrics instances.

```
metrics:
  global:
  # PASTE PROMETHEUS global SECTION HERE
  configs:
    - name: agent
      scrape_configs:
        # PASTE scrape_configs SECTION HERE
      remote_write:
        - url: "https://the-urlONE/api/v1/push"
        - url: "https://the-urlTWO/api/v1/push"
```

I'm closing this issue for now, but will keep an eye out for ways we can improve our documentation. Thanks again.
