### ISSUE TITLE
Grafana Agent error loading config file

### ISSUE THREAD

**Issue by duncanwraight** [grafana/agent#3269]
Hi folks

We're using the Grafana Agent Operator to run multiple Grafana Agent implementations on our cluster.

Our pods are constantly restarting:

```shell
❯ kubectl get pods
NAME                                          READY   STATUS             RESTARTS        AGE
grafana-agent-grafana-agent-logs-logs-l29nr   2/3     CrashLoopBackOff   7 (3m12s ago)   14m
grafana-agent-grafana-agent-logs-logs-zsvpq   2/3     CrashLoopBackOff   7 (2m54s ago)   14m
grafana-agent-grafana-logs-logs-jz6ls         2/3     CrashLoopBackOff   7 (3m21s ago)   14m
grafana-agent-grafana-logs-logs-kdnvm         2/3     CrashLoopBackOff   7 (2m45s ago)   14m
grafana-agent-loki-logs-logs-czm2z            2/3     CrashLoopBackOff   7 (3m15s ago)   14m
grafana-agent-metrics-0                       2/3     CrashLoopBackOff   7 (3m9s ago)    14m
grafana-agent-tempo-logs-logs-jgsvt           2/3     CrashLoopBackOff   7 (2m57s ago)   14m
grafana-agent-tempo-logs-logs-k4228           2/3     CrashLoopBackOff   7 (3m17s ago)   14m
```

`kubectl logs` on these pods doesn't look too bad:

```shell
2023-03-14T17:23:51.568641722Z caller=filetargetmanager.go:338 level=info component=logs logs_config=grafana-agent/loki-logs msg="Adding target" key="/var/log/pods/*206bceaa-69b8-4c87-bb08-9647c7af85bf/loki/*.log:{app_kubernetes_io_component=\"write\", app_kubernetes_io_instance=\"loki\", app_kubernetes_io_name=\"loki\", app_kubernetes_io_part_of=\"memberlist\", cluster=\"loki\", container=\"loki\", controller_revision_hash=\"loki-write-846857b77f\", job=\"loki/loki\", name=\"loki\", namespace=\"loki\", pod=\"loki-write-0\", statefulset_kubernetes_io_pod_name=\"loki-write-0\"}"
ts=2023-03-14T17:23:51.56957478Z caller=filetarget.go:278 level=info component=logs logs_config=grafana-agent/loki-logs msg="watching new directory" directory=/var/log/pods/loki_loki-read-0_0ae28cfd-fb60-44e1-aef6-71e9a3d01a5f/loki
ts=2023-03-14T17:23:51.570813342Z caller=log.go:168 component=logs logs_config=grafana-agent/loki-logs level=info msg="Seeked /var/log/pods/loki_loki-read-0_0ae28cfd-fb60-44e1-aef6-71e9a3d01a5f/loki/0.log - &{Offset:8305626 Whence:0}"
ts=2023-03-14T17:23:51.57012356Z caller=filetarget.go:278 level=info component=logs logs_config=grafana-agent/loki-logs msg="watching new directory" directory=/var/log/pods/loki_loki-write-0_206bceaa-69b8-4c87-bb08-9647c7af85bf/loki
ts=2023-03-14T17:23:51.570943369Z caller=log.go:168 component=logs logs_config=grafana-agent/loki-logs level=info msg="Seeked /var/log/pods/loki_loki-write-0_206bceaa-69b8-4c87-bb08-9647c7af85bf/loki/0.log - &{Offset:9195387 Whence:0}"
ts=2023-03-14T17:23:51.570980555Z caller=tailer.go:143 level=info component=logs logs_config=grafana-agent/loki-logs component=tailer msg="tail routine: started" path=/var/log/pods/loki_loki-write-0_206bceaa-69b8-4c87-bb08-9647c7af85bf/loki/0.log
ts=2023-03-14T17:23:51.571585415Z caller=tailer.go:143 level=info component=logs logs_config=grafana-agent/loki-logs component=tailer msg="tail routine: started" path=/var/log/pods/loki_loki-read-0_0ae28cfd-fb60-44e1-aef6-71e9a3d01a5f/loki/0.log
```

but if I `exec` into the pods, and `tail` the latest container log from `/var/log/containers`, I see an error about a missing config file. More info below.

Context here is...
- We have created `LogInstances` / `PodLogs` for multiple applications. These applications are created on separate node groups
- We have therefore created multiple `GrafanaAgent` resources, with different `nodeSelector` values, to ensure the agent DaemonSet pods are deployed to nodes which contain the container log files they're trying to read from
- Initially when doing this, we were seeing errors about the gRPC listener

```shell
2023-03-14T15:48:45.22477301Z stderr F ts=2023-03-14T15:48:45.224255363Z caller=main.go:69 level=error msg="error creating the agent server entrypoint" err="creating gRPC listener: listen tcp 127.0.0.1:12346: bind: address already in use"
```

- I then changed the container `args` of the `GrafanaAgent` resources. I took the default `args` from `kubectl describe ds grafana-agent-loki-logs` and added `-server.grpc.in-memory-addr=127.0.0.1:12{{ randNumeric 3 }}` resulting in:

```yaml
spec:
  containers:
   - name: "grafana-agent-{{ $monitor.name }}-logs"
     image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
     env:
      - name: AWS_SDK_LOAD_CONFIG
        value: "true"
      - name: AWS_REGION
        value: {{ $.Values.prometheus.region }}
     args:
      - -server.grpc.in-memory-addr=127.0.0.1:12{{ randNumeric 3 }}
      - -config.file=/var/lib/grafana-agent/config/agent.yml
      - -config.expand-env=true
      - -server.http.address=0.0.0.0:8080
      - -enable-features=integrations-next
```

The error I'm seeing now is: 

```shell
2023-03-14T17:24:33.49270443Z stderr F 2023/03/14 17:24:33 error loading config file /var/lib/grafana-agent/config/agent.yml: error reading config file open /var/lib/grafana-agent/config/agent.yml: no such file or directory
```

Which doesn't make any sense because if I run `cat /var/lib/grafana-agent/config/agent.yml`, I see the expected output which I believe is taken from a secret that the Operator configures:

```shell
root@grafana-agent-loki-logs-logs-czm2z:/var/log/containers# cat /var/lib/grafana-agent/config/agent.yml
logs:
    configs:
        - clients:
            - external_labels:
                cluster: grafana-agent/grafana-agent-loki-logs
              url: http://loki-write.loki.svc.cluster.local:3100/loki/api/v1/push
          name: grafana-agent/loki-logs
          scrape_configs:
            - job_name: podLogs/grafana-agent/loki-monitor
              kubernetes_sd_configs:
                - namespaces:
                    names:
                        - loki
                  role: pod
              pipeline_stages:
                - cri: {}
              relabel_configs:
                - source_labels:
                    - job
                  target_label: __tmp_prometheus_job_name
                - action: keep
                  regex: loki
                  source_labels:
                    - __meta_kubernetes_pod_label_app_kubernetes_io_name
```

I am using the `grafana/agent` image with tag `main-fd871f6`. I was originally using a previous version, 2 months old - `main-8c953cf` - but upgrading to the newer version made no difference.

Can anyone shed any light on why this might be failing? Or is there a better way to achieve what we're trying to achieve here?

**Comment by duncanwraight** [comment]
This issue can probably be closed, we have identified the problem.

Here is our `GrafanaAgent` manifest:

```yaml
kind: GrafanaAgent
metadata:
  name: "grafana-agent-{{ $monitor.name }}-logs"
  labels:
    app: "grafana-agent-{{ $monitor.name }}-logs"
spec:
  containers:
   - name: {{ include "grafana-agent.fullname" $ }}-logs
     image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
     env:
      - name: AWS_SDK_LOAD_CONFIG
        value: "true"
      - name: AWS_REGION
        value: {{ $.Values.prometheus.region }}
     args:
      - -server.grpc.in-memory-addr=agent.internal:12348
      - -config.file=/var/lib/grafana-agent/config/agent.yml
      - -config.expand-env=true
      - -server.http.address=0.0.0.0:8080
      - -server.grpc.address=0.0.0.0:12348
      - -enable-features=integrations-next
 ```

By calling the container `grafana-agent-logs`, we have essentially _added_ an additional container to the GrafanaAgent pod. It was repeatedly failing, as it didn't have the correct mounts etc. - and also explains the multiple gRPC binds.

We've renamed it to `grafana-agent`, and now we're overriding the GrafanaAgent resource's main container configuration. There is now only 2 containers in that pod (the `config-reload` and `grafana-agent` containers), instead of 3 (`config-reload`, `grafana-agent`, `grafana-agent-logs`) and the pods are `Running` as expected.

A little more documentation around the `GrafanaAgent` manifests would be super helpful, but I guess this isn't the remit of this repository.
