### ISSUE TITLE
grafana-agent-operator: Reconciler Error

### ISSUE THREAD

**Issue by luvpreetsingh** [grafana/agent#3300]
Hi,

I am using grafana-agent-operator helm chart installation. Then I am creating GrafanaAgent, MetricsInstance and ServiceMonitor objects and it starts working.

This setup is working fine on 9 of my clusters but not on 1 of my cluster.

The cluster on which this is not working is the cluster on which grafana mimir is installed. Not sure if that is related but just putting that out here.

Here is my helm file for operator,

```resources:
  limits:
    memory: 1000Mi
  requests:
    cpu: 1000m
    memory: 1000Mi
```

Here is how I install it,

```
helm install grafana-agent-operator grafana/grafana-agent-operator -n monitoring -f grafana-agent-operator.yaml
```

The operator gets installed, no issues until now.

However, in the operator logs, I get this

```
level=error ts=2023-03-17T10:37:26.041422856Z component=controller.node name=gke-monitoring-clust-prom-high-memory-d2e6a736-s4d5 namespace= msg="Reconciler error" err="failed to reconcile kubelet endpoints default/kubelet: failed to update endpoints: Operation cannot be fulfilled on endpoints \"kubelet\": the object has been modified; please apply your changes to the latest version and try again"
```

Then I launch GrafanaAgent,

```
kind: GrafanaAgent
metadata:
  name: grafana-agent
  namespace: monitoring
  labels:
    app: grafana-agent
spec:
  image: grafana/agent:v0.26.1
  logLevel: info
  serviceAccountName: grafana-agent
  metrics:
    instanceSelector:
      matchLabels:
        agent: grafana-agent-metrics
    externalLabels:
      cluster: monitoring-cluster

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-agent
rules:
  - apiGroups:
    - ""
    resources:
    - nodes
    - nodes/proxy
    - nodes/metrics
    - services
    - endpoints
    - pods
    - events
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch
  - nonResourceURLs:
    - /metrics
    - /metrics/cadvisor
    verbs:
    - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-agent
subjects:
- kind: ServiceAccount
  name: grafana-agent
  namespace: monitoring
```

After that I launch my MetricsInstance,

```
apiVersion: monitoring.grafana.com/v1alpha1
kind: MetricsInstance
metadata:
  name: primary
  namespace: monitoring
  labels:
    agent: grafana-agent-metrics
spec:
  remoteWrite:
  - url: https://mimir-nginx/api/v1/push # mimir is launched in the same namespace and this endpoint is working
    headers:
      X-Scope-OrgID: staging-kube
    basicAuth:
      username:
        name: grafana-agent-mimir-auth
        key: username
      password:
        name: grafana-agent-mimir-auth
        key: password
  serviceMonitorNamespaceSelector: {}
  podMonitorNamespaceSelector: {}
  probeNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      instance: primary
  podMonitorSelector:
    matchLabels:
      instance: primary
  probeSelector:
    matchLabels:
      instance: primary
```

After I launch GrafanaAgent and MetricsInstance, I get these operator logs,

```
level=info ts=2023-03-17T10:39:08.567546305Z component=controller.grafanaagent name=grafana-agent namespace=monitoring msg="deleting integrations Deployment" deploy=monitoring/grafana-agent-integrations-deploy
level=info ts=2023-03-17T10:39:08.567699835Z component=controller.grafanaagent name=grafana-agent namespace=monitoring msg="deleting integrations DaemonSet" ds=monitoring/grafana-agent-integrations-ds
level=info ts=2023-03-17T10:39:08.606965261Z component=controller.grafanaagent name=grafana-agent namespace=monitoring msg="reconciling grafana-agent"
level=info ts=2023-03-17T10:39:08.652961156Z component=controller.grafanaagent name=grafana-agent namespace=monitoring msg="reconciling secret" secret=grafana-agent-config
level=info ts=2023-03-17T10:39:08.660941896Z component=controller.grafanaagent name=grafana-agent namespace=monitoring msg="reconciling statefulset service" service=grafana-agent-operated
level=error ts=2023-03-17T10:39:08.720774079Z component=controller.grafanaagent name=grafana-agent namespace=monitoring msg="error during reconciling" err="failed to reconcile statefulset for shard: failed to update statefulset when creating replacement statefulset: statefulsets.apps \"grafana-agent\" already exists"
level=info ts=2023-03-17T10:39:08.720895959Z component=controller.grafanaagent name=grafana-agent namespace=monitoring msg="reconciling grafana-agent"
level=error ts=2023-03-17T10:39:08.760418235Z component=controller.grafanaagent name=grafana-agent namespace=monitoring msg="error during reconciling" err="failed to reconcile secret: failed to update service: Operation cannot be fulfilled on secrets \"grafana-agent-config\": the object has been modified; please apply your changes to the latest version and try again"
```

My grafana-agent pod gets stuck in Terminating state,

```
grafana-agent-0                                 2/2     Terminating   0             14m
```

Here is the description of the pod,

```
$ kubectl describe pod grafana-agent-0 -n monitoring
Name:                      grafana-agent-0
Namespace:                 monitoring
Priority:                  0
Node:                      gke-monitoring-clust-medium-workloads-a4160225-g8jp/10.128.63.133
Start Time:                Fri, 17 Mar 2023 16:12:25 +0530
Labels:                    app.kubernetes.io/instance=grafana-agent
                           app.kubernetes.io/managed-by=grafana-agent-operator
                           app.kubernetes.io/name=grafana-agent
                           app.kubernetes.io/version=v0.24.2
                           controller-revision-hash=grafana-agent-bc96dc79
                           grafana-agent=grafana-agent
                           operator.agent.grafana.com/name=grafana-agent
                           operator.agent.grafana.com/shard=0
                           operator.agent.grafana.com/type=metrics
                           statefulset.kubernetes.io/pod-name=grafana-agent-0
Annotations:               kubectl.kubernetes.io/default-container: grafana-agent
Status:                    Terminating (lasts <invalid>)
Termination Grace Period:  4800s
IP:                        10.64.9.246
IPs:
  IP:           10.64.9.246
Controlled By:  StatefulSet/grafana-agent
Containers:
  config-reloader:
    Container ID:  containerd://bd102e748ef54fcfdf26d1add9b12d3dc377cb7105457f7028762dc574573ff4
    Image:         quay.io/prometheus-operator/prometheus-config-reloader:v0.47.0
    Image ID:      quay.io/prometheus-operator/prometheus-config-reloader@sha256:0029252e7cf8cf38fc58795928d4e1c746b9e609432a2ee5417a9cab4633b864
    Port:          <none>
    Host Port:     <none>
    Args:
      --config-file=/var/lib/grafana-agent/config-in/agent.yml
      --config-envsubst-file=/var/lib/grafana-agent/config/agent.yml
      --watch-interval=1m
      --statefulset-ordinal-from-envvar=POD_NAME
      --reload-url=http://127.0.0.1:8080/-/reload
    State:          Running
      Started:      Fri, 17 Mar 2023 16:12:25 +0530
    Ready:          True
    Restart Count:  0
    Environment:
      POD_NAME:  grafana-agent-0 (v1:metadata.name)
      SHARD:     0
      SHARDS:    1
    Mounts:
      /var/lib/grafana-agent/config from config-out (rw)
      /var/lib/grafana-agent/config-in from config (ro)
      /var/lib/grafana-agent/data from grafana-agent-wal (rw)
      /var/lib/grafana-agent/secrets from secrets (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-tcdmb (ro)
  grafana-agent:
    Container ID:  containerd://bade2f3bb565fdba87779c67ea0830ddcd90732cc36decb5f6b765b112ee33a5
    Image:         grafana/agent:v0.26.1
    Image ID:      docker.io/grafana/agent@sha256:3af5bf1bda1b9e58ee5d6e439b6bdb55fd0add7a4362615441a675bbbda83fc9
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      -config.file=/var/lib/grafana-agent/config/agent.yml
      -config.expand-env=true
      -server.http.address=0.0.0.0:8080
    State:          Running
      Started:      Fri, 17 Mar 2023 16:12:25 +0530
    Ready:          True
    Restart Count:  0
    Readiness:      http-get http://:http-metrics/-/ready delay=0s timeout=3s period=5s #success=1 #failure=120
    Environment:
      POD_NAME:  grafana-agent-0 (v1:metadata.name)
      SHARD:     0
      SHARDS:    1
    Mounts:
      /var/lib/grafana-agent/config from config-out (rw)
      /var/lib/grafana-agent/config-in from config (ro)
      /var/lib/grafana-agent/data from grafana-agent-wal (rw)
      /var/lib/grafana-agent/secrets from secrets (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-tcdmb (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  grafana-agent-config
    Optional:    false
  config-out:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  secrets:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  grafana-agent-secrets
    Optional:    false
  grafana-agent-wal:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kube-api-access-tcdmb:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  15m   default-scheduler  Successfully assigned monitoring/grafana-agent-0 to gke-monitoring-clust-medium-workloads-a4160225-g8jp
  Normal   Pulled     15m   kubelet            Container image "quay.io/prometheus-operator/prometheus-config-reloader:v0.47.0" already present on machine
  Normal   Created    15m   kubelet            Created container config-reloader
  Normal   Started    15m   kubelet            Started container config-reloader
  Normal   Pulled     15m   kubelet            Container image "grafana/agent:v0.26.1" already present on machine
  Normal   Created    15m   kubelet            Created container grafana-agent
  Normal   Started    15m   kubelet            Started container grafana-agent
  Normal   Killing    15m   kubelet            Stopping container config-reloader
  Normal   Killing    15m   kubelet            Stopping container grafana-agent
  Warning  Unhealthy  15m   kubelet            Readiness probe failed: Get "http://10.64.9.246:8080/-/ready": dial tcp 10.64.9.246:8080: connect: connection refused
```

So, I deleted everything and then re-installed everything again. But I ran into the same issue again. I manually checked about any StatefulSet and there were not any.

I am not able to figure out what is happening and why is it happening?
