### ISSUE TITLE
Feature request: eventhandler logs as json

### ISSUE THREAD

**Issue by BitProcessor** [grafana/agent#3313]
We are currently successfully using the following integration:
```
    integrations:
      eventhandler:
        cache_path: "/etc/eventhandler/eventhandler.cache"
        logs_instance: "default"
```
Giving us the k8s events as logs in the application namespaces.
So far so good, however, it kind of interferes with our application logs, in the way that all our applications are standardised on `json` logs.

So suddenly, when querying logs with something such as `{namespace="foo"} | json` gives a json parse error because these event logs get in the way. 

Would it be possible for the eventhandler integration to output its logs in json format ? Maybe make the output format configurable?
