### ISSUE TITLE
Scraping mode: agent stuck at startup when etcd endpoint can't be resolved

### ISSUE THREAD

**Issue by cristiangreco** [grafana/agent#3333]
Agent version: v0.32.1

---

When running in scraping mode with etcd as store, if the etcd address can't be resolved the agent becomes stuck at startup after emitting just a couple of lines, e.g.

```
ts=2023-03-22T16:03:39.032615629Z caller=server.go:191 level=info msg="server listening on addresses" http=:80 grpc=127.0.0.1:12346 http_tls_enabled=false grpc_tls_enabled=false
ts=2023-03-22T16:03:39.033073588Z caller=node.go:85 level=info agent=prometheus component=cluster msg="applying config"
```

It'd be good to have more logging to figure out what is going on.

Example config:

```yaml
metrics:
    scraping_service:
        enabled: true
        kvstore:
            etcd:
                endpoints:
                    - etcd.default.svc.cluster.local:2379
            store: etcd
        lifecycler:
            ring:
                kvstore:
                    etcd:
                        endpoints:
                            - etcd.default.svc.cluster.local:2379
                    store: etcd
                replication_factor: 1
    wal_directory: /tmp/agent
server:
    log_level: debug
```
