### ISSUE TITLE
Logs: StreamLagLabels  can't be set

### ISSUE THREAD

**Issue by a-patos** [grafana/agent#3339]
Hello,
it seems that in version v0.32.1 of the agent the setting of the stream_lag_labels is impossible to set up

In my configuration I tried:

```yaml
server:
  log_level: debug

metrics:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 30s
    external_labels:
      st: INFRA
      cartographie: DEV
      composant: log
      host: log-host
    remote_write:
      - url: http://mimir:9009/api/v1/push
        # basic_auth:
        #   username: user-id
        #   password: api-token
        headers:
          X-Scope-OrgID: fake
logs:
  positions_directory: /tmp/grafana_positions
  global:
   clients:
    - url: "https://loki:8443/loki/api/v1/push"
      tenant_id: fake
      tls_config:
       insecure_skip_verify: true
      stream_lag_labels: stream

  configs:
  - name: integrations
    scrape_configs:
    - job_name: integrations/node_exporter_direct_scrape
      static_configs:
      - targets:
        - localhost
        labels:
          st: INFRA
          cartographie: DEV
          composant: log
          host: log-host
          __path__: /var/log/{syslog,messages,*.log}
          job: integrations/node_exporter
```

and I get the expected error:

```
ts=2023-03-23T03:07:26.02027581Z caller=main.go:72 level=error msg="error creating the agen t server entrypoint" err="unable to apply config for integrations: unable to create logs instance: client config stream_lag_labels is deprecated in favor of the config file options block field, and will be ignored: stream"
```

I try as described in the doc:
https://grafana.com/docs/loki/latest/clients/promtail/configuration/#supported-contents-and-default-values-of-configyaml

with the following configuration:
i try as 

```yaml
server:
  log_level: debug

metrics:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 30s
    external_labels:
      st: INFRA
      cartographie: DEV
      composant: log
      host: log-host
    remote_write:
      - url: http://mimir:9009/api/v1/push
        # basic_auth:
        #   username: user-id
        #   password: api-token
        headers:
          X-Scope-OrgID: fake
logs:
  positions_directory: /tmp/grafana_positions
  global:
   clients:
    - url: "https://loki:8443/loki/api/v1/push"
      tenant_id: fake
      tls_config:
       insecure_skip_verify: true
 
  configs:
  - name: integrations
    options:
      stream_lag_labels: stream
    scrape_configs:
    - job_name: integrations/node_exporter_direct_scrape
      static_configs:
      - targets:
        - localhost
        labels:
          st: INFRA
          cartographie: DEV
          composant: log
          host: log-host
          __path__: /var/log/{syslog,messages,*.log}
          job: integrations/node_exporter
```

and i got : 

```
line 31: field options not found in type logs.instanceConfig
```

**Comment by tpaschalis** [comment]
Hey there! The `stream_lag_labels` option to add extra labels on the `promtail_stream_lag_seconds` metric has been deprecated and is being removed from the Promtail configuration.

If you still want to add a new identifier label on that metric, you'll have to do it with a `metric_relabel_configs` block under the metrics scrape job that is responsible for scraping this metric.

**Comment by a-patos** [comment]
Hi @tpaschalis , 

thanks for answer , i try :
server:
  log_level: debug

metrics:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 30s
    external_labels:
      st: INFRA
      cartographie: DEV
      composant: log
      host: log-host
    remote_write:
      - url: http://mimir:9009/api/v1/push
        # basic_auth:
        #   username: user-id
        #   password: api-token
        headers:
          X-Scope-OrgID: fake
logs:
  positions_directory: /tmp/grafana_positions
  global:
   clients:
    - url: "https://loki:8443/loki/api/v1/push"
      tenant_id: fake
      tls_config:
       insecure_skip_verify: true
 
  configs:
  - name: integrations
    options:
      stream_lag_labels: stream
    scrape_configs:
    - job_name: integrations/node_exporter_direct_scrape
      static_configs:
      - targets:
        - localhost
        labels:
          st: INFRA
          cartographie: DEV
          composant: log
          host: log-host
          __path__: /var/log/{syslog,messages,*.log}
          job: integrations/node_exporter
    relabel_configs:
      - source_labels: ['filename']
        target_label: 'stream'

**Comment by rfratto** [comment]
@tpaschalis I don't think we support that options field yet that Promtail introduced.

**Comment by a-patos** [comment]
Ok, I found a workaround that seems dirty:
```yaml
server:
  log_level: debug

metrics:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 30s
    external_labels:
      st: INFRA
      cartographie: DEV
      composant: log
      host: log-host
    remote_write:
      - url: http://mimir:9009/api/v1/push
        # basic_auth:
        #   username: user-id
        #   password: api-token
        headers:
          X-Scope-OrgID: fake
logs:
  positions_directory: /tmp/grafana_positions
  global:
   clients:
    - url: "https://loki:8443/loki/api/v1/push"
      tenant_id: fake
      tls_config:
       insecure_skip_verify: true
      stream_lag_labels: stream

  configs:
  - name: integrations
    scrape_configs:
    - job_name: integrations/node_exporter_direct_scrape
      static_configs:
      - targets:
        - localhost
        labels:
          st: INFRA
          cartographie: DEV
          composant: log
          host: log-host
          __path__: /var/log/{syslog,messages,*.log}
          job: integrations/node_exporter
      pipeline_stages:
      - regex:
          source: filename
          expression: '(?P<stream>.+)'
      - labels:
          stream:
      - labeldrop:
        - filename
```
