### ISSUE TITLE
Grafana agent API endpoints not working

### ISSUE THREAD

**Issue by JCastrejonE** [grafana/agent#3399]
### Discussed in https://github.com/grafana/agent/discussions/3398

<div type='discussions-op-text'>

<sup>Originally posted by **JCastrejonE** March 30, 2023</sup>
I'm running a grafana agent inside docker, with the following `agent.yaml`
```
metrics:
  global:
    scrape_interval: 60s
  configs:
  - name: hosted-prometheus
    scrape_configs:
      - job_name: ${GRAFANA_JOB_NAME}
        static_configs:
        - targets: [${COLLECTOR_HOST}]
    remote_write:
      - url: https://${GRAFANA_PROM_HOST}/api/prom/push
        basic_auth:
          username: ${GRAFANA_PROM_USER}
          password: ${GRAFANA_PASS}
```
Inside my docker compose:
```
agent:
    image: grafana/agent:latest
    volumes:
      - ./agent/config:/etc/agent-config
    environment:
      GRAFANA_JOB_NAME: "local/${NETWORK}"
    env_file:
      - .env
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/agent.yaml
      - -config.expand-env=true
    ports:
      - 12345:12345
```
However, when the agent starts I don't get a response from `http://localhost:12345/-/healthy` or any of the API endpoints. I can confirm that the port is being used because the error is not from connection refused, it is `ERR_EMPTY_RESPONSE`. I need to use the healthy or the ready endpoints because this is failing healthchecks when deploying to amazon ECS</div>
