### ISSUE TITLE
Promtail: Error on reload when using "metrics" stage

### ISSUE THREAD

**Issue by darxriggs** [grafana/agent#3408]
When using a `metrics` stage and trying to reload the Grafana Agent configuration, it logs the following error:
```
ts=2023-04-02T10:06:40.238329045Z caller=entrypoint.go:167 level=error msg="failed to update loki" err="failed to unregister all metrics from previous promtail. THIS IS A BUG"
```

**How to reproduce**
Scrape from files and configure a `metrics` stage (like [the "counter" example](https://grafana.com/docs/loki/v2.7.x/clients/promtail/stages/metrics/#counter) in the documentation):

```yaml
logs:
  positions_directory: /tmp/positions
  configs:
    - name: metrics example
      clients:
        - url: <FILL IN>
      scrape_configs:
        - job_name: log files
          static_configs:
            - labels:
                __path__: /var/log/*.log
          pipeline_stages:
            - metrics:
               log_lines_total:
                 type: Counter
                 description: "total number of log lines"
                 prefix: my_promtail_custom_
                 max_idle_duration: 24h
                 config:
                   match_all: true
                   action: inc
```

Send the process a `SIGHUP` signal.

**Environment**
* Grafana Agent v0.32.1
