### ISSUE TITLE
grafana-agent integration doesn't work with -enable-features=integrations-next

### ISSUE THREAD

**Issue by chrmang** [grafana/agent#3493]
When I try to start grafana-agent with command line flag `-enable-features=integrations-next` it fails to start.

    > ./grafana-agent-linux-arm64 --version
    agent, version v0.32.1 (branch: HEAD, revision: f48e41a9)
    build user:       root@ce4f3c31cd6b
    build date:       2023-03-06T19:07:05Z
    go version:       go1.20
    platform:         linux/arm64

The config file:

    > cat config.yaml
    metrics:
      wal_directory: /tmp/wal
      global:
        remote_write:
          - url: http://localhost:9009/api/prom/push

    integrations:
      agent:
        enabled: true

The error message:

    > ./grafana-agent-linux-arm64 -config.file=config.yaml -enable-features=integrations-next 
    2023/04/07 14:04:18 error loading config file config.yaml: yaml: unmarshal errors:
      line 1: field enabled not found in type agent.Config

The same error occurs when running on kubernetes cluster.

**Comment by tpaschalis** [comment]
Hey there 👋  There are a few changes small changes you'll have to make in your config file to make use of `integrations-next`; they're documented [here](https://grafana.com/docs/agent/latest/configuration/integrations/integrations-next/#integrations-changes).

You can start by removing the `enabled` field and defining the `autoscrape` field with your metrics instance to send the metrics to and go from there!

```yaml
server:
  log_level: debug

metrics:
  global:
    remote_write:
      - url: "http://localhost:9009/api/prom/push"
        basic_auth:
          username: "user"
          password: "secret"
  configs:
    - name: mymetricsinstance

integrations:
  agent:
    autoscrape:
      enable: true
      metrics_instance: "mymetricsinstance"
```

Let us know if you're experiencing any other issues!
