### ISSUE TITLE
integrations/process_exporter scrape read_bytes_total counter / write_bytes_total counter value always 0

### ISSUE THREAD

**Issue by lovesharepc** [grafana/agent#3502]
hello 
I use integrations/process_exporter 
and find out there always 0 in scrape read_bytes_total counter / write_bytes_total counter 
when I install process-exporter can see value change

OS: ubuntu 22.04
agent version: 
```
agent, version v0.32.1 (branch: HEAD, revision: f48e41a9)
  build user:       root@ce4f3c31cd6b
  build date:       2023-03-06T19:07:00Z
  go version:       go1.20
  platform:         linux/amd64
```

agent config:
```
server:
  log_level: warn

metrics:
  global:
    scrape_interval: 15s
    external_labels:
      node_name: 'sample_node'


    remote_write:
      - url: https://XXXXX:XXX/api/v1/push
        tls_config:
          insecure_skip_verify: true
        headers:
          X-Scope-OrgID: prometheus
        basic_auth:
          username: "mimirwrite"
          password: "mimirwrite"
  wal_directory: '/var/lib/grafana-agent'
  wal_cleanup_age: "12h"
  configs:
    - name: local
      host_filter: false
      scrape_configs:
        - job_name: 'process-exporter'
          # https://www.rabbitmq.com/prometheus.html
          static_configs:
            - targets: ['127.0.0.1:9256']

integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true
    include_exporter_metrics: true
  process_exporter:
    enabled: true
    process_names:
      - name: "{{.Comm}}"
        cmdline:
          - '.+' 

```

grafana explore
[Imgur](https://imgur.com/AaPYegx)
