### ISSUE TITLE
Docs feedback: /configuration/integrations/snmp-config.md

### ISSUE THREAD

**Issue by mikempx** [grafana/agent#3516]
### Multiple labels configuration example

One of the key capabilities of the SNMP exporter for Prometheus is the ability to enhance or augment your time series with labels.  For example, you may want to label certain devices with their country, city, and/or the business unit the device supports.  By using labels, you can then use Prometheus template variable’s[ label_values](https://grafana.com/docs/grafana/latest/datasources/prometheus/template-variables/#use-query-variables) feature to drive more dynamic dashboards, allowing users to sort data based on those labels.

Please note that this configuration uses Grafana agent’s experimental feature, [integrations-next](https://grafana.com/docs/agent/latest/configuration/integrations/integrations-next/), and so you will have to run your Grafana agent with the  -enable-features integrations-next parameter set.

The following example contains several configuration details worth mentioning.  
First, if you need to collect custom MIB data or if you would like to be selective in the OIDs you would like to collect, you are required to generate a custom config_file using snmp_exporter’s generator [here](https://github.com/prometheus/snmp_exporter/tree/main/generator).  On line 6, we reference a custom config_file; and on lines 29, 55, and 76, we reference the [module] name within that config_file we would like to use for our specific Prometheus job.
Second, we are using two different sets of snmpwalk credentials to collect our SNMP data.  Therefore, on lines 8 and 17 we define two different walk_params named SNMPGrafana - used for SNMP targets in the London_if_mib and Paris_palo_mib jobs - and “public”, which is used for devices defined in the London_bgp job.  
Third, there are relabel_configs to add static labels.  In all 3 jobs, we add a “region” label with a value of “EMEA”.  We also add a “location” label as well.  In the London_if_mib job, we also added static “device_name” labels so that we did not need to rely upon DNS.
Finally, we add a global static label on the last line of the configuration.

```
integrations:
  snmp:
    autoscrape:
      enable: false
      metrics_instance: integrations
    config_file: /etc/snmp.yml
    walk_params:
      SNMPGrafana:
        version: 3
        auth:
          security_level: authPriv
          auth_protocol: MD5
          username: snmpuser3
          password: XXXX
          priv_protocol: DES
          priv_password: XXXX
      public:
        version: 2
        auth:
          community: public
metrics:
  wal_directory: /var/lib/grafana-agent/data
  configs:
    - name: snmp_matrix
      scrape_configs:
      - job_name: London_if_mib
        scrape_timeout: 60s
        params:
          module: [if_mib]
          walk_params: [SNMPGrafana]
        metrics_path: /integrations/snmp/metrics
        relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - replacement: 127.0.0.1:12345
          target_label: __address__
        - replacement: EMEA
          target_label: region
        - replacement: London
          target_label: location
        static_configs:
          - targets:
            - 10.146.0.17
            labels:
              device_name: EMEA-DTC-Cisco-LAB
          - targets:
            - 10.146.0.20
            labels:
              device_name: EMEA-DTC-IR01
      - job_name: London_bgp
        scrape_timeout: 60s
        params:
          module: [bgp]
          walk_params: [public]
        metrics_path: /integrations/snmp/metrics
        relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - replacement: 127.0.0.1:12345
          target_label: __address__
        - replacement: EMEA
          target_label: region
        - replacement: London
          target_label: location
        static_configs:
          - targets:
            - 10.136.0.20
            - 10.136.0.30
      - job_name: Paris_palo_mib
        scrape_timeout: 60s
        params:
          module: [paloalto_mib]
          walk_params: [SNMPGrafana]
        metrics_path: /integrations/snmp/metrics
        relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - replacement: 127.0.0.1:12345
          target_label: __address__
        - replacement: EMEA
          target_label: region
        - replacement: PARIS
          target_label: location
        static_configs:
          - targets:
            - 10.126.0.1
            - 10.126.0.251
  global:
    remote_write:
    - basic_auth:
        password: <grafana_cloud_token>
        username: <grafana_cloud_id>
      url: https://prometheus-us-central1.grafana.net/api/prom/push
    external_labels:
      SNMPtargettype: Network_Devices
```
