### ISSUE TITLE
`replace_instance_label` does not take effect on custom `scrape_configs`

### ISSUE THREAD

**Issue by mateuszdrab** [grafana/agent#3556]
Hi guys

I've been wanting to utilize the feature `replace_instance_label` which is enabled by default; however, in my setup, the instance label is not replaced.

A very simple example is when trying to use a vscode exporter extension with the following sample config:

```
server:
  log_level: info

metrics:
  wal_directory: C:\ProgramData\grafana-agent\wal
  global:
    scrape_interval: 1m
    scrape_timeout: 1m
    remote_write:
      - url: x
        basic_auth:
          username: y
          password: z
  configs:
    - name: agent
      scrape_configs:
        - job_name: vscode
          static_configs:
            - targets:
                - 127.0.0.1:9931
              labels:
                job: vscode
integrations:
  windows_exporter:
    enabled: true
  agent:
    enabled: true
```

I'm aware that it seems the `replace_instance_label` feature is scoped to integrations but I'm not seeing a way to add a custom scrape target via integrations. 

Am I missing something?

P.S. Is there such feature for logs? I'd like to use a file target job to collect files from a local system and send to loki; however, I don't see a way to inject the hostname into a label without using environment variable based labels which requires an extra agent flag which can't be easily enabled via the bundled agent installer for Windows.

Thanks!
