### ISSUE TITLE
[helm] envFrom in grafana-agent chart is not templating properly

### ISSUE THREAD

**Issue by day4me** [grafana/agent#3576]
I was trying to deploy grafana agent using helm chart(https://github.com/grafana/agent/tree/main/operations/helm/charts/grafana-agent), but when I add envFrom to the values, it does not appear in the manifest after deployment.
https://github.com/grafana/agent/blob/5d1338f0f5be64d87ddecfec9c092522549fb5de/operations/helm/charts/grafana-agent/templates/containers/_agent.yaml#L32
Can you please look into this?
I'm using the latest chart release.
Thanks in advance.

**Comment by tpaschalis** [comment]
Can you share more details about how you're using envFrom? In my setup it seems to work alright.

I created a sample configMap and installed it on my cluster like `kubectl create -f configmap-multikeys.yaml`.
```
# configmap-multikeys.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: agent
data:
  SPECIAL_LEVEL: very
  SPECIAL_TYPE: charm

$ kubectl create -f configmap-multikeys.yaml
```

I changed my `values.yaml` file to refer to this configmap
```
  envFrom:
    - configMapRef:
        name: special-config
```

And my pods had the env variables set on them
```
$ k exec -it agent-grafana-agent-qxmtk -- bash
# env | grep SPECIAL
SPECIAL_TYPE=charm
SPECIAL_LEVEL=very
```

When you use the `helm template .` command, do you see the `envFrom` field being populated correctly?

**Comment by day4me** [comment]
Hello @tpaschalis .
I used the same example as you, but I do not see it. 
Here is my values.yaml
```
agent:
  mode: 'static'
  configMap:
    create: false
    name: grafana-agent
    key: agent.yaml

  envFrom:
    - configMapRef:
        name: special-config

  extraArgs: ["-config.expand-env=true"]
```
```
helm template grafana/grafana-agent -f values.yaml
# Source: grafana-agent/templates/controllers/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: release-name-grafana-agent
  labels:
    helm.sh/chart: grafana-agent-0.10.0
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.32.1"
    app.kubernetes.io/managed-by: Helm
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-agent
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-agent
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccount: release-name-grafana-agent
      imagePullSecrets:
          - name: observability-artifactory
      containers:
          - name: grafana-agent
            image: grafana/agent:latest
            imagePullPolicy: IfNotPresent
            args:
              - -config.file=/etc/agent/agent.yaml
              - -server.http.address=0.0.0.0:80
              - -config.expand-env=true
            env:
              - name: AGENT_MODE
                value: static
              - name: HOSTNAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            ports:
              - containerPort: 80
                name: http-metrics
              - containerPort: 12347
                name: faro
            readinessProbe:
              httpGet:
                path: /-/ready
                port: 80
              initialDelaySeconds: 10
              timeoutSeconds: 1
            volumeMounts:
              - name: config
                mountPath: /etc/agent
          - name: config-reloader
            image: jimmidyson/configmap-reload
            args:
              - --volume-dir=/etc/agent
              - --webhook-url=http://localhost:80/-/reload
            volumeMounts:
              - name: config
                mountPath: /etc/agent
      volumes:
        - name: config
          configMap:
            name: grafana-agent
```
Checked the pod also, nothing there.
