### ISSUE TITLE
helm: incorrect yaml identation of some resources

### ISSUE THREAD

**Issue by pcecot** [grafana/agent#3617]
The latest helm chart requires the following definition of some resources such as toleration (4 spaces instead of 2):

```
controller:
  tolerations:
      - operator: "Exists"
```

Seems like #3386 broke it.

**Comment by rfratto** [comment]
We have a [test](https://github.com/grafana/agent/blob/main/operations/helm/charts/grafana-agent/ci/tolerations-values.yaml) which successfully creates a template with tolerations using two spaces.

What are you seeing when you try to use two spaces?

**Comment by pcecot** [comment]
When I use two spaces I don't see the custom toleration:

```
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
```

Only after adding four spaces I can see `- operator: "Exists"` is added:

```
  tolerations:
  - operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
```
