### ISSUE TITLE
static: multiplex integrations-next instances cannot have their config marshalled

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#3627]
As an example, the mongodb integration uses the shim to register itself to the v2 'integrations-next' functionality as a multiplex integration.

When using a config file like the following and starting the Agent, we can indeed monitor multiple mongodb instances.
The issue presents itself when using `-config.enable-read-api`. The `/-/config` endpoint produces an error as it's somehow still expected to be a single key instead of an array.

```yaml
metrics:
  global:
    scrape_interval: 5s
    remote_write:
      - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
        basic_auth:
          username: user
          password: pass
  configs:
    - name: default
      scrape_configs:
        - job_name: agent
          static_configs:
            - targets: ['127.0.0.1:12345']

integrations:
  mongodb_configs:
    - mongodb_uri: "mongodb://mongodb0.example.com:27017"
    - mongodb_uri: "mongodb://mongodb0.example.com:27018"
    - mongodb_uri: "mongodb://mongodb0.example.com:27019"
```

```
$ ./build/grafana-agent -config.file ~/integrations-next-multiplex.yaml -config.enable-read-api -enable-features=integrations-next
... 

$ curl localhost:12345/-/config
failed to marshal config: integration "mongodb" may not be defined more than once
```
