### ISSUE TITLE
Kubernetes not supported for Loki/Promtail?

### ISSUE THREAD

**Issue by loganmc10** [grafana/agent#363]
```
field kubernetes_sd_config not found in type scrapeconfig.plain
```

Here is my config:
```
loki:
  positions:
    filename: /var/log/traps/positions.yaml

  scrape_configs:
  - job_name: k8slogs
    kubernetes_sd_config:
      role: pod
      namespaces:
        names:
          - my_namespace
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: replace
        target_label: kubernetes_pod_container_name
```

**Comment by rfratto** [comment]
Hi there, it should be `kubernetes_sd_configs` as an array:

```yaml
loki:
  positions:
    filename: /var/log/traps/positions.yaml

  scrape_configs:
  - job_name: k8slogs
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
          - my_namespace
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: replace
        target_label: kubernetes_pod_container_name
```
