### ISSUE TITLE
Unable to find matching hostLabels

### ISSUE THREAD

**Issue by KarstenSiemer** [grafana/agent#3668]
Hello dear community!

After some talks to @tpaschalis on [your slack workspace](https://grafana.slack.com/archives/C01050C3D8F/p1681204440310699), we concluded that we have to reach out for help.

**What am I doing?**

I am trying to send traces from OTel collectors to grafana agent, attach k8s labels using the agents service discovery mechanisms and afterwards send the traces to grafana tempo for display + matching to logs and metrics.
Sending the traces through that pipeline is working, but attaching the labels does not work.

I was following these guides:
[k8s-agent-traces](https://grafana.com/docs/grafana-cloud/kubernetes-monitoring/other-methods/k8s-agent-traces/)
[grafana-agent](https://grafana.com/docs/tempo/latest/grafana-agent/)
[attach prometheus metadata to traces](https://grafana.com/blog/2020/11/17/tracing-with-the-grafana-cloud-agent-and-grafana-tempo/)

I tried [this](https://raw.githubusercontent.com/grafana/agent/main/production/kubernetes/agent-traces.yaml) installation manifest of the agent in version v0.32.1 first and now in **v0.33.0-rc.1**

current config:
```
apiVersion: v1
data:
  agent.yaml: |
    server:
      log_level: debug
    traces:
      configs:
        - batch:
              send_batch_size: 1000
              timeout: 1s
          name: default
          receivers:
              jaeger:
                  protocols:
                      grpc: null
                      thrift_binary: null
                      thrift_compact: null
                      thrift_http: null
              opencensus: null
              otlp:
                  protocols:
                      grpc: null
                      http: null
              zipkin: null
          remote_write:
            - endpoint: tempo:4317
              insecure: true
              retry_on_failure:
                  enabled: true
          automatic_logging:
            roots: true
            processes: true
          service_graphs:
            enabled: false
          scrape_configs:
          - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            job_name: kubernetes-pods
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_name]
              target_label: pod
            - source_labels: [__meta_kubernetes_pod_container_name]
              target_label: container
            - source_labels: [__meta_kubernetes_service_name]
              target_label: job
            - source_labels: [__address__]
              regex: "([^:]+):.+"
              target_label: "__address__"
              replacement: "$1"
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: false
immutable: false
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: Terraform
  name: grafana-agent-traces
  namespace: monitoring
```

Pictures attached show that the node-graph and the tracing in general is working.
![Node graph](https://user-images.githubusercontent.com/40307978/234776629-b03789e1-38fe-4d57-8bdd-bc2ff45603d8.png)
![Span labels](https://user-images.githubusercontent.com/40307978/234776650-19bd5b92-d068-48b3-bef9-fe7b9d973bf3.png)
![Span label ip)](https://user-images.githubusercontent.com/40307978/234776633-459c8edf-5e09-440b-b08a-4f81ba8333a9.png)

When I look into my actual prometheus instance ( we use prometheus-operator, so defined sd is by podMonitor and serviceMonitor) I can find the __address__  in undefined service discovery, with all the info I want grafana-agent to attach to the span. (attached as well)

![Prom SD](https://user-images.githubusercontent.com/40307978/234776640-d80c7ada-eb6d-4cb7-9e1e-bc8c9deb2643.png)
![Prom SD2](https://user-images.githubusercontent.com/40307978/234776643-f56f0e23-1333-4aa2-85fd-0e4dd947ec19.png)

The error I see in debug logs:

```
ts=2023-04-24T13:29:41.445321242Z caller=prom_sd_processor.go:169 level=debug component="traces service disco" msg="unable to find ip in span attributes, skipping attribute addition"
```

**What do I expect?**

I would expect the grafana agent to utilize prometheus sd to attach further metadata to the spans, so that I can match traces to logs according to their metadata. Which is currently not possible due to missing metadata on the traces
