### ISSUE TITLE
Feature request: Support for multiple Redis Server pools on same localhost

### ISSUE THREAD

**Issue by TheOldMan2000** [grafana/agent#3698]
Hello, 
Please would add support for observing multiple Redis Server instances/pools on the same machine?

Nothing fancy like support for Redis Cluster, Sentinel or use by Kubernetes etc, just the ability to select a different Redis Server instance or be able to Select All (instances).

e.g. localhost:6379, localhost:6380, localhost:6381 etc.

The drop box form field is already there, but only shows one instance. The docs say you can do it by adding multiple agents, but to a newbie Grafana user like myself, it doesn’t explain how or give any example config. There is a small example, but it creates errors and stops the Grafana-Agent.service from working.

Many thanks!

**Comment by tpaschalis** [comment]
Hey Graham! 👋 Could you tell us where you got that drop box field and example? Is it a page in Grafana Cloud?

In any case, to observe multiple redis instances, you can pass in the `--enable-features=integrations-next` command-line flag, and alter your current YAML [configuration](https://grafana.com/docs/agent/latest/static/configuration/integrations/integrations-next/) so it's still working. Then you can define multiple redis integration instances under the `redis_configs` key. Here's a config to get you started.

```yaml
integrations:
  metrics:
    autoscrape:
      enable: true                       # whether to automatically scrape integrations
      metrics_instance: "redis_integration"  # which instance of the 'metrics' block below should scrape these integrations
  redis_configs:
    - instance: "foo"
      redis_addr: "127.0.0.1:6379"
    - instance: "bar"
      redis_addr: "127.0.0.1:6380"

metrics:
  global:
    scrape_interval: 1m
  configs:
    - name: redis_integration
      remote_write:
        - url: url
          basic_auth:
            username: user
            password: pass
```

Then you'll be able to hit the `/agent/api/v1/metrics/instances` and `/agent/api/v1/metrics/targets` endpoints to see the status of your metrics instances and targets.
