### ISSUE TITLE
Cannot set the allowlist field in node_exporter's diskstat collector

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#3759]
The logic around the include/exclude fields for the diskstat collector in the node_exporter integration, that is also inherited by the prometheus.exporter.unix component was that a) the `device_exclude` field had a default value and b) the `device_exclude` and `device_include` fields were mutually exclusive.

This meant that the first field was always being set implicitly, and if the second was defined then node_exporter could not start. The following two config files failed to start the Agent, and there is no way to make use of `device_include`.

```yaml
integrations:
  node_exporter:
    enabled: true
    scrape_integration: true
    set_collectors:
      - "diskstats"
    diskstats_device_include: "/dev/vd.*"
```

```river
prometheus.exporter.unix {
	disk {
		device_include = "foo"
	}
}
```
