### ISSUE TITLE
Add grafanacloud block to config that creates default write locations for Prometheus, Loki, Tempo, Integrations

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#379]
A fully configured Agent config file requires configuring write settings four times: Prometheus, Loki, Tempo, and Integrations. If users are sending data to Grafana Cloud, we can add a block to look up the proper settings:

```yaml
grafanacloud:
   # Stack ID to write to 
   stack_id: <string>
   # MetricsPublisher API key 
   api_key: <string>
``` 

If this block is defined at the root of the config file, default settings for subsystems will be defined. 

Note that this would currently rely on an undocumented API. 

Related: #378
