### ISSUE TITLE
Fatal error: unexpected fault address 0x1fb2e7c: segmentation violation code=0x2 addr=0x1fb2e7c pc=0x4f6b0c

### ISSUE THREAD

**Issue by wallrj** [grafana/agent#381]
Grafana Agent crashed with this traceback: 
[panic.txt](https://github.com/grafana/agent/files/5921879/panic.txt)

Config:
```
server:
  http_listen_address: 127.0.0.1
  http_listen_port: 8081
  grpc_listen_address: 127.0.0.1
  grpc_listen_port: 8082
  log_level: info

prometheus:
  wal_directory: ${STATE_DIRECTORY}/grafana-agent-wal
  global:
    scrape_interval: 15s
  configs: null

integrations:
  node_exporter:
    enabled: true
    disable_collectors:
      - timex # See https://github.com/prometheus/node_exporter/issues/1934

  prometheus_remote_write:
  - url: https://prometheus-us-central1.grafana.net/api/prom/push
    basic_auth:

loki:
  positions:
    filename: ${STATE_DIRECTORY}/positions.yaml

  clients:
  - url: https://logs-prod-us-central1.grafana.net/api/prom/push
    basic_auth:

  scrape_configs:
  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'hostname'

```

```
# grafana-agent --version
agent, version v0.11.0 (branch: HEAD, revision: 48c0762)
  build user:       runner@fv-az184-545
  build date:       2021-01-20T16:32:37Z
  go version:       go1.14.4
  platform:         linux/arm

```

Raspbian GNU/Linux 10 (buster)
Raspberry Pi 3 Model B Plus Rev 1.3
