### ISSUE TITLE
Provide `headers` option in remote write config

### ISSUE THREAD

**Issue by jeschkies** [grafana/agent#385]
I would like to defined custom headers in the remote write config. E.g.

```yaml
name: foo-ec2
instances:
- job_name: foo-ec2
  static_configs:
  - targets: ['whatever']
  remote_write:
  - url: http://cortex-internal:9009/api/prom/push
    headers:
      X-Scope-OrgID: foobar
```

`headers` is an optional field that takes a map of header name to header value.
