### ISSUE TITLE
consul_exporter tracks up == 1 if event if consul is down

### ISSUE THREAD

**Issue by suikast42** [grafana/agent#3959]
### What's wrong?

Have two scrappers.
1. static one 
2. Integrations/consul_exporter

Both of them are configured for localhost:8501 over tls

If I stop the consul service then the intehrations scrapper send up=1 for the job. 

Agent config 

``` yaml
server:
  log_level: info
  http_tls_config:
    cert_file: "/etc/opt/certs/nomad/nomad.pem"
    key_file: "/etc/opt/certs/nomad/nomad-key.pem"
    client_auth_type: "RequireAndVerifyClientCert"
    client_ca_file: "/usr/local/share/ca-certificates/cloudlocal/cluster-ca-bundle.pem"

metrics:
  wal_directory: "/opt/services/observability/grafana_agent/wal"
  global:
    scrape_interval: 10s
    remote_write:
      - url: http://mimir.service.consul:9009/api/v1/push
#        headers:
#          X-Scope-OrgID: 1
  configs:
    # This name is printed in the agent/api/v1/instances
    - name: integration/nomad
      scrape_configs:
        # Scrape metrics from nomad
        - job_name: integrations/nomad
          metrics_path: /v1/metrics
          tls_config:
            insecure_skip_verify: false
            ca_file: "/usr/local/share/ca-certificates/cloudlocal/cluster-ca-bundle.pem"
            cert_file: "/etc/opt/certs/nomad/nomad.pem"
            key_file: "/etc/opt/certs/nomad/nomad-key.pem"
          scheme: https
          params:
            format:
              - prometheus
          static_configs:
            - targets: ['localhost:4646']
              # Add label for imported dashboard
              labels:
                agent_hostname: "worker-03"
          relabel_configs:
            # Replace the instance label with the hostname.
            # Otherwise, localhost:4646 will be tracked in this label
            - source_labels: [ instance ]
              replacement: "worker-03"
              target_label: instance
              action: replace
        - job_name: integrations/consul_test
          metrics_path: /v1/agent/metrics
          tls_config:
            insecure_skip_verify: false
            ca_file: "/usr/local/share/ca-certificates/cloudlocal/cluster-ca-bundle.pem"
            cert_file: "/etc/opt/certs/consul/consul.pem"
            key_file: "/etc/opt/certs/consul/consul-key.pem"
          scheme: https
          params:
            format:
              - prometheus
          static_configs:
            - targets: ['localhost:8501']
              # Add label for imported dashboard
              labels:
                agent_hostname: "worker-03"
          relabel_configs:
            # Replace the instance label with the hostname.
            # Otherwise, localhost:4646 will be tracked in this label
            - source_labels: [ instance ]
              replacement: "worker-03"
              target_label: instance
              action: replace
#logs:
#  configs:
#    - name: default
#      clients:
#        - url:  http://loki.service.consul:3100/api/v1/push
#      positions:
#        filename: "/opt/services/observability/grafana_agent/logpos/positions.yaml"
#      target_config:
#        sync_period: 10s
#      scrape_configs:
#        - job_name: integrations/docker
#          docker_sd_configs:
#            - host: unix:///var/run/docker.sock
#              refresh_interval: 5s
#          relabel_configs:
#            - action: replace
#              replacement: integrations/docker
#              source_labels:
#                - __meta_docker_container_id
#              target_label: job
#            - source_labels:
#                - __meta_docker_container_name
#              regex: '/(.*)'
#              target_label: container
#            - source_labels:
#                - __meta_docker_container_log_stream
#              target_label: stream


traces:
  configs:
    - name: default
      service_graphs:
        enabled: true
      remote_write:
        - endpoint: http://tempo-otlp-grpc.service.consul:4317
#          headers:
#            X-Scope-OrgID: 1
          insecure: true
      receivers:
        jaeger:
          protocols:
            thrift_http:


integrations:
  http_tls_config:
    insecure_skip_verify: true
    ca_file: "/usr/local/share/ca-certificates/cloudlocal/cluster-ca-bundle.pem"
    cert_file: "/etc/opt/certs/nomad/nomad.pem"
    key_file: "/etc/opt/certs/nomad/nomad-key.pem"

  agent:
    # Enables the Agent integration, allowing the Agent to automatically
    enabled: true
    relabel_configs:
      - action: replace
        source_labels:
          - agent_hostname
        target_label: instance
  # Scrape metrics from linux host
  node_exporter:
    enabled: true
    relabel_configs:
      - action: replace
        source_labels:
          - agent_hostname
        target_label: instance
  # Scrape metrics from consul
  consul_exporter:
    enabled: true
    server: https://localhost:8501
    ca_file: "/usr/local/share/ca-certificates/cloudlocal/cluster-ca-bundle.pem"
    cert_file: "/etc/opt/certs/consul/consul.pem"
    key_file: "/etc/opt/certs/consul/consul-key.pem"
    relabel_configs:
      - action: replace
        source_labels:
          - agent_hostname
        target_label: instance
```

### Steps to reproduce

Configre the agent with the config file below

### Configuration

```text
Agent config 

 yaml
server:
  log_level: info
  http_tls_config:
    cert_file: "/etc/opt/certs/nomad/nomad.pem"
    key_file: "/etc/opt/certs/nomad/nomad-key.pem"
    client_auth_type: "RequireAndVerifyClientCert"
    client_ca_file: "/usr/local/share/ca-certificates/cloudlocal/cluster-ca-bundle.pem"

metrics:
  wal_directory: "/opt/services/observability/grafana_agent/wal"
  global:
    scrape_interval: 10s
    remote_write:
      - url: http://mimir.service.consul:9009/api/v1/push
#        headers:
#          X-Scope-OrgID: 1
  configs:
    # This name is printed in the agent/api/v1/instances
    - name: integration/nomad
      scrape_configs:
        # Scrape metrics from nomad
        - job_name: integrations/nomad
          metrics_path: /v1/metrics
          tls_config:
            insecure_skip_verify: false
            ca_file: "/usr/local/share/ca-certificates/cloudlocal/cluster-ca-bundle.pem"
            cert_file: "/etc/opt/certs/nomad/nomad.pem"
            key_file: "/etc/opt/certs/nomad/nomad-key.pem"
          scheme: https
          params:
            format:
              - prometheus
          static_configs:
            - targets: ['localhost:4646']
              # Add label for imported dashboard
              labels:
                agent_hostname: "worker-03"
          relabel_configs:
            # Replace the instance label with the hostname.
            # Otherwise, localhost:4646 will be tracked in this label
            - source_labels: [ instance ]
              replacement: "worker-03"
              target_label: instance
              action: replace
        - job_name: integrations/consul_test
          metrics_path: /v1/agent/metrics
          tls_config:
            insecure_skip_verify: false
            ca_file: "/usr/local/share/ca-certificates/cloudlocal/cluster-ca-bundle.pem"
            cert_file: "/etc/opt/certs/consul/consul.pem"
            key_file: "/etc/opt/certs/consul/consul-key.pem"
          scheme: https
          params:
            format:
              - prometheus
          static_configs:
            - targets: ['localhost:8501']
              # Add label for imported dashboard
              labels:
                agent_hostname: "worker-03"
          relabel_configs:
            # Replace the instance label with the hostname.
            # Otherwise, localhost:4646 will be tracked in this label
            - source_labels: [ instance ]
              replacement: "worker-03"
              target_label: instance
              action: replace
#logs:
#  configs:
#    - name: default
#      clients:
#        - url:  http://loki.service.consul:3100/api/v1/push
#      positions:
#        filename: "/opt/services/observability/grafana_agent/logpos/positions.yaml"
#      target_config:
#        sync_period: 10s
#      scrape_configs:
#        - job_name: integrations/docker
#          docker_sd_configs:
#            - host: unix:///var/run/docker.sock
#              refresh_interval: 5s
#          relabel_configs:
#            - action: replace
#              replacement: integrations/docker
#              source_labels:
#                - __meta_docker_container_id
#              target_label: job
#            - source_labels:
#                - __meta_docker_container_name
#              regex: '/(.*)'
#              target_label: container
#            - source_labels:
#                - __meta_docker_container_log_stream
#              target_label: stream


traces:
  configs:
    - name: default
      service_graphs:
        enabled: true
      remote_write:
        - endpoint: http://tempo-otlp-grpc.service.consul:4317
#          headers:
#            X-Scope-OrgID: 1
          insecure: true
      receivers:
        jaeger:
          protocols:
            thrift_http:


integrations:
  http_tls_config:
    insecure_skip_verify: true
    ca_file: "/usr/local/share/ca-certificates/cloudlocal/cluster-ca-bundle.pem"
    cert_file: "/etc/opt/certs/nomad/nomad.pem"
    key_file: "/etc/opt/certs/nomad/nomad-key.pem"

  agent:
    # Enables the Agent integration, allowing the Agent to automatically
    enabled: true
    relabel_configs:
      - action: replace
        source_labels:
          - agent_hostname
        target_label: instance
  # Scrape metrics from linux host
  node_exporter:
    enabled: true
    relabel_configs:
      - action: replace
        source_labels:
          - agent_hostname
        target_label: instance
  # Scrape metrics from consul
  consul_exporter:
    enabled: true
    server: https://localhost:8501
    ca_file: "/usr/local/share/ca-certificates/cloudlocal/cluster-ca-bundle.pem"
    cert_file: "/etc/opt/certs/consul/consul.pem"
    key_file: "/etc/opt/certs/consul/consul-key.pem"
    relabel_configs:
      - action: replace
        source_labels:
          - agent_hostname
        target_label: instance
```
```


###  Version
v0.33.2
