### ISSUE TITLE
Agent not tailing with kubernetes_sd_configs

### ISSUE THREAD

**Issue by kmeinster** [grafana/agent#404]
While trying to migrate from promtail to the agent we can't seem to push any kubernetes logs (the ones discovered via `kubernetes_sd_configs`

The debug log only tells us: 

```
level=info ts=2021-02-09T16:40:29.749303056Z caller=server.go:229 http=[::]:12345 grpc=[::]:9095 msg="server listening on addresses"
level=debug ts=2021-02-09T16:40:29.755600054Z caller=instance.go:267 agent=prometheus instance=afc7ab03ef06cdd0e0f78f1bf4f93edd msg="initializing instance" name=afc7ab03ef06cdd0e0f78f1bf4f93edd
level=info ts=2021-02-09T16:40:29.756103789Z caller=kubernetes.go:263 component=loki loki_config=default component=discovery discovery=kubernetes msg="Using pod service account via in-cluster config"
level=debug ts=2021-02-09T16:40:29.756894793Z caller=manager.go:195 component=loki loki_config=default component=discovery msg="Starting provider" provider=kubernetes/0 subs="[kubernetes-pods-name kubernetes-pods-app kubernetes-pods-direct-controllers kubernetes-pods-indirect-controller kubernetes-pods-static]"
```
`static_configs` do work, they get tailed and pushed to Loki and prometheus metrics do get discovered and get pushed to Cortex.

Converted config (works in promtail):
```
loki:
  configs:
    - name: default
      positions:
        filename: /tmp/positions.yaml
      clients:
        - url: https://something-something/loki/api/v1/push
          bearer_token: vanillaflavouredmilkshakesarenotsosecret
      scrape_configs:
      - pipeline_stages:
        - docker:
        job_name: kubernetes-pods-name
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels:
          - __meta_kubernetes_pod_label_name
          target_label: __service__
        - source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: drop
          regex: ^$
          source_labels:
          - __service__
        - action: replace
          replacement: $1
          separator: /
          source_labels:
          - __meta_kubernetes_namespace
          - __service__
          target_label: job
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: instance
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container_name
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
          target_label: __path__
      - pipeline_stages:
        - docker:
        job_name: kubernetes-pods-app
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - action: drop
          regex: .+
          source_labels:
          - __meta_kubernetes_pod_label_name
        - source_labels:
          - __meta_kubernetes_pod_label_app
          target_label: __service__
        - source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: drop
          regex: ^$
          source_labels:
          - __service__
        - action: replace
          replacement: $1
          separator: /
          source_labels:
          - __meta_kubernetes_namespace
          - __service__
          target_label: job
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: instance
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container_name
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
          target_label: __path__
      - pipeline_stages:
        - docker:
        job_name: kubernetes-pods-direct-controllers
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - action: drop
          regex: .+
          separator: ''
          source_labels:
          - __meta_kubernetes_pod_label_name
          - __meta_kubernetes_pod_label_app
        - action: drop
          regex: ^([0-9a-z-.]+)(-[0-9a-f]{8,10})$
          source_labels:
          - __meta_kubernetes_pod_controller_name
        - source_labels:
          - __meta_kubernetes_pod_controller_name
          target_label: __service__
        - source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: drop
          regex: ^$
          source_labels:
          - __service__
        - action: replace
          replacement: $1
          separator: /
          source_labels:
          - __meta_kubernetes_namespace
          - __service__
          target_label: job
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: instance
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container_name
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
          target_label: __path__
      - pipeline_stages:
        - docker:
        job_name: kubernetes-pods-indirect-controller
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - action: drop
          regex: .+
          separator: ''
          source_labels:
          - __meta_kubernetes_pod_label_name
          - __meta_kubernetes_pod_label_app
        - action: keep
          regex: ^([0-9a-z-.]+)(-[0-9a-f]{8,10})$
          source_labels:
          - __meta_kubernetes_pod_controller_name
        - action: replace
          regex: ^([0-9a-z-.]+)(-[0-9a-f]{8,10})$
          source_labels:
          - __meta_kubernetes_pod_controller_name
          target_label: __service__
        - source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: drop
          regex: ^$
          source_labels:
          - __service__
        - action: replace
          replacement: $1
          separator: /
          source_labels:
          - __meta_kubernetes_namespace
          - __service__
          target_label: job
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: instance
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container_name
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
          target_label: __path__
      - pipeline_stages:
        - docker:
        job_name: kubernetes-pods-static
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - action: drop
          regex: ^$
          source_labels:
          - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_label_component
          target_label: __service__
        - source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: drop
          regex: ^$
          source_labels:
          - __service__
        - action: replace
          replacement: $1
          separator: /
          source_labels:
          - __meta_kubernetes_namespace
          - __service__
          target_label: job
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: instance
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container_name
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
          - __meta_kubernetes_pod_container_name
          target_label: __path__
```
No clue where to check further (to be honest, I'm mostly clueless about things in general).

**Comment by rfratto** [comment]
Hey there, how did you install the Agent?

**Comment by kmeinster** [comment]
Yeah should've added that, I've basically used those too:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: graffy-agent
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: graffy-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: graffy-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: graffy-agent
subjects:
  - kind: ServiceAccount
    name: graffy-agent
    namespace: default
```

I will check a bit more in the SA side of things since I haven't checked that properly, though prometheus metrics are actually discovered (same agent pod).

**Comment by kmeinster** [comment]
Ooh and the deployment file that I use for minikube (to test the agent):

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethos-agent
  labels:
    app: ethos-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ethos-agent
  template:
    metadata:
      labels:
        app: ethos-agent
    spec:
      serviceAccountName: graffy-agent
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: etcmachineid
          hostPath:
            path: /etc/machine-id
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: pods
          hostPath:
            path: /var/log/pods
        - emptyDir:
            medium: Memory
          name: istio-certs
        - emptyDir:
            medium: Memory
          name: istio-envoy
        - name: istio-token
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  audience: istio-ca
                  expirationSeconds: 43200
                  path: istio-token
        - configMap:
            defaultMode: 420
            name: istio-ca-root-cert
          name: istiod-ca-cert
        - name: agent-config
          configMap:
            name: agent-config
      containers:
        - name: ethos-agent
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - mountPath: /var/log
              name: varlog
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - mountPath: /etc/machine-id
              name: etcmachineid
              readOnly: true
            - name: pods
              mountPath: /var/log/pods
              readOnly: true
            - mountPath: "/etc/agent-config"
              name: agent-config
              readOnly: true
            - mountPath: /etc/istio-certs
              name: istio-certs
          image: grafana/agent:latest
          args: ["-config.file=/etc/agent-config/agent.yaml", "-prometheus.wal-directory=/tmp/agent/wal"]
          ports:
            - containerPort: 12345
              name: http
        - name: istio-proxy
          args:
            - proxy
            - sidecar
            - --domain
            - $(POD_NAMESPACE).svc.cluster.local
            - --configPath
            - /etc/istio/proxy
            - --binaryPath
            - /usr/local/bin/envoy
            - --serviceCluster
            - istio-proxy-prometheus
            - --drainDuration
            - 45s
            - --parentShutdownDuration
            - 1m0s
            - --discoveryAddress
            - istio-pilot.istio-system.svc:15012
            - --proxyLogLevel=warning
            - --proxyComponentLogLevel=misc:error
            - --connectTimeout
            - 10s
            - --proxyAdminPort
            - "15000"
            - --controlPlaneAuthPolicy
            - NONE
            - --dnsRefreshRate
            - 300s
            - --statusPort
            - "15020"
            - --trust-domain=cluster.local
            - --controlPlaneBootstrap=false
          env:
              - name: OUTPUT_KEY_CERT_TO_DIRECTORY
                value: /etc/istio-certs
              - name: JWT_POLICY
                value: third-party-jwt
              - name: PILOT_CERT_PROVIDER
                value: istiod
              - name: CA_ADDR
                value: istio-pilot.istio-system.svc:15012
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
              - name: INSTANCE_IP
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: status.podIP
              - name: SERVICE_ACCOUNT
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: spec.serviceAccountName
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: status.hostIP
              - name: ISTIO_META_POD_NAME
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
              - name: ISTIO_META_CONFIG_NAMESPACE
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
              - name: ISTIO_META_MESH_ID
                value: cluster.local
              - name: HOSTNAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
          image: docker.io/istio/proxyv2:1.5.0
          imagePullPolicy: IfNotPresent
          ports:
              - containerPort: 15090
                name: http-envoy-prom
                protocol: TCP
          readinessProbe:
            failureThreshold: 30
            httpGet:
                path: /healthz/ready
                port: 15020
                scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
              - mountPath: /var/run/secrets/istio
                name: istiod-ca-cert
              - mountPath: /etc/istio/proxy
                name: istio-envoy
              - mountPath: /var/run/secrets/tokens
                name: istio-token
              - mountPath: /etc/istio-certs/
                name: istio-certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
```
