### ISSUE TITLE
Support grafana agent operator for gcp_exporter

### ISSUE THREAD

**Issue by alhafoudh** [grafana/agent#4056]
### Request

When grafana agent is deployd using operator, `gcp_exporter` configuraiton is not working.

I am using following `Integration` CR:

```
apiVersion: monitoring.grafana.com/v1alpha1
kind: Integration
metadata:
  labels:
    agent: grafana-agent
  name: gcp-exporter
  namespace: grafana
spec:
  name: gcp_exporter
  type:
    allNodes: false
    unique: true
  config:
    enabled: true
    gcp_exporter:
      project_ids:
        - 'xxx'
      gcp_client_timeout: 15s
      metrics_prefixes:
        - compute.googleapis.com/
        - storage.googleapis.com/
        - redis.googleapis.com/
        - cloudsql.googleapis.com/
        - networking.googleapis.com/
        - loadbalancing.googleapis.com/
        - autoscaler.googleapis.com/
```

Then I get this error log from `grafana-agent-integrations-deploy` Pod:

```
ts=2023-06-05T16:21:39.639934501Z caller=entrypoint.go:341 level=error msg="failed to reload config file" err="error loading config file /var/lib/grafana-agent/config/agent.yml: yaml: unmarshal errors:\n  line 4: field gcp_exporter_configs not found in type integrations.SubsystemOptions"
```

And the generated `agent.yml` secret looks like this:

```
integrations:
...
    gcp_exporter_configs:
        - enabled: true
          gcp_exporter:
            gcp_client_timeout: 15s
            metrics_prefixes:
                - compute.googleapis.com/
                - storage.googleapis.com/
                - redis.googleapis.com/
                - cloudsql.googleapis.com/
                - networking.googleapis.com/
                - loadbalancing.googleapis.com/
                - autoscaler.googleapis.com/
            project_ids:
                - xxx
...
```

### Use case

I want to use grafana agent operator to deploy my grafana agent and be able to export GCP metrics to grafana using gcp_exporter via Integration CR.

**Comment by alhafoudh** [comment]
This is where the `Secret` is generated for the `Integration`: https://github.com/grafana/agent/blob/35772b426af55f344854fb2eaa49e7508d8581d0/pkg/operator/config/templates/agent-integrations.libsonnet#L118

It looks like `gcp_exporter_configs` is not supported in `agent.yml`. According to https://grafana.com/docs/agent/latest/static/configuration/integrations/gcp-exporter-config/ grafana gent support only "singleton" config for the `gcp_exporter` under `integrations.gcp_exporter` not `integrations.gcp_exporter_configs` array.

**Comment by marctc** [comment]
cc @thepalbi @kgeckhart

**Comment by empollard** [comment]
@marctc @thepalbi @kgeckhart 
Just wanted to check on this to see if y'all were able to take a look at it. The customer is wanting to migrate from Datadog ASAP and isn't able to make this work.

Please let me know if it would help to create a Support escalation or if there's anything else I can assist or provide info on.

Thanks!

**Comment by marctc** [comment]
The problem is that config block should be `gcp_configs` intead of `gcp_exporter_configs`. Could you change the `spec > name` to `gcp`?

**Comment by alhafoudh** [comment]
Looks like it got rid of the error message, but I needed to tweak also the Integration config like this:

```
apiVersion: monitoring.grafana.com/v1alpha1
kind: Integration
metadata:
  labels:
    agent: grafana-agent
  name: gcp-exporter
  namespace: grafana
spec:
  name: gcp
  type:
    allNodes: false
    unique: true
  config:
    project_ids:
      - '[REDACTED]'
    gcp_client_timeout: 15s
    metrics_prefixes:
      - compute.googleapis.com/
      - storage.googleapis.com/
      - redis.googleapis.com/
      - cloudsql.googleapis.com/
      - networking.googleapis.com/
      - loadbalancing.googleapis.com/
      - autoscaler.googleapis.com/
```


Now I dont see any error messages in the `grafana-agent-integrations-deploy-xxx-yyy` Pod, but I see no metrics from GCP/stackdriver either.

**Comment by alhafoudh** [comment]
I just got it working by enabling the scraping :)
Thank you for pointing me to the right direction!

This is my final Intergration resource config:
```
apiVersion: monitoring.grafana.com/v1alpha1
kind: Integration
metadata:
  labels:
    agent: grafana-agent
  name: gcp-exporter
  namespace: grafana
spec:
  name: gcp
  type:
    allNodes: false
    unique: true
  config:
    autoscrape:
      enable: true
      metrics_instance: grafana/grafana-agent-metrics
    project_ids:
      - '[REDACTED]'
    gcp_client_timeout: 15s
    metrics_prefixes:
      - compute.googleapis.com/
      - storage.googleapis.com/
      - redis.googleapis.com/
      - cloudsql.googleapis.com/
      - networking.googleapis.com/
      - loadbalancing.googleapis.com/
      - autoscaler.googleapis.com/
```
