### ISSUE TITLE
Helm creating and using default ConfigMap rather than using one already defined

### ISSUE THREAD

**Issue by elburnetto-sky** [grafana/agent#4063]
### What's wrong?

I'm trying to deploy Grafana Agent in Flow Mode on GKE, and have already created a config map:

```
data:
  config.river: |
    otelcol.exporter.otlphttp "OTEL" {
        client {
          endpoint = "<redacted>"
        }
      }
      
      otelcol.receiver.otlp "OTEL" {
        grpc {
          endpoint = "0.0.0.0:4317"
        }

        http {
          endpoint = "0.0.0.0:4318"
        }

        output {
          logs = [otelcol.exporter.loki.OTEL.input]
          traces = [otelcol.exporter.otlphttp.OTEL.input]
        }
      }

      otelcol.exporter.loki "OTEL" {
        forward_to = [loki.write.OTEL.receiver]
      }
      
      loki.write "OTEL" {
        endpoint {
          url = "grafana-loki-loki-distributed-gateway.monitoring.svc.cluster.local/loki/api/v1/push"
        }
      }
```

Within my Helm file, I'm setting the values as so:

```
agent: 
  mode: 'flow'
  configMap:
    create: false
    name: grafana-agent-config
    key: config.river
  extraPorts:
    - name: "faro"
      port: 12347
      targetPort: 12347
      protocol: "TCP"

ingress:
  enabled: true
  annotations:
    no_authgateway: "true"
    kubernetes.to/ingress.class: nginx
  
  hosts:
    - <redacted>
  
  tls:
    - secretName: <redacted>
      hosts:
        - <redacted>
```

However when Helm then executes, the Agent is creating it's own default configMap, rather than using the one defined in Helm Values.

### Steps to reproduce

1. Create a configMap in Kubernetes with the relevant Flow values
2. Amend values.yaml to not create the config map, and to use the configmap already created

### Software version

Grafana Agent v0.33.2 / Helm 0.14.0
