### ISSUE TITLE
Flow: grafana-agent deployed with helm unable to collect node telemetry (prometheus.exporter.unix)

### ISSUE THREAD

**Issue by pcecot** [grafana/agent#4207]
### Discussed in https://github.com/grafana/agent/discussions/3470

<div type='discussions-op-text'>

<sup>Originally posted by **pcecot** April  6, 2023</sup>
agent version: v0.32.1
helm chart: grafana-agent-0.10.0

Collecting the node telemetry using `prometheus.exporter.unix` does not work. I see the following in the container logs:
```
ts=2023-04-06T08:12:50.628942484Z level=error component=prometheus.exporter.unix msg="collector failed" name=systemd duration_seconds=0.000108774 err="couldn't get dbus connection: dial unix /run/systemd/private: connect: no such file or directory"
ts=2023-04-06T08:12:50.634454633Z level=error component=prometheus.exporter.unix collector=ethtool msg="ethtool link info error" err="no such device" device=docker0 errno=19
ts=2023-04-06T08:12:50.63446389Z level=error component=prometheus.exporter.unix collector=ethtool msg="ethtool driver info error" err="no such device" device=docker0 errno=19
ts=2023-04-06T08:12:50.634470465Z level=error component=prometheus.exporter.unix collector=ethtool msg="ethtool stats error" err="no such device" device=docker0 errno=19
ts=2023-04-06T08:12:50.634484609Z level=error component=prometheus.exporter.unix collector=ethtool msg="ethtool link info error" err="no such device" device=ens192 errno=19
ts=2023-04-06T08:12:50.634489309Z level=error component=prometheus.exporter.unix collector=ethtool msg="ethtool driver info error" err="no such device" device=ens192 errno=19
ts=2023-04-06T08:12:50.634494074Z level=error component=prometheus.exporter.unix collector=ethtool msg="ethtool stats error" err="no such device" device=ens192 errno=19
```

Configuration used:

```terraform
      prometheus.exporter.unix {
        set_collectors = ["cpu", "disk", "ethtool", "systemd"]
        procfs_path = "/host/proc"
        sysfs_path = "/host/sys"
        rootfs_path = "/host/root"
      }
```

Helm chart values:
```yaml
controller:
  securityContext:
    privileged: true
    runAsUser: 0 
  volumes:
    extra:
      - name: rootfs
        hostPath:
          path: /
      - name: sysfs
        hostPath:
          path: /sys
      - name: procfs
        hostPath:
          path: /proc
agent:
  mounts:
    dockercontainers: true
    extra: 
      - name: rootfs
        mountPath: /host/root
        readOnly: true
      - name: sysfs
        mountPath: /host/sys
        readOnly: true
      - name: procfs
        mountPath: /host/proc
        readOnly: true
```

Any suggestion what am I missing?</div>

I went back to test it again on latest agent/helm chart version and the problem is still seen. When using grafana-agent in flow mode unix exporter is unable to scrape host metrics.
At the same time running a standalone node exporter on the same k8 cluster scrapes metrics just fine.
