### ISSUE TITLE
'relabel_configs' does not support replacing 'relabel_configs' with' instance ？

### ISSUE THREAD

**Issue by GuridMa** [grafana/agent#4298]
### What's wrong?

![image](https://github.com/grafana/agent/assets/74485252/40d66080-bbea-4933-a261-39fab5898161)
![image](https://github.com/grafana/agent/assets/74485252/03e5b2f3-84f7-43e7-a1a2-2f55192d4c1b)

### Steps to reproduce

config.conf
`
![image](https://github.com/grafana/agent/assets/74485252/38df3827-6ccb-4312-8c74-d3d9d830d062)
`

### System information

centos 7

### Software version

v0.33.2

**Comment by spartan0x117** [comment]
Hey! :wave: The `__address__` label is set to the agent's address inside that `relabel_config`, as the agent is scraping itself in-memory. If you want to set the `instance` label, you should use the `instance` field:
```yaml
  kafka_exporter:
    enabled: true
    kafka_uris:
    - 127.0.0.1:9092
    instance: "127.0.0.1:9092" # Or something else, if needed
```

If you only have one kafka_uri entry, then you should be able to omit the `instance` field in the config and it will populate the `instance` label with the kafka uri.
