### ISSUE TITLE
Timestamp stage not working on windows

### ISSUE THREAD

**Issue by PsySuck** [grafana/agent#4337]
### What's wrong?

I'm trying to use the timestamp stage to change the time of an event. In promtail, the timestamp stage works, but it does not work when transferring the config to Grafana Agent.
<img width="345" alt="Screenshot 2023-07-04 at 12 35 08" src="https://github.com/grafana/agent/assets/87027160/cc6c8fe3-4aed-401e-8323-117431107188">

Inspect in promtail
```
{stages.Entry}.Entry.Entry.Timestamp:
        -: 2023-07-04 14:09:21.986855 +0300 EEST
        +: 2023-07-01 00:00:01 +0300 EEST
```

### Steps to reproduce

1. Install Agent.
2. Add Timestamp with Location and Custom Format
3. Run agent 

### System information

Windows server 2019

### Software version

agent, version v0.34.3 

### Configuration

```text
Promtail:
- job_name: iis-frontend
  static_configs:
    - targets:
        - localhost
      labels:
        __path__: E:\IIS_Logs\W3SVC1\u_ex23*.log
  pipeline_stages:
    - match:
          # Drop lines that are comments (start with #)
        selector: '{service="exchange"} |~ "^#"'
        action: drop
        drop_counter_reason: iis_comment_line
                
    - regex:
        source:
        expression: "^(?P<time>\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}) "
            
    - timestamp:
        source: time
        format: 2006-01-02 15:04:05
        location: Europe/Sofia
Grafana Agent:       
 - job_name: iis-frontend
          static_configs:
            - targets:
                - localhost
              labels:
                service: exchange
                log_type: iis-frontend
                __path__: E:\IIS_Logs\W3SVC1\u_ex*.log
          pipeline_stages:
            - match:
          # Drop lines that are comments (start with #)
                selector: '{service="exchange"} |~ "^#"'
                action: drop
                drop_counter_reason: iis_comment_line
                
            - regex:
                source:
                expression: "^(?P<time>\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}) (?P<csmethod>.+?) (?P<csuristem>.+?) (?P<csuriquery>.+?) (?P<csusername>.+?) (?P<cip>.+?) (?P<useragent>.+?) (?P<cookie>.+?) (?P<scstatus>.+?) (?P<ip>.+?):"
            
            - timestamp:
                source: time
                format: 2006-01-02 15:04:05
                location: Europe/Sofia


            - template:
                source: hostname
                template: ${COMPUTERNAME}

            - template:
                source: hostname
                template: '{{ ToLower .Value }}'
                
            - labels:
                hostname:            
                
                
            - pack:
                labels:
                  - csmethod
                  - csuristem
                  - csuriquery
                  - csusername
                  - cip
                  - useragent
                  - cookie
                  - scstatus
                  - ip
                  - time
```

### Logs

```text
Software: Microsoft Internet Information Services 10.0
#Version: 1.0
#Date: 2023-06-03 00:00:02
#Fields: date time cs-method cs-uri-stem cs-uri-query cs-username c-ip cs(User-Agent) cs(Cookie) sc-status ip
2023-06-02 23:59:31 POST /EWS/Exchange.asmx &CorrelationID=<empty>;&cafeReqId=xxxxxxxxxxxx; xxx\xxx xx.xx.xx.xx AppleExchangeWebServices/xxxxxxxxxxxxx X-BackEndCookie=xxxxxxxxxxxx
```

**Comment by tpaschalis** [comment]
Do all log lines have the same issue? Have you verified that the rest of the regex here (`(?P<csmethod>...` onwards) matches the log lines correctly?

**Comment by tpaschalis** [comment]
Closing the issue as fixed in #4351. The fix will be available in release v0.35 sometime this month, but in the meantime you can build the Agent from main or use our Dockerhub images.

**Comment by PsySuck** [comment]
still reproduced in static mode

**Comment by rfratto** [comment]
Reopening, #4351 was not intended as a fix for this issue, but rather just found as a related problem.

**Comment by mattdurham** [comment]
We have updated Loki so possibly fixed in main and in v0.36

**Comment by Noahnc** [comment]
We use Grafana Agent Flow version 0.38.1 and have the same issue.
Parsing on Windows with a custom format doesn't work.
Is there any update on this?

**Comment by ptodev** [comment]
I'm going to close this because I believe the issue is due to an incorrect regex in the config.

The regex config used in the Promtail file in the issue description is this one:
```yaml
- regex:
  source:
  expression: "^(?P<time>\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}) "
```

The regex config used in the Agent file is this one:
```yaml
- regex:
  source:
  expression: "^(?P<time>\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}) (?P<csmethod>.+?) (?P<csuristem>.+?) (?P<csuriquery>.+?) (?P<csusername>.+?) (?P<cip>.+?) (?P<useragent>.+?) (?P<cookie>.+?) (?P<scstatus>.+?) (?P<ip>.+?):"
            
```

I believe the regex in the Agent config file doesn't work as expected. I tried this out in https://regex101.com/ and you can see that the capture groups are not identified ok:
![Screenshot 2024-02-12 at 16 06 29](https://github.com/grafana/agent/assets/5834788/d3ff6504-7f14-481c-94a3-08f9e0813d63)

A slightly different regex identifies the timestamp, but doesn't work well for other capture groups:
![Screenshot 2024-02-12 at 16 06 59](https://github.com/grafana/agent/assets/5834788/a485feb7-a0b0-42b9-9dce-2c87c7b495bd)

If you are impacted by a similar issue, I'd recommend the following:
* Test your regex in a website such as regex101.com to make sure there is a "time" capture group.
* Enable debug logging on your agent. You might see log lines such as "regex did not match" and "extracted data did not contain a timestamp".

**Comment by PsySuck** [comment]
@ptodev  i disagree with you.
First of all - how to do it _"Enable debug logging on your agent. You might see log lines such as "regex did not match" and "extracted data did not contain a timestamp"._ ?

here is simple example how to reproduce
Config of agent
```
server:
  log_level: debug
metrics:
  wal_directory: C:\ProgramData\grafana-agent\wal
  global:
    scrape_interval: 1m
  configs:
    - name: integrations
integrations:
  windows_exporter:
    enabled: false
logs:
  # Choose a directory to save the last read position of log files at.
  # This directory will be created if it doesn't already exist.
  positions_directory: "C:\\Program Files\\Grafana Agent\\pos\\"
  configs:
    - name: windows
      # Loki endpoint to push logs to
      clients:
        - url: https:/loki/api/v1/push
      scrape_configs:

########################################################

      - job_name: riskdetection
        static_configs:
          - targets:
              - localhost
            labels:
              service: timetest
              __path__: C:\Program Files\Grafana Agent\test.txt
        pipeline_stages:
          - regex:
              source:
              expression: "^(?P<time>\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}) (?P<event>.+)$"
          - timestamp:
              source: time
              format: 2006-01-02 15:04:05
              location: Europe/Sofia
                
          - pack:
              labels:
                - event
                - time
                
          - labeldrop:
              - filename             
```
text.txt:
```
2024-04-12 19:20:05 up
2024-04-12 19:20:06 up
2024-04-12 19:21:05 down
2024-04-12 19:22:05 up_again
2024-04-12 19:22:07 down
2024-04-12 19:22:08 up
2024-04-12 19:24:05 up
2024-04-12 19:25:06 up
2024-04-12 19:26:05 down
2024-04-12 19:27:05 up_again
2024-04-12 19:28:07 down
2024-04-12 19:29:08 up
```
Regex test:
<img width="1465" alt="Screenshot 2024-02-12 at 19 44 09" src="https://github.com/grafana/agent/assets/87027160/f6d1db91-8e91-4bf8-a4bf-50c84ee1ef0e">

Results:
<img width="624" alt="Screenshot 2024-02-12 at 19 47 08" src="https://github.com/grafana/agent/assets/87027160/b52ad466-529c-43eb-b797-8747b7721fc4">
<img width="502" alt="Screenshot 2024-02-12 at 19 46 58" src="https://github.com/grafana/agent/assets/87027160/c64839f7-cc29-4969-b0a2-202e589f1418">

**Comment by ptodev** [comment]
Hi, @PsySuck, thank you for the prompt response! I was able to reproduce the log lines which you posted above.

The reason for the timestamp is that the `ingest_timestamp` config attribute for the `pack` stage defaults to `true`. When `ingest_timestamp` is `true`, the `pack` stage will always set `time.Now()` as the timestamp. This is mentioned in the [Promtail docs](https://grafana.com/docs/loki/latest/send-data/promtail/stages/pack/):

> If the resulting log line should use any existing timestamp or use time.Now() when the line was processed.
> To avoid out-of-order issues with Loki, when combining several log streams (separate source files) into one
> you will want to set a new timestamp on the log line, `ingest_timestamp: true`
> If you are not combining multiple source files or you know your log lines won't have interlaced timestamps
> you can set this value to false.

To retain the previous timestamp, you can configure your `pack` stage like this:

```yaml
- pack:
    ingest_timestamp: false
    labels:
    - event
    - time
```

I will update the docs because they could certainly make this more clear. Thanks a lot for your feedback!

I'll reopen this issue until you confirm that this resolves it for you.
