### ISSUE TITLE
CRD `grafanaagents.monitoring.grafana.com` cannot be deployed because of annotation length

### ISSUE THREAD

**Issue by dangmai** [grafana/agent#4379]
### What's wrong?

I've been using Grafana Agent Helm chart for a while now successfully, but it looks like the latest version can't be deployed because of the annotation length.

Full error is: `one or more objects failed to apply, reason: CustomResourceDefinition.apiextensions.k8s.io "grafanaagents.monitoring.grafana.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes (retried 5 times).`

### Steps to reproduce

Deploy the `grafana-agent-operator` version `0.2.16` using Helm and ArgoCD with this chart:

```
apiVersion: v2
name: grafana

type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: grafana-agent-operator
    version: 0.2.16
    repository: https://grafana.github.io/helm-charts
```

### System information

k3s v1.27.2+k3s1, Linux 5.15.0-73-generic

### Software version

Grafana Agent Operator 0.2.16

### Configuration

```text
# This is my `values.yaml` file used for this Helm chart
grafana-agent-operator:
  kubeletService:
    namespace: grafana
    serviceName: kubelet
```

**Comment by eduanb** [comment]
@dangmai I had the same issue. A workaround is to use server-side apply https://kubernetes.io/docs/reference/using-api/server-side-apply/

**Comment by dangmai** [comment]
@eduanb Thank you for pointing me to that, it leads me down the rabbit hole researching about this issue, and it looks like other charts have run into this before, most prominently this one: https://github.com/prometheus-community/helm-charts/issues/1500 There are some workarounds there for different tools (ArgoCD, pulumi, etc.)

I'll leave it up to the maintainers to decide whether this is a bug or not.

**Comment by eduanb** [comment]
For reference, here is my Argo app that worked and includes the server-side apply

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-agent-operator
  namespace: grafana-agent
spec:
  destination:
    namespace: grafana-agent
    server: https://kubernetes.default.svc
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.2.16
    helm:
      releaseName: grafana-agent-operator
    chart: grafana-agent-operator
    syncOptions:
#      Need server side apply because the resource is too big to fit in 262144 bytes allowed annotation size
      - ServerSideApply=true

```
