### ISSUE TITLE
Update helm chart to support Downloading GeoIP databases

### ISSUE THREAD

**Issue by dwalker-sabiogroup** [grafana/agent#4469]
### Background

[v0.35.0-rc.0](https://github.com/grafana/agent/releases/tag/v0.35.0-rc.0) adds support for `stage.geoip` but https://github.com/oschwald/maxminddb-golang only support loading the GeoIP database from a local path

```
stage.geoip {
  source  = "ip"
  db      = "/path/to/db/GeoLite2-City.mmdb"
  db_type = "city"
}
```

The current helm chart does not provide anyway to enable the database files to be added to the pod file system when created. 

### Proposal

A solution to the problem would be to add https://hub.docker.com/r/maxmindinc/geoipupdate as an optional sidecar that can be responsible for ensuring that the required GeoIP files are available in the pod.

**Comment by dwalker-sabiogroup** [comment]
Rather than using a sidecar I solved this issue by allowing the pod initcontainers to be configurable

```yaml
  initContainers:
      {{- with .Values.initContainers }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
```

I was then able to add the following to my values

```yaml
initContainers:
- name: geo-ip
  image: ghcr.io/maxmind/geoipupdate:v6.0
  volumeMounts:
    - name: geoip
      mountPath: /etc/geoip
  volumes:
  - name: geoip
    emptyDir: {}
  env:
  - name: GEOIPUPDATE_ACCOUNT_ID
    value: "<redacted>"
  - name: GEOIPUPDATE_LICENSE_KEY
    value: "<redacted>"
  - name: GEOIPUPDATE_EDITION_IDS
    value: "GeoLite2-ASN GeoLite2-City GeoLite2-Country"
  - name: GEOIPUPDATE_DB_DIR
    value: "/etc/geoip"
controller:
  volumes:
    extra:
      - name: geoip
        mountPath: /etc/geoip
agent:
  mounts:
    extra:
      - name: geoip
        mountPath: /etc/geoip
```

Which stores the DB files locally in the pod.

```shell
ls -lh /etc/geoip
total 82M
-rw-r--r-- 1 root root 7.9M Jul 17 18:40 GeoLite2-ASN.mmdb
-rw-r--r-- 1 root root  68M Jul 17 18:40 GeoLite2-City.mmdb
-rw-r--r-- 1 root root 5.9M Jul 17 18:41 GeoLite2-Country.mmdb
```

The main pain with this approach is that the database files need to be downloaded each time the containers are restarted but works for my use-case.
