### ISSUE TITLE
Tempo: Support Mirroring a traffic pipeline

### ISSUE THREAD

**Issue by joe-elliott** [grafana/agent#466]
Tempo currently allows multiple independent pipelines, but it would be nice if we could also add the ability to mirror a single pipeline to two different backends.  The underlying OTel Collector technology supports this so it would simply be a matter of setting up the correct configuration.

Here is an example mirrored pipeline configuration:
```
receivers:
  jaeger:
    protocols:
      grpc:
exporters:
  otlp:
    endpoint: example.com:12345
  otlp/2:
    endpoint: otherexample.com:12345
service:
  pipelines:
    traces:
      exporters: ["otlp","otlp/2"]
      processors: []
      receivers: ["jaeger"]
```
