### ISSUE TITLE
Flow mode creates duplicate scrape configs for `ServiceMonitor` in some scenarios

### ISSUE THREAD

**Issue by braunsonm** [grafana/agent#4707]
### What's wrong?

It seems that when you use `targetPort` with the flow component `prometheus.operator.servicemonitor`, you will get duplicate scrape configurations added which point to container ports that do not expose metrics.

You can work around this by changing your `ServiceMonitor` to use `port` with a string value instead of `targetPort` with a integer value.

### Steps to reproduce

You can deploy the `cert-manager` helm chart or create a `ServiceMonitor` which uses `targetPort` targeting a container that has more than one container port

```yaml
apiVersion: monitoring.coreos.com/v1                                                                                                                         
kind: ServiceMonitor                                                                                                                                         
metadata:                                                                                                                                                                                                                                                                   
  name: cert-manager                                                                                                                                         
  namespace: cert-manager                                                                                                                                
spec:                                                                                                                                                        
  endpoints:                                                                                                                                                 
  - honorLabels: false                                                                                                                                       
    interval: 60s                                                                                                                                            
    path: /metrics                                                                                                                                           
    targetPort: 9402                                                                                                              
    scrapeTimeout: 30s                                                                                                                                       
  jobLabel: cert-manager                                                                                                                                     
  selector:                                                                                                                                                  
    matchLabels:                                                                                                                                             
      app.kubernetes.io/component: controller                                                                                                                
      app.kubernetes.io/instance: cert-manager                                                                                                               
      app.kubernetes.io/name: cert-manager    
```

What you'll see is even though we are targeting port `9402` specifically, if the container has any other container ports exposed they will also be added as scrape configuration to Mimir. You will see duplicate endpoints when you query and of course one will be down (in this change the one that has instance `9403`, a container port) because no metrics are meant to be scraped there.

![image](https://github.com/grafana/agent/assets/5280764/921876cc-91ec-438e-a832-f8a806c8a955)


### System information

_No response_

### Software version

0.35.2

### Configuration

```text
N/A
```


### Logs

```text
N/A
```
