### ISSUE TITLE
Grafana-agent-operator: ability to run Integration as a StatefulSet

### ISSUE THREAD

**Issue by james-callahan** [grafana/agent#4763]
### Request

When trying to run `eventhandler` as a logs integration, we need a volume to store the event cache.
I'm creating this with a PVC and attaching it to the `Integration`:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-agent-eventhandler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: monitoring.grafana.com/v1alpha1
kind: Integration
metadata:
  name: eventhandler
  labels:
    grafana-agent: logs
spec:
  config:
    cache_path: /etc/eventhandler/eventhandler.cache
    logs_instance: default/grafana-agent-logs
  name: eventhandler
  type:
    unique: true
  volumeMounts:
    - mountPath: /etc/eventhandler
      name: eventhandler-cache
  volumes:
    - name: eventhandler-cache
      persistentVolumeClaim:
        claimName: grafana-agent-eventhandler
```

However, the integration runs as a `Deployment`, and when a new pod comes up (e.g. due to other changes such as a new grafana agent version), then the new pod comes up but is unable to mount the volume as it is already in use.

My first preference would be to be have the integration as a `StatefulSet` instead.

Second prize would be to at least be able to set the `Deployment`'s `strategy.type` to `Recreate` instead of the default of `RollingUpdate`.

### Use case

Stateful integrations.
