### ISSUE TITLE
Getting did not find expected key in deploying the Grafana cloud agent pod

### ISSUE THREAD

**Issue by saaish** [grafana/agent#477]
I have configured the remote write url correctly and all the parameters are specified correctly. However my pod enters a crash loop with the message
error loading config file /etc/agent/agent.yml: yaml: line 10: did `not` find expected key
Attached is the ConfigMap

```
[cm.txt](https://github.com/grafana/agent/files/6183262/cm.txt)

```

**Comment by rfratto** [comment]
Hey there, I suspect the problem is your `scrape_configs` are outdented which is throwing off the YAML parser:

```yaml
 # notice how the first entry is at a higher indentation level than scrape_configs, where it should instead be at equal or lower indentation
        scrape_configs:
  - job_name: 'appmesh-envoy'
    metrics_path: /stats/prometheus
    kubernetes_sd_configs:
    - role: pod
 # etc
```

should be:

```yaml
        scrape_configs:
        - job_name: 'appmesh-envoy'
          metrics_path: /stats/prometheus
          kubernetes_sd_configs:
          - role: pod
        # etc
```
