### ISSUE TITLE
Agent spanmetric generation does not include Exemplar support

### ISSUE THREAD

**Issue by hedss** [grafana/agent#4785]
### What's wrong?

The spanmetrics processor from the OpenTelemetry Collector project is used to generate spanmetrics for given traces if configured. The processor includes generating exemplars that are attached to histograms (such as `traces_spanmetrics_latency_bucket`). In Tempo/GCT/GET, this processor is also utilised and histograms produce exemplars that can be written to Mimir/GCM/GEM. 

However, it appears that the agent does not produce exemplars when spanmetric generation is configured within it.
There are situations where it is preferable to use the Agent for spanmetric generation, particularly in cases where tail sampling is required, but a full view RED view of all spans is required for the entire system.

Note that general metrics passthrough does work, metrics scraped with pre-existing exemplars by the Agent are written with this information passed on to a remote Mimir/GCM/GEM endpoint.

### Steps to reproduce

1. Configure the Agent to produce spanmetrics, for example:
```yaml
      spanmetrics:
        metrics_instance: <endpoint>
      service_graphs:
        enabled: true
```
2. Ensure that the endpoint used for metrics remote writing has exemplar support configured:
```yaml
  global:
    remote_write:
      - url: <metrics_endpoint>
        send_exemplars: true
```
3. Send traces into the Agent, and then visualise with a suitable PromQL query in Grafana (ensuring exemplar support is enabled), for example:
```
histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{}[1m])) by (le))
```

You can also recreate this using https://github.com/grafana/intro-to-mlt/ by removing the comments from the static configutation here: https://github.com/grafana/intro-to-mlt/blob/main/agent/config.yaml#L147 
and commenting out the relevant section producing spanmetrics in Tempo here: https://github.com/grafana/intro-to-mlt/blob/main/tempo/tempo.yaml#L56 

### System information

Docker on MacOS 12.6.8 (21G725)

### Software version

Grafana Agent 0.35.3 (but also versions tested as far back as 0.32.0)

### Configuration

```yaml
spanmetrics:
        metrics_instance: <endpoint>
      service_graphs:
        enabled: true
```
```yaml
  global:
    remote_write:
      - url: <metrics_endpoint>
        send_exemplars: true
```
