### ISSUE TITLE
Inconsistent behavior of the Config Management API

### ISSUE THREAD

**Issue by jtyr** [grafana/agent#500]
I would like to load individual configurations via [Config Management API](https://github.com/grafana/agent/blob/main/docs/api.md#config-management-api) but I have difficulties to make it to work. This is how I install and configure the Agent (using [this Agent Helm chart](https://github.com/grafana/helm-charts/pull/354)):

```
# Install ETCD
cat <<END | helm upgrade --create-namespace --namespace grafana-agent --install --values - etcd bitnami/etcd
persistence:
  enabled: false
auth:
  rbac:
    enabled: false
END

# Install Agent
cat <<END | helm upgrade --create-namespace --namespace grafana-agent --values - --install agent . 
fullnameOverride: agent

_etcd: &etcd
  endpoints:
    - etcd:2379

_kvs: &kvs
  store: etcd
  etcd: *etcd

_ss: &ss
  enabled: true
  lifecycler:
    ring:
      replication_factor: 1
      kvstore: *kvs

_secret: &secret
  data:
    password: cdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZZYXWVUTSRQPONMLKJIHGFEDCBAzyxwvutsrqponmlkjihgfedc

agentLogs:
  secret: *secret
  urlConfig:
    username: 12345

agentMetrics:
  extraArgs:
    - "-log.level=debug"
  scrapingServiceDeployment:
    <<: *ss
    kvstore:
      <<: *kvs
      prefix: configurations/deployment/
  scrapingService:
    <<: *ss
    kvstore:
      <<: *kvs
      prefix: configurations/metrics/
  secret: *secret

agentTraces:
  secret: *secret
  pushConfig:
    username: 67890
END
```

Then I create configuration files:

```yaml
# default.yaml
host_filter: false
remote_write:
  - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: 45678
      password_file: /var/run/secrets/grafana.com/agent/password
scrape_configs:
  - job_name: agent-metrics
    kubernetes_sd_configs:
      - namespaces:
          names:
            - grafana-agent
        role: pod
    relabel_configs:
      - action: keep
        regex: "^(logs|metrics|traces)$"
        source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_component
  - job_name: default/kubernetes
    kubernetes_sd_configs:
      - role: endpoints
    metric_relabel_configs:
      - action: keep
        regex: workqueue_queue_duration_seconds_bucket|process_cpu_seconds_total|process_resident_memory_bytes|workqueue_depth|rest_client_request_duration_seconds_bucket|workqueue_adds_total|up|rest_client_requests_total|apiserver_request_total|go_goroutines
        source_labels:
          - __name__
    relabel_configs:
      - action: keep
        regex: apiserver
        source_labels:
          - __meta_kubernetes_service_label_component
    scheme: https
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: false
      server_name: kubernetes

# test-app.yaml
host_filter: false
remote_write:
  - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: 45678
      password_file: /var/run/secrets/grafana.com/agent/password
scrape_configs:
  - job_name: test-app
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - test-app
```

Then I load the configuration:

```shell
# Forward port to the `deployment` container
kubectl port-forward -n grafana-agent $(kubectl get pod -l app.kubernetes.io/component=metrics-deployment -o name -n grafana-agent | head -n1) 8080:8080

# Upload configs
curl -v -X POST --data-binary @$PWD/default.yaml localhost:8080/agent/api/v1/config/default
curl -v -X POST --data-binary @$PWD/test-app.yaml localhost:8080/agent/api/v1/config/test-app
```

I can see both configs via `/agent/api/v1/configs` but I sometimes I can see targets (`/agent/api/v1/targets`) only for one of the configs. The same configuration work just fine if I configure it statically:

```yaml
cat <<END | helm upgrade --create-namespace --namespace grafana-agent --values - --install agent . 
fullnameOverride: agent

_secret: &secret
  data:
    password: cdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZZYXWVUTSRQPONMLKJIHGFEDCBAzyxwvutsrqponmlkjihgfedc

agentLogs:
  secret: *secret
  urlConfig:
    username: 12345

agentMetrics:
  secret: *secret
  remoteAuthConfig:
    username: 45678
  extraDeploymentDefaultScrapeConfig:
    - job_name: test-app
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
              - test-app

agentTraces:
  secret: *secret
  pushConfig:
    username: 67890
END
```

Sometimes restart of the `deployment` container (`kubectl delete pod -l app.kubernetes.io/component=metrics-deployment`) loads no configuration at all. Deleting the configs and uploading them again doesn't help. Only deleting the configs, restarting the container and uploading the configs again helps sometimes.

When I tried to debug it, I have noticed that the [`owned` parameter](https://github.com/grafana/agent/blob/main/pkg/prom/cluster/config_watcher.go#L207) in the `configWatcher` is set to `false` for one of the configs, sometimes it's `true` for both but still no targets are shown.

Do you have any idea what could be wrong?
