### ISSUE TITLE
Support write_relabel_configs at push_config level

### ISSUE THREAD

**Issue by ponson-thankavel-finastra** [grafana/agent#502]
**Background:** Our K8s cluster is used by multiple tenants (separated by namespaces). We maintain a grafana cloud stack for each of the tenants. We need to collect traces for tenants and stream to respective grafana cloud stack. All tenant applications will send their traces to same endpoint "localhost:55680". 

**Ask:** Is it possible to support write_relabel_configs as part of push_config? below config example illustrates the requirement. grafana agent for metrics & logs support similar configuration. 

```
tempo:
  configs:
    - name: tempo-config
       push_config: 
        - name: tenant1
          basic_auth:
            username: 12345
            password_file: /etc/agent/secrets/tenant1/password
          endpoint: tempo-us-central1.grafana.net
          write_relabel_configs:
            - action: keep
              regex: tenant1-ns1|tenant1-ns2
              source_labels:
                - namespace
        - name: tenant2
          basic_auth:
            username: 45678
            password_file: /etc/agent/secrets/tenant1/password
          endpoint: tempo-us-central1.grafana.net
          write_relabel_configs:
            - action: keep
              regex: tenant2-ns1|tenant2-ns2
              source_labels:
                - namespace
      receivers:
        otlp:
          protocols:
            grpc: 
              endpoint: "localhost:55680"
      scrape_configs:
        - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
```
