### ISSUE TITLE
node_exporter integration metrics not being scraped

### ISSUE THREAD

**Issue by gerhard** [grafana/agent#515]
Given K8S v1.20.5 & grafana-agent v0.13.0 + #497 (adds a missing namespace):
* node_exporter is enabled
* metrics are available via `/integrations/node_exporter/metrics`
* `scrape_integration: true` is set on the node_exporter integration

`node_exporter` metrics **do not** appear in Grafana Cloud. What did I miss?

This is the exact config: https://github.com/thechangelog/changelog.com/commit/fc394ff48d078aac1c6e4cc326999eff7e66199e#diff-f8ff18f3577d75cca85ef0278edf268d3ee16195375a1783aa0930d79ed3d7d9R11-R14

**Comment by rfratto** [comment]
👋 Integrations [currently require their own remote_write settings](https://github.com/grafana/agent/blob/main/docs/configuration-reference.md#integrations_config), independent of remote_write configured in the `prometheus` block. We're introducing a global remote_write configuration in the next release, but 0.13.0 doesn't have that change. 

```yaml
integrations:
  node_exporter: 
    enabled: true
  prometheus_remote_write:
    - url: https://some-url
      # etc 
```
