### ISSUE TITLE
Grafana Agent SNMP V3

### ISSUE THREAD

**Issue by brngates98** [grafana/agent#5294]
### What's wrong?

SNMP V3 Does not seem to work via the grafana agent

### Steps to reproduce
```
snmp:
  enabled: true
  relabel_configs:
    - action: replace
      source_labels: [job]
      regex: (^.*snmp)\/(.*)
      target_label: job_snmp
      replacement: $1
    - action: replace
      source_labels: [job]
      regex: (^.*snmp)\/(.*)
      target_label: snmp_target
      replacement: $2
  snmp_targets:
    - name: network_switch_1
      address: 'switch1'
      module: if_mib
      version: 3  # Specify SNMP version 3
      auth:
        username: 'username'
        password: 'password'
        auth_protocol: SHA  # Use the appropriate authentication protocol (SHA or MD5)
        privacy_password: 'password'
        privacy_protocol: DES  # Use the appropriate privacy protocol (AES or DES)
      timeout: 5s  # Specify the SNMP timeout
      retries: 3   # Specify the number of SNMP retries
  metric_relabel_configs:
    - action: keep
      regex: ifHCInOctets|ifHCOutOctets|ifInErrors|ifMtu|ifOperStatus|ifOutErrors|ifPhysAddress|ifSpeed|ifType_info|snmp_scrape_duration_seconds|sysUpTime
      source_labels:
        - __name__
```

### Configuration

```text
Grafana Agent attempting to use it to collect snmp if_mib stats
```
