### ISSUE TITLE
Creation of prometheus rules via mimir.kubernetes.rules component fails in grafana cloud.

### ISSUE THREAD

**Issue by marioanton** [grafana/agent#5413]
### What's wrong?

When creating rules based of PrometheusRule resource using mimir.kubernetes.rules component in grafana agent mode FLOW we receive unexpected response failing to create the rule.
The issue is with parsing the data returned by api/v1/rules endpoint.

Grafana agent flow mode config:

```
mimir.rules.kubernetes "default" {
  address = grafanaCloudPrometheusBaseUrl + "/api/prom"
  use_legacy_routes = true

  basic_auth {
      username = user
      password = password
  }
}
}
```
Prometheus rule
```

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-k8s-rules
spec:
  groups:
  - name: host
    rules:
    - alert: high_cpu_load
      expr: node_load1 > 1.5
      for: 30s
      labels:
        severity: warning
      annotations:
        summary: "Server under high load"
        description: "Cpu host is under high load, the avg load 1m is at {{ $value}}. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."%

```

Error retrieved:
```
component evaluation failed: updating component: yaml: unmarshal errors: line 1: cannot unmarshal !!str `success` into []rulefmt.RuleGroup line 1: cannot unmarshal !!map into []rulefmt.RuleGroup line 1: cannot unmarshal !!str `` into []rulefmt.RuleGroup line 1: cannot unmarshal !!str `` into []rulefmt.RuleGroup
```

Manual api query returning this section of payload which makes me thing is not parsing rule groupts it properly and just grabs the whole result:
```
{
    "status": "success",
    "data": {
        "groups": [................
```

### Steps to reproduce

Use the config above against grafana cloud 

### Software version

0.36.2

### Configuration

```text
Grafana agent flow mode config:

`mimir.rules.kubernetes "default" {
  address = grafanaCloudPrometheusBaseUrl + "/api/prom"
  use_legacy_routes = true

  basic_auth {
      username = user
      password = password
  }
}
}
 `
Prometheus rule
`

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-k8s-rules
spec:
  groups:
  - name: host
    rules:
    - alert: high_cpu_load
      expr: node_load1 > 1.5
      for: 30s
      labels:
        severity: warning
      annotations:
        summary: "Server under high load"
        description: "Cpu host is under high load, the avg load 1m is at {{ $value}}. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."%

`
```

### Logs

```text
component evaluation failed: updating component: yaml: unmarshal errors: line 1: cannot unmarshal !!str `success` into []rulefmt.RuleGroup line 1: cannot unmarshal !!map into []rulefmt.RuleGroup line 1: cannot unmarshal !!str `` into []rulefmt.RuleGroup line 1: cannot unmarshal !!str `` into []rulefmt.RuleGroup
```
