### ISSUE TITLE
Use of extraPorts in helm chart breaks install

### ISSUE THREAD

**Issue by moxious** [grafana/agent#5575]
### What's wrong?

This: `helm install agent grafana/grafana-agent --values agent/config.yaml`

given this config.yaml:

```
agent:
  mode: flow
  extraPorts:
  - "4317"
  - "4318"

  envFrom: 
  - secretRef:
      name: grafana-cloud-token

  configMap:
    create: false
    name: agent-config-river
```

Fails to install with this error:

```
$ helm template agent grafana/grafana-agent --values agent/config.yaml
Error: template: grafana-agent/templates/controllers/daemonset.yaml:16:8: executing "grafana-agent/templates/controllers/daemonset.yaml" at <include "grafana-agent.pod-template" .>: error calling include: template: grafana-agent/templates/controllers/_pod.yaml:33:8: executing "grafana-agent.pod-template" at <include "grafana-agent.container" .>: error calling include: template: grafana-agent/templates/containers/_agent.yaml:44:32: executing "grafana-agent.container" at <$portMap.targetPort>: can't evaluate field targetPort in type interface {}
```

Which looks related to some other template's selection of `targetPort`.  This same config without the "extraPorts" works fine, but I'm attempting to expose these ports for http/grpc endpoints for otel collection (perhaps I'm going about this wrong, not sure).

River config in use is this (but I don't think this is related to the issue, just including for completeness)

```
module.git "grafana_cloud" {
  repository = "https://github.com/grafana/agent-modules.git"
  path = "modules/grafana-cloud/autoconfigure/module.river"
  revision = "main"
  pull_frequency = "0s"
  arguments {
    stack_name = "moxious"
    token = env("GRAFANA_CLOUD_TOKEN")
  }
}

otelcol.exporter.prometheus "to_prometheus" {
  forward_to = [
    module.git.grafana_cloud.exports.metrics_receiver,
  ]
}

otelcol.exporter.loki "to_loki" {
  forward_to = [
    module.git.grafana_cloud.exports.logs_receiver,
  ]
}

otelcol.receiver.otlp "default" {
  grpc {}
  http {}
  output {
    metrics = [otelcol.exporter.prometheus.to_prometheus.input]
    logs = [otelcol.exporter.loki.to_loki.input]
    traces = [module.git.grafana_cloud.exports.traces_receiver]
  }
}

logging {
  level  = "debug"
  format = "logfmt"
}
```

### Steps to reproduce

See above

### System information

GKE

### Software version

helm chart grafana-agent-0.27.0

### Configuration

```text
see above
```

**Comment by moxious** [comment]
Extra ports docs link that led me down this path: https://github.com/grafana/agent/tree/911021c6dc7dd6bfa71ae7724403d5f68980f2cb/operations/helm/charts/grafana-agent#values

**Comment by petewall** [comment]
The elements inside the `.extraPorts` field should be in proper Kubernetes port definition style. So something like this is probably what it's expecting:
```
agent:
  extraPorts:
      - name: "otlp-grpc"
        port: 4317
        targetPort: 4317
        protocol: "TCP"
      - name: "otlp-http"
        port: 4318
        targetPort: 4318
        protocol: "TCP"
```
