### ISSUE TITLE
github_exporter: fields mismatch between exporter and dashboards

### ISSUE THREAD

**Issue by ahpook** [grafana/agent#5579]
### What's wrong?

When adding the `github_exporter` integration to the agent and installing the bundled dashboards, the **Open Pull Requests** dashboard is empty. This is because the query for the metrics is filtering on fields `user` and `repo` (i.e. `github_repo_pull_request_count{user="grafana",repo="agent"}`) but the metric is not exported into prometheus with a `user` field.

It looks like the dashboard end of things expects the change in [this PR](https://github.com/githubexporter/github-exporter/pull/63) to exist in the data model, but the exporter is not updated to add that key. Maybe this is a result of #5289 ?

### Steps to reproduce

* Install the GitHub integration as [described in the docs](https://grafana.com/docs/grafana-cloud/monitor-infrastructure/integrations/integration-reference/integration-github/)
* Note the **Open Pull Requests** table is empty
* Edit the dashboard and using the data explorer, browse to the `github_repo_pull_request_count` metric, and note the only filterable field on it is `repo`.
* Remove the `user=$user` filter from the query and note the data now shows up correctly.

As an aside there are additional metrics that would be great to have in this integration (as #1845 mentioned), but it's very unclear where to put a PR right now

### Software version

grafana-agent-0.37.2-1

### Configuration

```
integrations:
  prometheus_remote_write:
  - basic_auth:
      password: glc_XXX
      username: 111
    url: https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push
  agent:
    enabled: true
    relabel_configs:
    - action: replace
      source_labels:
      - agent_hostname
      target_label: instance
    - action: replace
      target_label: job
      replacement: "integrations/agent-check"
    metric_relabel_configs:
    - action: keep
      regex: (prometheus_target_.*|prometheus_sd_discovered_targets|agent_build.*|agent_wal_samples_appended_total|process_start_time_seconds)
      source_labels:
      - __name__
  github_exporter:
    enabled: true
    api_token: 'github_pat_XXX'
    repositories:
    - cli/cli
    relabel_configs:
    - replacement: 'ahpook-test'
      target_label: instance
    metric_relabel_configs:
    - action: keep
      regex: github_rate_limit|github_rate_remaining|github_repo_forks|github_repo_open_issues|github_repo_pull_request_count|github_repo_size_kb|github_repo_stars|github_repo_watchers
      source_labels:
      - __name__

```
