### ISSUE TITLE
CPU/memory ussage of grafana agent flow windows

### ISSUE THREAD

**Issue by ToonTijtgat2** [grafana/agent#5599]
### What's wrong?

Dear

We're starting to use the grafana agent flow mode to collect logs on windows vm's. With logs I mean textfiles, and windows event logs.
I noticed that the cpu usage and memory stay normal (0.1% of 16 cpu/65 MB) aslong as we do one of the 2 thing, so or textfiles or windows events.

from the moment we try to sent the 2 types of logs togehter, the cpu goes to (25% of 16 cpu/800MB).

Currently we are sending the textfiles and windows event to an other tenant_id. but even if I sent it to the same loki write component, the behaviour is the same.

So to conclude, I observer that from the moment there are 2 different loki sources (loki.source.file and loki.source.windowsevent) the cpu and memory of the agent spike.

Thanks for investigating.

### Steps to reproduce

create the grafana agent flow setup on a windows vm with the config specified in the configuration section.
Have the agent monitor files and windows events.

### System information

Windows server 2022 version 21H2

### Software version

Grafana agent flow v0.37.2

### Configuration

```text
// Logging
logging {
  level = "error"
}

// filebeat logs
loki.write "logs_iis" {
	endpoint {
		url       = "https://logs-ingester.man.dev.azure.fluxys.net/loki/api/v1/push"
		tenant_id = "logging-onprem-dev3"
	}
	external_labels = {
		environment = env("Environment"),
		instance    = env("COMPUTERNAME"),
		tenant      = env("Tenant"),
	}
}

// iis log files
local.file_match "logs_iis_iis" {
	path_targets = [{
		__address__ = "localhost",
		__path__    = "E:\\Log\\IIS\\*\\*\\*.log",
		job         = "iis",
	}]
}

loki.source.file "logs_iis_iis" {
	targets    = local.file_match.logs_iis_iis.targets
	forward_to = [loki.process.logs_iis_iis.receiver]
}

loki.process "logs_iis_iis" {
	forward_to = [loki.write.logs_iis.receiver]

	stage.match {
		selector = "{job=\"iis\"}"

		stage.regex {
			expression = "E:\\\\Log\\\\IIS\\\\(?P<application>[^\\\\]+)\\\\"
			source     = "filename"
		}

		stage.labels {
			values = {
				application = null,
			}
		}
	}
}

// application logs
local.file_match "logs_iis_applicationlog" {
	path_targets = [{
		__address__ = "localhost",
		__path__    = "E:\\Log\\*\\*\\*.log",
		job         = "applicationlog",
	}]
}

loki.source.file "logs_iis_applicationlog" {
	targets    = local.file_match.logs_iis_applicationlog.targets
	forward_to = [loki.process.logs_iis_applicationlog.receiver]
}

loki.process "logs_iis_applicationlog" {
	forward_to = [loki.write.logs_iis.receiver]

	stage.match {
		selector = "{job=\"applicationlog\"}"

		stage.regex {
			expression = "E:\\\\Log\\\\(?P<application>[^\\\\]+)\\\\"
			source     = "filename"
		}

		stage.labels {
			values = {
				application = null,
			}
		}
	}

	stage.regex {
		expression = "^(?s)(?P<time>\\S+?) "
	}

	stage.timestamp {
		source = "time"
		format = "RFC3339Nano"
	}
}

// winlogbeat
loki.source.windowsevent "logs_winlogbeat_winlogapplication" {
	eventlog_name          = "Application"
	poll_interval          = "0s"
	exclude_event_data     = true
	use_incoming_timestamp = true
	forward_to             = [loki.write.logs_winlogbeat.receiver]
}

loki.source.windowsevent "logs_winlogbeat_winlogsystem" {
	eventlog_name          = "System"
	poll_interval          = "0s"
	exclude_event_data     = true
	use_incoming_timestamp = true
	forward_to             = [loki.write.logs_winlogbeat.receiver]
}

loki.source.windowsevent "logs_winlogbeat_winlogsec" {
	eventlog_name          = "Security"
	poll_interval          = "0s"
	exclude_event_data     = true
	use_incoming_timestamp = true
	forward_to             = [loki.write.logs_winlogbeat.receiver]
}

loki.write "logs_winlogbeat" {
	endpoint {
		url       = "https://logs-ingester.man.dev.azure.fluxys.net/loki/api/v1/push"
		tenant_id = "winlogbeat-onprem-dev"
	}
	external_labels = {
		environment = env("Environment"),
		instance    = env("COMPUTERNAME"),
		tenant      = env("Tenant"),
	}
}

// windows exporter integration
prometheus.exporter.windows "integrations_windows_exporter" {
	enabled_collectors = ["cpu", "cs", "logical_disk", "net", "os", "service", "system", "textfile"]

	text_file {
		text_file_directory = "C:\\Program Files\\Grafana Agent"
	}
}
```

**Comment by ToonTijtgat2** [comment]
FYI, I tried to do the same with the grafana agent (not flow) here the behaviour is even worse.
28% CPU and 2.855 GB memory.

used config for grafana agent is the following:
```
server:
  log_level: info
logs:
  positions_directory: E:\Log\metrics_scraping
  configs:
    - name: iis
      clients:
        - url: https://logs-ingester.man.dev.azure.fluxys.net/loki/api/v1/push
          tenant_id: logging-onprem-dev3
          external_labels:
            instance: "${COMPUTERNAME}"
            tenant: "${Tenant}"
            environment: "${Environment}"
      scrape_configs:
        - job_name: iis
          static_configs:
            - targets:
              - localhost
              labels:
                job: iis
                __path__: 'E:\Log\IIS\*\*\*.log'
          pipeline_stages:
          - match:
              selector: '{job="iis"}'
              stages:
              - regex:
                  source: filename
                  expression: 'E:\\Log\\IIS\\(?P<application>[^\\]+)\\'
              - labels:
                  application:
        - job_name: application
          static_configs:
            - targets:
              - localhost
              labels:
                job: application
                __path__: 'E:\Log\*\*\*.log'
          pipeline_stages:
          - match:
              selector: '{job="application"}'
              stages:
              - regex:
                  source: filename
                  expression: 'E:\\Log\\(?P<application>[^\\]+)\\'
              - labels:
                  application:
    - name: winlog
      clients:
        - url: https://logs-ingester.man.dev.azure.fluxys.net/loki/api/v1/push
          tenant_id: winlogbeat-onprem-dev
          external_labels:
            instance: "${COMPUTERNAME}"
            tenant: "${Tenant}"
            environment: "${Environment}"
      scrape_configs:
        - job_name: windows
          windows_events:
            bookmark_path: E:\Log\bookmark.xml
            use_incoming_timestamp: true
            eventlog_name: "Application"
        - job_name: security
          windows_events:
            bookmark_path: E:\Log\bookmark.xml
            use_incoming_timestamp: true
            eventlog_name: "Security"
        - job_name: system
          windows_events:
            bookmark_path: E:\Log\bookmark.xml
            use_incoming_timestamp: true
            eventlog_name: "System"

        

integrations:
  windows_exporter:
    enabled: true
    enabled_collectors: cpu,cs,logical_disk,net,os,service,system,textfile
    text_file:
      text_file_directory: 'C:\Program Files\Grafana Agent'
```
