### ISSUE TITLE
Accessing non-existent fields in `remote.kubernetes.configmap` or `remote.kubernetes.secret` throws an error

### ISSUE THREAD

**Issue by petewall** [grafana/agent#5615]
### Steps to reproduce

If I have a secret like this...
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: prometheus
data:
  username: cHJvbXVzZXI=
```

And I try to use it like this...
```river
remote.kubernetes.secret "credentials" {
  namespace = "monitoring"
  name = "prometheus"
}

prometheus.remote_write "default" {
  endpoint {
    url = "http://prom.example.com"
    basic_auth {
      username = coalesce(remote.kubernetes.secret.credentials.data["username"], "defaultusername")
      password = coalesce(remote.kubernetes.secret.credentials.data["password"], "defaultpassword")
    }
  }
}
```

Instead of the empty secret fields `coalesce`'ing to the defaults, I get an error message:

```
│ grafana-agent Error: /etc/agent/config.river:342:97: field "password" does not exist
```
