### ISSUE TITLE
Agent not tailing after migration from Promtail

### ISSUE THREAD

**Issue by mplewis** [grafana/agent#567]
Hello, I am trying to migrate my config from a working Promtail installation to a Grafana Agent installation in my Kubernetes cluster.

I installed this agent following the [example manifest](https://github.com/grafana/agent/blob/44bc96d7839fd95451c7045fc32883cf436983ba/production/kubernetes/agent.yaml). It is currently sending Prometheus metrics to Grafana Cloud and discovering pods using the Prometheus config, so I am fairly certain its cluster role bindings and permissions are correct for pod/log discovery.

I copied my working Promtail config into my Agent config under key `loki` using [these directions](https://github.com/grafana/agent/blob/main/docs/getting-started.md#loki-configmigrating-from-promtail). When that didn't work, I tried stripping my `loki` config down to ensure it was not dropping anything it can scrape. However, it looks like everything the Agent can find ends up dropped or delabeled, and it doesn't find any data to send to the backend.

Hopefully this is an issue with my configuration. Please let me know if you see anything I can try or if you need more specific information.

Below are the agent logs:

```
level=info ts=2021-04-28T03:04:56.662650977Z caller=server.go:229 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"
level=debug ts=2021-04-28T03:04:56.674882368Z caller=instance.go:268 agent=prometheus instance=2a042b27535dfb9eb2df65212baacc99 msg="initializing instance" name=2a042b27535dfb9eb2df65212baacc99
level=info ts=2021-04-28T03:04:56.695402794Z caller=wal.go:173 agent=prometheus instance=2a042b27535dfb9eb2df65212baacc99 msg="replaying WAL, this may take a while" dir=/tmp/agent/data/2a042b27535dfb9eb2df65212baacc99/wal
level=info ts=2021-04-28T03:04:56.696055241Z caller=wal.go:220 agent=prometheus instance=2a042b27535dfb9eb2df65212baacc99 msg="WAL segment loaded" segment=0 maxSegment=0
level=info ts=2021-04-28T03:04:56.696716868Z caller=kubernetes.go:264 agent=prometheus instance=2a042b27535dfb9eb2df65212baacc99 component="discovery manager" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=debug ts=2021-04-28T03:04:56.698568782Z caller=manager.go:195 agent=prometheus instance=2a042b27535dfb9eb2df65212baacc99 component="discovery manager" msg="Starting provider" provider=kubernetes/0 subs=[kubernetes-pods]
level=debug ts=2021-04-28T03:04:56.698889335Z caller=instance.go:605 agent=prometheus instance=2a042b27535dfb9eb2df65212baacc99 msg="creating host filterer" for_host=default-8yeni
ts=2021-04-28T03:04:56.699898834Z caller=dedupe.go:112 agent=prometheus instance=2a042b27535dfb9eb2df65212baacc99 component=remote level=info remote_name=2a042b-96a2d3 url=https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push msg="Starting WAL watcher" queue=2a042b-96a2d3
ts=2021-04-28T03:04:56.700132079Z caller=dedupe.go:112 agent=prometheus instance=2a042b27535dfb9eb2df65212baacc99 component=remote level=info remote_name=2a042b-96a2d3 url=https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push msg="Starting scraped metadata watcher"
level=debug ts=2021-04-28T03:04:56.700736933Z caller=instance.go:349 agent=prometheus instance=2a042b27535dfb9eb2df65212baacc99 msg="running instance" name=2a042b27535dfb9eb2df65212baacc99
ts=2021-04-28T03:04:56.701399434Z caller=dedupe.go:112 agent=prometheus instance=2a042b27535dfb9eb2df65212baacc99 component=remote level=info remote_name=2a042b-96a2d3 url=https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push msg="Replaying WAL" queue=2a042b-96a2d3
ts=2021-04-28T03:04:56.701668886Z caller=dedupe.go:112 agent=prometheus instance=2a042b27535dfb9eb2df65212baacc99 component=remote level=debug remote_name=2a042b-96a2d3 url=https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push msg="Tailing WAL" lastCheckpoint= checkpointIndex=0 currentSegment=0 lastSegment=0
ts=2021-04-28T03:04:56.701825751Z caller=dedupe.go:112 agent=prometheus instance=2a042b27535dfb9eb2df65212baacc99 component=remote level=debug remote_name=2a042b-96a2d3 url=https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push msg="Processing segment" currentSegment=0
level=info ts=2021-04-28T03:04:56.703183025Z caller=kubernetes.go:264 component=loki component=loki loki_config=default component=discovery discovery=kubernetes msg="Using pod service account via in-cluster config"
level=debug ts=2021-04-28T03:04:56.705205493Z caller=manager.go:195 component=loki component=loki loki_config=default component=discovery msg="Starting provider" provider=kubernetes/0 subs="[kubernetes-pods-app-kubernetes-io-name kubernetes-pods-app kubernetes-pods-direct-controllers kubernetes-pods-indirect-controller kubernetes-other]"

// ... scraping starts ...

level=debug ts=2021-04-28T03:05:01.706054015Z caller=filetargetmanager.go:200 component=loki component=loki loki_config=default msg="new target" labels="{__address__=\"10.244.2.62\", __meta_kubernetes_pod_container_init=\"false\", __meta_kubernetes_pod_container_name=\"pg-dump\"}"
level=debug ts=2021-04-28T03:05:01.706940043Z caller=filetargetmanager.go:218 component=loki component=loki loki_config=default msg="dropping target, no labels"
level=debug ts=2021-04-28T03:05:01.718884367Z caller=filetargetmanager.go:200 component=loki component=loki loki_config=default msg="new target" labels="{__address__=\"10.244.2.76:8443\", __meta_kubernetes_pod_container_init=\"false\", __meta_kubernetes_pod_container_name=\"traefik\", __meta_kubernetes_pod_container_port_name=\"websecure\", __meta_kubernetes_pod_container_port_number=\"8443\", __meta_kubernetes_pod_container_port_protocol=\"TCP\"}"
level=debug ts=2021-04-28T03:05:01.719270054Z caller=filetargetmanager.go:249 component=loki component=loki loki_config=default msg="ignoring target, already exists" labels="{app=\"traefik\", container=\"traefik\", job=\"default/traefik\", namespace=\"default\", node_name=\"default-8yeni\", pod=\"traefik-5f8978f959-j8dlq\"}"

// ... lots more "dropping target, no labels" and "ignoring target, already exists" ...

level=debug ts=2021-04-28T03:05:01.720009753Z caller=filetarget.go:196 component=loki component=loki loki_config=default msg="no files matched requested path, nothing will be tailed" path=/var/log/pods/*25468897-53eb-412b-adc1-d38ab83bf438/traefik/*.log
// ... the above "no files matched requested path, nothing will be tailed" is repeated until the next scrape ...
```

Below is the Loki config I'm using for the Grafana Agent deployment pods:

```yaml
loki:
  configs:
    - name: default
      positions:
        filename: /tmp/positions.yaml
      clients:
        - url: https://logs-prod-us-central1.grafana.net/api/prom/push
          basic_auth:
            username: 12345
            password: GRAFANA_API_KEY
      scrape_configs:
        - job_name: kubernetes-other
          pipeline_stages:
            - cri: {}
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: app
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_label_component
              target_label: component
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_node_name
              target_label: node_name
            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              replacement: $1
              separator: /
              source_labels:
                - namespace
                - app
              target_label: job
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
              target_label: __path__
            - action: replace
              regex: true/(.*)
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
                - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
                - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
                - __meta_kubernetes_pod_container_name
              target_label: __path__
```

**Comment by rfratto** [comment]
Hi, the problem here is likely that the manifest you're missing volume mounts for the container to be able to find the logs. The manfest linked was just built specifically for Prometheus and is missing some settings required to get logs to work properly. (We'd like to build an all-in-one manifest but haven't gotten around to it yet. Sorry that the existing setup has given you some trouble.)

If you look at our [agent-loki example](https://github.com/grafana/agent/blob/main/production/kubernetes/agent-loki.yaml), you'll see the `/var/log` volume mount that should fix your problem:

```yaml
volumeMounts:
- mountPath: /etc/agent
  name: grafana-agent-logs
- mountPath: /var/log
  name: varlog
- mountPath: /var/lib/docker/containers
  name: varlibdockercontainers
  readOnly: true
# used for journald reading, you can omit this 
- mountPath: /etc/machine-id
  name: etcmachineid
  readOnly: true
```

and the corresponding volumes:

```yaml
volumes:
- configMap:
    name: grafana-agent-logs
  name: grafana-agent-logs
- hostPath:
    path: /var/log
  name: varlog
- hostPath:
    path: /var/lib/docker/containers
  name: varlibdockercontainers
# used for journald only
- hostPath:
    path: /etc/machine-id
  name: etcmachineid
```
