### ISSUE TITLE
Passing basic auth for kubernetes_sd_config

### ISSUE THREAD

**Issue by MikaelElkiaer** [grafana/agent#568]
Is this possible somehow?
I have not been able to find a way.

I have some pods in my cluster which require basic auth for their metrics endpoints.
Currently the agent is just getting 401's, but I cannot figure out how to add it via kubernetes_sd_config.
I was hoping that adding something along the lines of
```
- source_labels:
¦ ¦ - __meta_kubernetes_pod_annotation_prometheus_io_username
¦ action: replace
¦ target_label: __basic_auth_username__
¦ regex: (.+)
¦ replacement: $1
- source_labels:
¦ ¦ - __meta_kubernetes_pod_annotation_prometheus_io_password
¦ action: replace
¦ target_label: __basic_auth_password__
¦ regex: (.+)
¦ replacement: $1
```
would do the trick, but it doesn't seem to do anything at all.

**Comment by rfratto** [comment]
Hi, yes, the [scrape_config definition](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) supports basic_auth:

```yaml
- job_name: example-with-basic_auth
  basic_auth:
    username: foo
    password: bar
  kubernetes_sd_configs:
  - role: pod
  scrape_configs:
  - # ... 
```

Unfortunately, if you have multiple pods that require different credentials, you'll need to set up multiple scrape configs to do this.
