### ISSUE TITLE
Create a YAML config section to control node exporter

### ISSUE THREAD

**Issue by gotjosh** [grafana/agent#57]
# What we need to do

At the moment, `node_exporter` is controlled using a set of query parameters on the scrape URL. We'd like to avoid this and configure it using a similar structure to what we have today: YAML config.

# Implementation notes
- Add a new root key in the `Config` struct named `integrations` that holds a collection of exporters. e.g. A key for the collection in the case of `node_expoerter` would look like:

```YAML
server:
  log_level: info
  http_listen_port: 12345

prometheus:
  global:
    scrape_interval: 5s

integrations:
  node_exporter:
    an_example_option_here:
```

- Whatever we do, please keep in mind that in the future we'd like to load integrations from an individual file.
- Ensure we have proper documentation for the different keys too.
