### ISSUE TITLE
Mysql integration not able to collect Mysql 8.0+ select stats 

### ISSUE THREAD

**Issue by wally007** [grafana/agent#5759]
### What's wrong?

As mentioned in this bug ticket https://github.com/grafana/agent/issues/3169 
There is still an issue with Mysql integration when `info_schema.innodb_tablespaces` collector is enabled (even though the integration was updated to the latest version)

The `'INNODB_SYS_TABLESPACES` table was renamed to `'INNODB_TABLESPACES` in 8.0

### Steps to reproduce

How to reproduce ?
Install grafana-agent 0.37.4 (latest version)
enable Mysql integration and scrape Mysql 8.0+ instance
add `info_schema.innodb_tablespaces` to the collectors

```
  mysqld_exporter:
    scrape_interval: 20s
    enabled: true
    data_source_name: "{{ mysqld_exporter_user }}:{{ mysqld_exporter_pwd }}@unix(/var/lib/mysql/mysql.sock)/"
    set_collectors:
      - info_schema.innodb_tablespaces
 ```
 
 Observe the following error in the logs:
 
 ```
 grafana-agent[464257]: ts=2023-11-13T17:31:26.024020141Z caller=exporter.go:180 level=error integration=mysqld_exporter msg="Error from scraper" scraper=info_schema.innodb_tablespaces err="Error 1109 (42S02): Unknown table 'INNODB_SYS_TABLESPACES' in information_schema"

### System information

4.18.0-477.27.1.el8_8.x86_64

### Software version

version v0.37.4 (branch: HEAD, revision: 89ded9f2)

### Configuration

_No response_

### Logs

_No response_
