### ISSUE TITLE
Grafana agent support runAsNonRoot

### ISSUE THREAD

**Issue by HSoulat** [grafana/agent#5824]
### Request

Grafana agent should runAsNonRoot in order to follow [Kubernetes Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/). 

Currently use runAsNonRoot is not permited and if we set runAsUser the agent do not work correctly. 

### Use case

Some use case do not require to run the Agent as root.

**Comment by tpaschalis** [comment]
The new [helm chart](https://github.com/grafana/agent/tree/main/operations/helm/charts/grafana-agent) has supported securityContext for a long time now.

Are y'all referring to the Operator here?

**Comment by harishkashyap569** [comment]
@tpaschalis Agent fails to run when trying to run as nonroot.  Did it work for you when you try to run the agent as non-root? (in flow mode with clustering enabled) If yes, could you please share the Dockerfile?. I have also initiated some discussions on the agent slack channel. What I understood from the responses, currently it’s not possible to run as nonroot and there is work in progress for it.

**Comment by bcrisp4** [comment]
Is there any update on this? or any explanations as to why running as non-root does not work currently?

I prefer to run with a locked down securityContext, but this does not work (agent fails to become ready, but does not log any errors) 

e.g. this does not work
```yaml
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
```
