### ISSUE TITLE
Remote write interval greater than scrape interval

### ISSUE THREAD

**Issue by tonyplovich** [grafana/agent#587]
Hello,

Even though I have the global scrape_interval set at 2 minutes my Cortex instance is getting series with data points every 15 seconds.  I'm currently only using the agent to send node_exporter metrics.

My expectation would be that the TSDB wouldn't receive more data points than the agent is configured to collect via its scrap_interval.

```
# grafana-agent --version
agent, version v0.13.1 (branch: HEAD, revision: 05f26e6)
  build user:       runner@fv-az216-940
  build date:       2021-04-09T14:26:08Z
  go version:       go1.15.8
  platform:         linux/arm
```

```
# cat /etc/grafana-agent.yaml
# Sample config for Grafana Agent
# For a full configuration reference, see: https://github.com/grafana/agent/blob/main/docs/configuration-reference.md.
server:
  http_listen_address: '127.0.0.1'
  http_listen_port: 9090

prometheus:
  global:
    scrape_interval: 120s
  wal_directory: '/var/lib/grafana-agent'
  configs:
    # Example Prometheus scrape configuration to scrape the agent itself for metrics.
    # This is not needed if the agent integration is enabled.
    # - name: agent
    #   host_filter: false
    #   scrape_configs:
    #     - job_name: agent
    #       static_configs:
    #         - targets: ['127.0.0.1:9090']

loki:
  positions_directory: /opt/loki/
  configs:
    - name: loki
      clients:
        - url: https://loki.example.com/api/prom/push
          basic_auth:
            username: loki
            password: XXXXX
      scrape_configs:
        - job_name: messages
          static_configs:
            - targets:
              - localhost
              labels:
                __path__: /var/log/messages
                host: ${HOSTNAME}
        - job_name: syslog
          static_configs:
            - targets:
              - localhost
              labels:
                __path__: /var/log/syslog
                host: ${HOSTNAME}
        - job_name: journal
          journal:
            max_age: 12h
            labels:
              job: systemd-journal
              host: ${HOSTNAME}
          relabel_configs:
            - source_labels: ['__journal__systemd_unit']
              target_label: 'unit'

integrations:
  agent:
    enabled: true
    scrape_interval: 120s
  node_exporter:
    enabled: true
    include_exporter_metrics: true
    disable_collectors:
      - "mdadm"
    textfile_directory: /opt/textfiles
  prometheus_remote_write:
    - url: https://cortex.example.com/api/v1/push
      basic_auth:
        username: cortex
        password: XXXXX

```
