### ISSUE TITLE
Helm templating inconsistency with --namespace flag

### ISSUE THREAD

**Issue by edwardzjl** [grafana/agent#6040]
### What's wrong?

When I try to install Grafana Agent Flow using helm, I specified the `--namespace` flag, but the output seems wrong

The generated ServiceAccount resource did not have any `namespace` specified:

```yaml
# Source: grafana-agent/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent-flow
  labels:
    helm.sh/chart: grafana-agent-0.29.0
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent-flow
    
    app.kubernetes.io/version: v0.38.1
    app.kubernetes.io/managed-by: Helm
```

While the generated ClusterRoleBinding resource bounds ClusterRole to a namespaced ServiceAccount:

```yaml
# Source: grafana-agent/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-agent-flow
  labels:
    helm.sh/chart: grafana-agent-0.29.0
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent-flow
    
    app.kubernetes.io/version: v0.38.1
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-agent-flow
subjects:
  - kind: ServiceAccount
    name: grafana-agent-flow
    namespace: logging
```

### Steps to reproduce

```sh
helm repo add grafana https://grafana.github.io/helm-charts

helm repo update

helm template grafana-agent-flow grafana/grafana-agent --namespace logging --skip-tests > grafana-agent-flow.yaml
```

### Software version

Helm: `{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}`

Grafana Agent v0.38.1
