### ISSUE TITLE
Flow mode: process signals to stop

### ISSUE THREAD

**Issue by otaconix** [grafana/agent#6075]
### Request

It'd be nice if, when running in Flow Mode, the agent would process signals (SIGINT, SIGTERM and SIGQUIT) in such a way that it terminates the agent. This processing is currently done in the static mode, so it should be fairly straightforward to port this over to Flow Mode.

### Use case

I personally run Grafana Agent in a Docker Compose stack, and updating is sometimes frustrating, as Docker does send a signal to the container, which Grafana Agent in Flow Mode does not pick up. My Docker instance then waits 10 seconds for the process to exit willingly, after which it forcefully kills it.

I imagine this is an issue in other environments, such as Kubernetes, or even directly in service managers such as systemd.

**Comment by tpaschalis** [comment]
Hey there, thanks for opening an issue! 

The Agent _does_ [handle signals](https://github.com/grafana/agent/blob/e6b8ac7761b29d1f1f422a3e50b1b954d51965af/cmd/internal/flowmode/cmd_run.go#L428) in Flow mode; more specifically an interrupt or a SIGTERM for terminating the Agent as well as a SIGHUP for reloading the config.

```bash
$ ps aux | grep grafana-agent
tpaschalis       63258   0.0  0.7 410039856 121120 s003  S+    1:48PM   0:00.10 ./build/grafana-agent-flow run /Users/tpaschalis/river-configs/node-exporter.river
$ kill -SIGTERM 63258
...
ts=2024-01-09T11:49:25.81927Z level=info msg="component exited" component=prometheus.exporter.unix.foo
ts=2024-01-09T11:49:25.819551Z level=info msg="http server closed" service=http addr=memory err="http: Server closed"
ts=2024-01-09T11:49:25.819597Z level=info msg="http server closed" service=http addr=127.0.0.1:12345 err="http: Server closed"
```

Can you share more details about your config and setup (after redacting any sensitive info) so we can see if this is a bug and handle accordingly?

**Comment by otaconix** [comment]
Apologies for the delayed response, and for not looking hard enough at the source to see that signal handling is indeed in there.

Anyway, here's a setup that doesn't seem to terminate when Docker sends the TERM signal (only stopping after the 10s grace period):

```yaml
services:
  agent:
    image: grafana/agent:main
    restart: unless-stopped
    environment:
      AGENT_MODE: flow
      RANDOM: ${RANDOM}
    command:
      - run
      - --disable-reporting
      - --storage.path=/data
      - --server.http.listen-addr=:12345
      - /config.river
    volumes:
      - ./config.river:/config.river:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      skip_logging: true
```

```hcl
discovery.docker "docker" {
  host = "unix:///var/run/docker.sock"
}

loki.source.docker "docker" {
  host = "unix:///var/run/docker.sock"
  targets = discovery.docker.docker.targets
  forward_to = [loki.process.docker.receiver]
}

loki.process "docker" {
  stage.drop {
    older_than = "5s"
  }

  stage.sampling {
    rate = 0.001
  }

  forward_to = [loki.echo.docker.receiver]
}

loki.echo "docker" {}
```
