### ISSUE TITLE
Spanmetrics doesn't seem to be pushing metrics

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#617]
To reproduce, use this config file, replacing PROMETHEUS_URL, LOKI_URL, and TEMPO_URL as appropriate. 

```yaml
prometheus:
  configs:
    - name: default
      host_filter: false
      remote_write:
      - url: PROMETHEUS_URL
​
loki:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: LOKI_URL
tempo:
  configs:
  - name: default
    receivers:
      jaeger:
        protocols:
          grpc:
          thrift_binary:
          thrift_compact:
          thrift_http:
      otlp:
        protocols:
          http:
          grpc:
    push_config:
      endpoint: TEMPO_URL
    automatic_logging:
      backend: loki
      loki_name: default
      spans: true
      processes: true
      roots: true
    spanmetrics:
      latency_histogram_buckets: [2ms, 6ms, 10ms, 100ms, 250ms]
      dimensions:
        - name: http.method
          default: GET
        - name: http.status_code
        - name: peer.hostname
      prom_instance: default
```
