### ISSUE TITLE
otelconvert: invalid label when converting pipelines with names such as `metrics/2`

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#6600]
### What's wrong?

The way that the current conversion happens for multiple groups, is that separate components build their own labels by concatenating the group's 'name' along with the component ID.

https://github.com/grafana/agent/blob/72b08cae804624f444b1c7529aaa4148672b4db8/internal/converter/internal/otelcolconvert/converter.go#L127

Sometimes, in OpenTelemetry collector configs, pipelines are named like `metrics/2` which means the group ends with the name `2`. During conversion this means we may try to build component labels like `2_metrics_backend` which is not a valid river identifier and is rejected.

### Steps to reproduce

Try to convert a configuration which has a pipeline with a name (the part after the slash) that is not a valid identifier since its starts with a digit. One example is the following:

```
receivers:
  otlp/traces:
    protocols:
      grpc:
      http:

exporters:
  otlp/traces_backend:
    endpoint: database:34317

  otlp/metrics_backend:
    endpoint: database:44317

  otlp/metrics_backend/2:
    endpoint: database:54317

connectors:
  spanmetrics:

service:
  pipelines:
    traces:
      receivers: [otlp/traces]
      exporters: [otlp/traces_backend, spanmetrics]
    metrics:
      receivers: [spanmetrics]
      exporters: [otlp/metrics_backend]
    metrics/2:
      receivers: [spanmetrics]
      exporters: [otlp/metrics_backend/2]
```

Conversion should fail with 

```
unexpected diag count reach for diag: (Critical) failed to render Flow config: 1:23: expected block label to be a valid identifier, but got "2_metrics_backend/2" (and 2 more diagnostics)
```

**Comment by tpaschalis** [comment]
cc @rfratto the simplest solution here would be to swap around the two values; I _think_ it's more probable that all exporters/receivers have names that are valid identifiers.

Any concerns to doing that as a workaround?

**Comment by tpaschalis** [comment]
Same happens for component IDs. In OpenTelemetry, the following is a valid exporter definition.

```
exporters:
  otlp/metrics_backend/2:
    endpoint: database:4317

service:
  pipelines:
    traces:
    metrics/two:
      receivers: [spanmetrics]
      exporters: [otlp/metrics_backend/2]


```

We'd then try to build a label like `two_metrics_backend/2` which is not a valid River identifier either, so we could possibly use a better sanitization strategy.
