### ISSUE TITLE
Cannot set labels from windows_events log configuration when using logs:global:clients:external_labels

### ISSUE THREAD

**Issue by pmannozg** [grafana/agent#6635]
### What's wrong?

I have an external_labels block in my global configuation for logs.
```
         - url: <my url>
            external_labels:
              agent_hostname: "myhostname"
              instance: "myhostname:12345"
              environment: "dev"
              app: "app"
              os: "windows"
```
In my configs I have windows_events
```
        configs:
          - name: win_logs
            scrape_configs:
              - job_name: windows_app
                windows_events:
                  bookmark_path: 'C:\Program Files\Grafana Agent\bookmark\app_bookmark.xml'
                  use_incoming_timestamp: false
                  eventlog_name: "Application"
                  xpath_query: '*'
                  labels:
                    job: windows_app
                relabel_configs:
                  - source_labels: [ 'computer' ]
                    action: drop
```
In Loki I do not see the added job label.

If I add a job label to the external_labels, the job label shows up.
If I try to relabel the job label in relabel_configs in the windows_events, the job label remains as it is in external_labels.

### Steps to reproduce

See configuration example above.

### System information

Windows 2016 Server

### Software version

Grafana Agent 0.39.2

### Configuration

```text
server:
  log_level: debug
logs:
  global:
    clients:
    - url: https://loki.domain.local/loki/api/v1/push
      external_labels:
        agent_hostname: host00
        instance: host00:12345
        environment: dev
        app: myapp
        os: windows
  positions_directory: C:\Program Files\Grafana Agent\positions
  configs:
  - name: win_logs
    scrape_configs:
    - job_name: windows_app
      windows_events:
        bookmark_path: C:\Program Files\Grafana Agent\bookmark\app_bookmark.xml
        use_incoming_timestamp: false
        eventlog_name: Application
        xpath_query: '*'
        labels:
          job: windows_app
      relabel_configs:
      - source_labels:
        - computer
        action: drop
integrations:
  scrape_integrations: true
  agent:
    enabled: true
  windows_exporter:
    enabled: true
    enabled_collectors: cpu,cpu_info,memory,net,process,service,tcp,time,cs,logon,logical_disk,os,iis
```

**Comment by pmannozg** [comment]
Actually even if I remove the external_labels and just use the labels: section of the windows_events It does not work
```
              - job_name: windows_app
                windows_events:
                  bookmark_path: 'C:\Program Files\Grafana Agent\bookmark\app_bookmark.xml'
                  use_incoming_timestamp: false
                  eventlog_name: "Application"
                  xpath_query: '*'
                  labels:
                    agent_hostname: host00
                    instance: host00:12345
                    environment: dev
                    app: myapp
                    os: windows
                    job: windows_app
                relabel_configs:
                  - source_labels: [ 'computer' ]
                    action: drop
```

**Comment by pmannozg** [comment]
I was able to get the job label set by relabling an existing label
```
              - job_name: windows_app
                windows_events:
                  bookmark_path: 'C:\Program Files\Grafana Agent\bookmark\app_bookmark.xml'
                  use_incoming_timestamp: false
                  eventlog_name: "Application"
                  xpath_query: '*'
                relabel_configs:
                  - source_labels: [ 'computer' ]
                    target_label: job
                    replacement: windows_app
```
