### ISSUE TITLE
Can't seem to limit series with integrations

### ISSUE THREAD

**Issue by the-dansan** [grafana/agent#686]
Hi there,

We are deploying a fleet of raspberry pi 4s (raspian) with grafana-agent installed to ship logs and some selected metrics -- except we can't seem to select the metrics.

Given a configuration file like this on agent v 0.15:

```yaml
integrations:
  agent:
    enabled: false
  node_exporter:
    enabled: true
prometheus:
   ....
server:
   .....
loki:
   ....
```

We still receive a boggling number of series, including all of the `agent_` series. I've experimented quite a bit with the options can't find anything that works. Originally I thought that I could use `set_collectors` as documented in the config reference, but that doesn't seem to get me there to reduce the number of collectors --even disabling it doesn't appear to work.

For a single pi:
![Screen Shot 2021-06-24 at 2 21 54 PM](https://user-images.githubusercontent.com/18700228/123314019-14bf6e80-d4f8-11eb-94d7-66c9b14938cc.png)
