### ISSUE TITLE
nil pointer panic when using snmp with v0.40.5

### ISSUE THREAD

**Issue by heathcliff26** [grafana/agent#6927]
### What's wrong?

When running grafana-agent docker image v0.40.5 and trying to collect metrics with snmp, the container crashes with a nil pointer exception.
Downgrading to v0.40.4 solves the problem.

### Steps to reproduce

1. start grafana-agent container v0.40.5 with snmp enabled

### System information

Fedora CoreOS 40.20240504.3.0 with k3s v1.30.0+k3s1

### Software version

v0.40.5

### Configuration

config-file:
```
# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
---
# For a full configuration reference, see: https://grafana.com/docs/agent/latest/configuration/.
server:
  log_level: warn

integrations:
  agent:
    enabled: true
    relabel_configs:
    - replacement: <redacted_hostname>
      target_label: instance
    - replacement: <redacted_hostname>
      target_label: agent_hostname
    - action: replace
      target_label: job
      replacement: "integrations/agent-check"
    metric_relabel_configs:
    - action: keep
      regex: (prometheus_target_.*|prometheus_sd_discovered_targets|agent_build.*|agent_wal_samples_appended_total|process_start_time_seconds)
      source_labels:
      - __name__
  prometheus_remote_write:
  - basic_auth:
      password: "${GRAFANA_TOKEN}"
      username: <redacted>
    url: <redacted>

  # SNMP scraping for Synology NAS
  snmp:
    enabled: true
    relabel_configs:
      - action: replace
        source_labels: [job]
        regex: (^.*snmp)\/(.*)
        target_label: job_snmp
        replacement: $1
      - action: replace
        source_labels: [job]
        regex: (^.*snmp)\/(.*)
        target_label: snmp_target
        replacement: $2
      - replacement: <redacted_hostname>
        target_label: instance
      - replacement: <redacted_hostname>
        target_label: 'agent_hostname'
    snmp_targets:
      - name: <redacted_hostname>
        address: <redacted_snmp_client>
        auth: public_v2
        module: if_mib

logs:
  configs:
  - clients:
    - basic_auth:
        password: "${GRAFANA_TOKEN}"
        username: <redacted>
      url: <redacted>
    name: integrations
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
    - job_name: integrations/syslog
      syslog:
        listen_address: 0.0.0.0:1514
        listen_protocol: tcp
        idle_timeout: 60s
        label_structured_data: yes
        labels:
          job: "integrations/syslog"
          instance: <redacted_hostname>
      relabel_configs:
        - source_labels: ['__syslog_message_hostname']
          target_label: 'host'
        - replacement: <redacted_hostname>
          target_label: 'agent_hostname'

```
deployment:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-agent
  namespace: grafana-syslog
  labels:
    app: syslog-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syslog-agent
  template:
    metadata:
      labels:
        app: syslog-agent
    spec:
      containers:
        - name: grafana-agent
          envFrom:
            - secretRef:
                name: syslog-agent-diskstation
          image: docker.io/grafana/agent:v0.40.4
          args: ["--disable-reporting", "--config.file=/etc/agent/agent.yaml","--config.expand-env" ,"--metrics.wal-directory=/etc/agent/data"]
          ports:
            - name: syslog
              containerPort: 1514
              protocol: TCP
          volumeMounts:
            - name: grafana-agent-config
              mountPath: /etc/agent/agent.yaml
              subPath: agent.yaml
      volumes:
        - name: grafana-agent-config
          configMap:
            name: syslog-agent
            items:
              - key: grafana-agent.yaml
                path: agent.yaml
```

### Logs

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x585cc25]
goroutine 665 [running]:
github.com/prometheus/snmp_exporter/collector.Collector.collect({{0x8ca1848, 0xc0031b0b40}, {0xc0049e8403, 0x14}, 0xc0023b0120, {0xc0049e83e4, 0x9}, {0xc0049526f0, 0x1, 0x1}, ...}, ...)
 /go/pkg/mod/github.com/prometheus/snmp_exporter@v0.26.0/collector/collector.go:363 +0x305
github.com/prometheus/snmp_exporter/collector.Collector.Collect.func1(0xc001ba1a40?)
 /go/pkg/mod/github.com/prometheus/snmp_exporter@v0.26.0/collector/collector.go:458 +0x8d1
created by github.com/prometheus/snmp_exporter/collector.Collector.Collect in goroutine 664
 /go/pkg/mod/github.com/prometheus/snmp_exporter@v0.26.0/collector/collector.go:432 +0x13d
```

**Comment by db-wally007** [comment]
same here - simple upgrade of the podman container fails (I'm using flow configuration)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x581d065]

goroutine 723 [running]:
github.com/prometheus/snmp_exporter/collector.Collector.collect({{0x8c55e10, 0xc004c04a80}, {0xc005df40de, 0xb}, 0xc001cb4870, {0x79a6bb0, 0x9}, {0xc001ba42f8, 0x1, 0x1}, ...}, ...)
        /go/pkg/mod/github.com/prometheus/snmp_exporter@v0.26.0/collector/collector.go:363 +0x305
github.com/prometheus/snmp_exporter/collector.Collector.Collect.func1(0xc003376440?)
        /go/pkg/mod/github.com/prometheus/snmp_exporter@v0.26.0/collector/collector.go:458 +0x8d1
created by github.com/prometheus/snmp_exporter/collector.Collector.Collect in goroutine 722
        /go/pkg/mod/github.com/prometheus/snmp_exporter@v0.26.0/collector/collector.go:432 +0x13d

```

Rollback to 0.40.4 = works fine.

**Comment by ptodev** [comment]
Hi, apologies for this issue. It was fixed in v0.41.0 via #6921

**Comment by db-wally007** [comment]
I havent tested 0.41.0 but 0.41.1 this is still an issue

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x581d065]

goroutine 718 [running]:
github.com/prometheus/snmp_exporter/collector.Collector.collect({{0x8c55e10, 0xc005379680}, {0xc004a575de, 0xb}, 0xc0033a8360, {0x79a6bb0, 0x9}, {0xc004d8e968, 0x1, 0x1}, ...}, ...)
        /go/pkg/mod/github.com/prometheus/snmp_exporter@v0.26.0/collector/collector.go:363 +0x305
github.com/prometheus/snmp_exporter/collector.Collector.Collect.func1(0xc0057e82a0?)
        /go/pkg/mod/github.com/prometheus/snmp_exporter@v0.26.0/collector/collector.go:458 +0x8d1
created by github.com/prometheus/snmp_exporter/collector.Collector.Collect in goroutine 717
        /go/pkg/mod/github.com/prometheus/snmp_exporter@v0.26.0/collector/collector.go:432 +0x13d
```

**Comment by ptodev** [comment]
Hi @db-wally007! Do you mind sharing your Agent config file please (with secrets redacted)? I just tried v0.41.1 with this config, and it worked without issues:

```yaml
server:
  log_level: debug
integrations:
  snmp:
    enabled: true
    scrape_interval: 1m
    scrape_timeout: 30s
    snmp_targets:
      - name: testing
        address: demo.pysnmp.com
        module: if_mib
        auth: public_v2
```
