### ISSUE TITLE
timestamp format not recognised

### ISSUE THREAD

**Issue by davordbetter** [grafana/agent#6976]
### What's wrong?

Log are read via grafana-agent (ansible role, installed as service) on VM.
Log have ISO8601 timestamp format and look like this:

```
[2024-07-09T14:25:42,786+02:00] TRACE PolicyExecutionResource [01fe0291-***-***-a9d2-***] - Result of policy ...
[2024-07-09T14:25:42,786+02:00] INFO PolicyExecutionAuditorImpl [01fe0291-***-***-a9d2-***] - {"callId....
```

grafana-agent log reading config
```
      - job_name: "application_logs" 
        static_configs:
          - targets:
              - localhost
            labels:
              instance: "{{ ansible_hostname }}"
              environment: "{{ monitoringGrafanaAgent_environment }}"
              __path__: "{{ monitoringGrafanaAgent_defaultHomeDir }}/*/latest/logs/server.log"
        pipeline_stages:
          - regex:
              source: filename
              expression: '{{ monitoringGrafanaAgent_defaultHomeDir }}/(?P<app>[^/]+)/latest/logs/server\.log'
          - multiline:
              firstline: '^[(.*)] '
              max_wait_time: 3s
              max_lines: 1024
          - regex:
              expression: '^\[(?P<time>(.*))\] (?P<level>\w+) '
          - timestamp:
              source: time
              format: '2024-12-20T09:14:58,381+02:00'
          - labels:
              app:
              level:
```

But when viewing log in Loki, timestamp does not match...

![Screenshot 2024-07-09 at 14 31 27](https://github.com/grafana/agent/assets/145570198/fddd9f94-a829-4185-b891-7382b2819643)

I'm missing something here, but can't see where is the issue.
setting grafana-agent to debug level does not return any useful line for me or any error

### Steps to reproduce

use promtail config as mention above and logs sample

### System information

Oracle Linux

### Software version

0.41.1

### Configuration

```text
- job_name: "application_logs" 
        static_configs:
          - targets:
              - localhost
            labels:
              instance: "{{ ansible_hostname }}"
              environment: "{{ monitoringGrafanaAgent_environment }}"
              __path__: "{{ monitoringGrafanaAgent_defaultHomeDir }}/*/latest/logs/server.log"
        pipeline_stages:
          - regex:
              source: filename
              expression: '{{ monitoringGrafanaAgent_defaultHomeDir }}/(?P<app>[^/]+)/latest/logs/server\.log'
          - multiline:
              firstline: '^[(.*)] '
              max_wait_time: 3s
              max_lines: 1024
          - regex:
              expression: '^\[(?P<time>(.*))\] (?P<level>\w+) '
          - timestamp:
              source: time
              format: '2024-12-20T09:14:58,381+02:00'
          - labels:
              app:
              level:
```

### Logs

```text
[2024-07-09T14:25:42,786+02:00] TRACE PolicyExecutionResource [01fe0291-***-***-a9d2-***] - Result of policy ...
[2024-07-09T14:25:42,786+02:00] INFO PolicyExecutionAuditorImpl [01fe0291-***-***-a9d2-***] - {"callId....
```
