### ISSUE TITLE
Add ability to specify config-reloader image

### ISSUE THREAD

**Issue by marcusbooyah** [grafana/agent#764]
Currently it is possible to specify the image for the `grafana-agent`, but it is not possible to do the same for the `config-reloader` container, as it is [hard coded](https://github.com/grafana/agent/blob/02c19c2b8a5b113b22541e49e9c908d0cf3e894b/pkg/operator/resources.go#L362) to `quay.io/prometheus-operator/prometheus-config-reloader:v0.47.0`.

It would be nice to be able to specify the container for `config-reloader`, just like we can for the `grafana-agent`.

**Comment by rfratto** [comment]
Thanks, this is something we can consider adding. This will probably be something we support as a flag to the operator instead of adding it into the CRD, though.
 
In the meantime, there's a workaround to override the image. You can modify the [`containers`](https://github.com/grafana/agent/blob/1a880a3343530701700cd6923b9d1ba3870fe603/production/operator/crds/monitoring.grafana.com_grafana-agents.yaml#L654) field on the GrafanaAgent CRD to change the image:

```
apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: grafana-agent-example
  namespace: default
  labels:
    app: grafana-agent-example
spec:
  image: grafana/agent:v0.18.0
  containers:
  - name: config-reloader 
     image: CUSTOM_IMAGE
```

This will use a [strategic merge patch](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/) with the generated container and leave everything the same except for the image.
