### ISSUE TITLE
Auto-tagging spans provides misleading results for pods belonging in a istio service mesh

### ISSUE THREAD

**Issue by PatTheSilent** [grafana/agent#795]
I was trying to leverage grafana-agent's auto-tagging of spans and grafan's feature of jumping from Tempo traces to Loki logs.
My Pods are a part of a istio service mesh. They all have a istio-proxy sidecar and a istio-init initContainer. To little suprise I've learned that grafana agent was incorrectly tagging my spans with the istio-init container (didn't debug why but my guess is that because it's the first container). So I decided on adding the container attribute from within the application
```dotnet
var containerName = Environment.GetEnvironmentVariable("CONTAINER_NAME");
if (!string.IsNullOrWhiteSpace(containerName))
{
  attributes.Add(new KeyValuePair<string, object>("container", containerName));
}
```
but that didn't work because `UpsertString` is called on attributes.
https://github.com/grafana/agent/blob/997675b53a8e1685ee34f00a6dcc18e8ffa852f8/pkg/tempo/promsdprocessor/prom_sd_processor.go#L115

So I'd propose changing that to `InsertString` which would leave the original value. I've tested that on my environment and it works as expected.

**Comment by joe-elliott** [comment]
So you can probably use a prometheus [action](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_action) to drop the containers you are not interested in.

Your config may look something like:
```
  scrape_configs:
    - kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_container_name
          target_label: container
```

Perhaps try adding:

```
  scrape_configs:
    - kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - action: drop
          source_labels:
            - __meta_kubernetes_pod_container_name
          regex: istio-init|istio-proxy|<more containers i don't care about>
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_container_name
          target_label: container
```
