### ISSUE TITLE
Span id not propagated to loki

### ISSUE THREAD

**Issue by bputt-e** [grafana/agent#816]
We're looking to use the full integration of loki/prometheus/tempo and are using the autologging feature for traces. It appears the span id is not being included in the logs for loki which causes some issues with integration throughout grafana.

How can we go about getting the span id added to loki as a part of the automatic logging?

Grafana version: 8.1.1
Agent version: 0.18.1

**Loki log:**
![image](https://user-images.githubusercontent.com/60984725/129112210-e39211c9-7358-4772-9350-95b42b2239b6.png)

**Clicking the Tempo button:**
![image](https://user-images.githubusercontent.com/60984725/129112261-520201c2-db61-4941-b7ad-29a66846afac.png)

**Clicking the log icon inside the tempo screenshot:**
![Screenshot at 2021-08-11 18-42-36](https://user-images.githubusercontent.com/60984725/129113272-58ec689f-7819-44e0-adc5-abfecd025cf9.png)
![image](https://user-images.githubusercontent.com/60984725/129112296-1e19f477-8c4b-49b5-b4fb-0e3cda3f20d8.png)

**Our loki datasource:**
![image](https://user-images.githubusercontent.com/60984725/129112357-66623de4-0662-4209-b56c-d3c656e0b1f5.png)

**Our tempo datasource:**
![image](https://user-images.githubusercontent.com/60984725/129112476-a748cfce-a0aa-42bd-acf6-89ea398b4e35.png)

**Agent yaml**
```
server:
    http_listen_port: 12345
    log_level: info 
loki:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki-loki-distributed-distributor:3100/loki/api/v1/push
tempo:
    configs:
      - batch:
            send_batch_size: 1000
            timeout: 5s
        name: default
        receivers:
          otlp:
            protocols:
              grpc: null
        remote_write:
          - endpoint: tempo-tempo-distributed-distributor:4317
            insecure: true
        automatic_logging:
          backend: loki
          loki_name: default
          roots: true
          processes: true
          spans: true
```
