### ISSUE TITLE
Reload: Changing global scrape_interval does not modify integrations

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#827]
For the following config file:

```yaml
prometheus:
  global:
    scrape_interval: 60s 
    remote_write: []
integrations:
  node_exporter:
    enabled: true 
```

Do the following to reproduce: 

1. Start the agent 
2. Modify the config file and change the scrape_interval to 15s 
3. Call the `/-/reload` endpoint 
4. Observe that node_exporter is being scraped every 60 seconds

If you configure remote_write, you can observe the scrape_interval being unchanged by querying for `count_over_time(node_uname_info[1m])`. It will be 1 when there's only 1 sample per minute (60s scrape_interval) and 4 when there are 4 samples per minute (15s scrape_interval)
