### ISSUE TITLE
Windows_exporter metric_relabel_config

### ISSUE THREAD

**Issue by oriondvd** [grafana/agent#863]
I use Grafana Cloud with windows_exporter integration.
Here is my agent-config.yaml

```
server:
  http_listen_port: 12345
  #log_level: debug
prometheus:
  wal_directory: C:\ProgramData\grafana-agent-wal
  global:
    scrape_interval: 15s
    remote_write:
    - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
      basic_auth:
        username: USERNAME
        password: PASSWORD
  configs:
    - name: integrations
integrations:
  windows_exporter:
    enabled: true
    enabled_collectors: "system"
    relabel_configs:
      - source_labels: ['__name__']
        regex: 'windows_system_system_up_time'
        action: keep
```
**Please help to drop some metrics.** I need to keep only one metric with name ‘windows_system_system_up_time’ - all other metrics need to be droped.

**Comment by mattdurham** [comment]
We have seen some inconsistencies with using  `__name__`, can you try with ID or `__address__`?

**Comment by mattdurham** [comment]
I think there seems to be an issue with __name__, apologies for suggesting address since that wouldn't solve your problem.

**Comment by mattdurham** [comment]
You need to use *metric_relabel_configs* instead of *relabel_configs* then it should behave properly.

**Comment by oriondvd** [comment]
Thanks for your answers, but I've tried both: _metric_relabel_configs_ and _relabel_configs_ - and both didn't work
I`ve solve the problem in this way:
```
server:
  http_listen_port: 12345
prometheus:
  wal_directory: C:\ProgramData\grafana-agent-wal
  global:
    scrape_interval: 15s
    remote_write:
    - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
      basic_auth:
        username: LOGIN
        password: PASS
      write_relabel_configs:
      - source_labels: [__name__]
        regex: windows_system_system_up_time|windows_os_info|windows_cs_hostname|windows_cpu_time_total|windows_cs_logical_processors|windows_cs_physical_memory_bytes|windows_os_physical_memory_free_bytes|windows_logical_disk_free_bytes|windows_logical_disk_size_bytes|windows_net_bytes_total|windows_net_current_bandwidth|windows_logical_disk_write_bytes_total|windows_logical_disk_read_bytes_total|windows_service_status
        action: keep
      - source_labels: [__address__]
        regex: '.*'
        target_label: hostname
        replacement: 'Мой компьютер'
      - source_labels: [__address__]
        regex: '.*'
        target_label: agent_hostname
        replacement: 'Мой компьютер'
  configs:
    - name: integrations
integrations:
  windows_exporter:
    enabled: true
    enabled_collectors: "os,system,cs,logical_disk,cpu,net,service"
    logical_disk:
      blacklist: 'HarddiskVolume2|HarddiskVolume3|HarddiskVolume4'
    service:
      where_clause: "Name='1c:enterprise 8.3 server agent (x86-64)' or Name='Apache2.2' or Name='MSSQLSERVER' or Name='1C_WebSocket_3221' or Name='1C_WebSocket_3222'"
```
