### ISSUE TITLE
Integration with OhmGraphite

### ISSUE THREAD

**Issue by oriondvd** [grafana/agent#889]
Can anyone help me integrate [Grafana Agent for Windows](https://grafana.com/blog/2021/04/22/weve-added-first-class-windows-support-to-grafana-agent/) with [OhmGraphite](https://github.com/nickbabcock/OhmGraphite)?
I've tried such configuration of _agent-config.yaml_, but it doesn't work:
```
server:
  http_listen_port: 12345
prometheus:
  wal_directory: C:\ProgramData\grafana-agent-wal
  global:
    scrape_interval: 15s
    remote_write:
    - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
      basic_auth:
        username: LOGIN
        password: PASS
  configs:
    - name: integrations
    - name: ohmgraphite
      host_filter: false
      scrape_configs:
        - job_name: ohmgraphite
          static_configs:
          - targets: ['localhost:4445']
integrations:
  windows_exporter:
    enabled: true
```
