### ISSUE TITLE
Jsonnet library and quickstart scripts use the same `ClusterRoleBinding` name and fight over subject namespace

### ISSUE THREAD

**Issue by eamonryan** [grafana/agent#928]
I've noticed that when deploying multiple copies of the agent to a single Kubernetes cluster, especially via different methods for things like scoped testing, there is a scenario where the jsonnet library and the quickstart scripts fight over a namespace subject:

https://github.com/grafana/agent/blob/ec53e841ac00ad707a477887e850e4db83cd14bd/production/tanka/grafana-agent/v1/internal/agent.libsonnet#L20-L33

and

https://github.com/grafana/agent/blob/main/production/tanka/grafana-agent/v2/internal/base.libsonnet#L23-L32

These create a `ClusterRoleBinding` named `grafana-agent` that looks like:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-agent
subjects:
- kind: ServiceAccount
  name: grafana-agent
  namespace: grafana-agent
```

However, the `agent-bare.yaml` at https://github.com/grafana/agent/blob/3a33bbf228b40ed3d1f46799cbf20f4cef44f7f7/production/kubernetes/agent-bare.yaml also creates a `ClusterRoleBinding` with the same name.

https://github.com/grafana/agent/blob/3a33bbf228b40ed3d1f46799cbf20f4cef44f7f7/production/kubernetes/agent-bare.yaml#L29-L40

So the result is that the `ClusterRoleBinding` itself is modified and the `subjects` section is altered on every alternate deploy to swap the namespace back and forth between the namespaces where you did your two deploys.

A relatively easy way to fix this might be to rename the deployments/roles/accounts etc. in one or both of the library or quickstart scripts to be different so they are not both just `grafana-agent`.
