### ISSUE TITLE
Multiple prometheus_remote_write for one configuration

### ISSUE THREAD

**Issue by Amet13** [grafana/agent#938]
Hey.

In my case I installed an agent with this configuration:
```
integrations:
  node_exporter:
    enabled: true
  prometheus_remote_write:
  - basic_auth:
      password: my-password
      username: my-username
    url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
loki:
  ...
prometheus:
  configs:
  - name: selfhosted
    remote_write:
    - url: http://172.31.46.66:9090/api/v1/write
    scrape_configs:
      - job_name: rails-exporter
        metrics_path: /metrics
        scrape_interval: 30s
        static_configs:
        - targets: ['localhost:9394']
          labels:
            job: rails-exporter
            host_ip: {{ ansible_host }}
            server_name: {{ server_name }}
  global:
    scrape_interval: 60s
    remote_write:
    - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
      basic_auth:
        password: my-password
        username: my-username
  wal_directory: /tmp/grafana-agent-wal
server:
  http_listen_port: 12345
```

Here, I want to send node_exporter metrics to Grafana Cloud, which I set in `prometheus_remote_write` for integrations and in `remote_write` in global configuration.
At the same time, I want to send some metrics from `rails-exporter` to my own self-hosted Prometheus `http://172.31.46.66:9090/api/v1/write`.

In the current configuration, I expect to see that rails exporter metrics come to self-hosted and node_exporter metrics to Grafana Cloud. But in my case, rails-exporter metrics come to my self-hosted Prometheus `http://172.31.46.66:9090/api/v1/write` and node configuration doesn't work.

**Is there any option to use multiple remote_writes for different configurations?
Thanks in advance.**
