### ISSUE TITLE
automatic_logging labels containing period cause loki to return 400 error

### ISSUE THREAD

**Issue by frankbohman** [grafana/agent#941]
Should it be possible to add for example service.name or span.kind as labels to index traces in loki ? 

Or perhaps have some way to rewrite them in the agent?

Loki return: Bad Request (400): error parsing labels: parse error at line 1, col 9: syntax error: unexpected ., expecting = or != or =~ or !~"

My configuration:

```yaml
automatic_logging:
          backend: logs_instance
          logs_instance_name: default
          overrides:
            service_key: app
          spans: true
          processes: true
          roots: true
          process_attributes:
            - service.name
          span_attributes:
            - span.kind
          labels:
            - service.name
            - span.kind
```
